### ISSUE TITLE
Consider creating a "top level" package

### ISSUE THREAD

**Issue by stephenmathieson** [segmentio/evergreen#103]
I'm currently building a small app using Evergreen and have found it super tedious to have to keep `npm install`ing packages. @stevenmiller888 and I briefly discussed the idea of creating a "top level" package which exports all Evergreen components so this need is removed.

In order to keep our compiled production bundle size reasonable, maybe we also create a Babel plugin to rewrite `import { TableCell } from 'evergreen'` to `import { TableCell } from 'evergreen-table'`?

Thoughts? @jeroenransijn

**Comment by jeroenransijn** [comment]
Yeah this is somewhat annoying with a mono-repo. It seems reasonable enough to do this.

We can consider something like `evergreen-core` or whatever with a opinionated subset of components if bundle size becomes an issue.

**Comment by jeroenransijn** [comment]
I am wondering what other mono-repo's do here, or if there is any best practices.

**Comment by Rowno** [comment]
Can't we just have a single package like the react-ui-library? It seems to me that this monorepo thing is super over complicating things and I don't really see the benefits.

**Comment by Rowno** [comment]
When webpack's tree shaking, bundle size shouldn't really be an issue with having a single package.

**Comment by jeroenransijn** [comment]
I am still onboard on the mono-repo thing. A single package makes sense to me, so I imagine we can have best of both worlds with this approach.

Why I am still in favor of a mono-repo is how I imagine the future of Evergreen could play out. It will become easier for people to start adopting evergreen outside of Segment with less sophisticated builds. It is also a sign of maturity of a component library — this might be a biased opinion.  Potentially it's cleaner to extend or use certain components when you make a package that says build on top of `evergreen-popover` or `evergreen-positioner`.

I am happy to reflect back on wether a mono-repo is still the right choice once every while during the coming year(s). But I don't think it is a high priority right now to get rid of it at this point. I do think it's smart to make a `evergreen` package that is more accessible and lowers friction of using and adopting evergreen.

Overall I believe in making consumption easy and possible in whatever way possible.

@Rowno can you explain what exactly the mono-repo is overcomplicating? If it's consumption this would solve it right?

**Comment by stephenmathieson** [comment]
I think all of these components should stay in the same repository (a "monorepo"), but I do not see any benefit of exposing multiple packages (via Lerna). Even "mature" libraries like MaterialUI ship a single package to NPM and let the consumers of the library take what they want from it.

**Comment by jeroenransijn** [comment]
@stephenmathieson and @Rowno I trust both of you if you guys feel it is the right decision. I don't see it as a high priority right now compared to writing docs and writing more component. If you guys feel different about it and want to take this responsibility I am more than happy to jump on board.

**Comment by jeroenransijn** [comment]
Closing this in favor of #117
