### ISSUE TITLE
Please add props to Storybook

### ISSUE THREAD

**Issue by stephenmathieson** [segmentio/evergreen#104]
Currently I have to dig thru code in order to find what props an exported component accepts. It would be extremely useful if the Storybook included this information.

**Comment by jeroenransijn** [comment]
We are working on actual documentation in the docs branch: http://evergreen.surge.sh/components/buttons

I want to avoid putting too much documentation in Storybook and use it mainly what it is designed for. I am closing this issue. See also #82

**Comment by stephenmathieson** [comment]
Ah, this is exactly what I was looking for!

Maybe the documentation site should be linked to somewhere?
