### ISSUE TITLE
Checkbox Label is too small

### ISSUE THREAD

**Issue by cdedreuille** [segmentio/evergreen#1050]
I believe there's an inconstancy with the checkbox label being 12px compared to all other labels being 14px. In my case I'm trying to have a list of checkboxes on the left and some associated text on the right but the checkbox label doesn't match the text and is quite hard to read as 12px is quite small. I'm not sure it's even accessible enough.

It would be great if the checkbox label could be pushed up to 14px.

**Comment by akleiner2** [comment]
Great callout here @cdedreuille. You're right - looks like the `<Checkbox />` implementation is using `<Text size={300} />` under the hood. Agreed that this is probably too small, but I'd be weary about updating the underlying visual styles as a non-breaking change. 

Evergreen has a `Label` export -- could you potentially compose that instead? 

```
<>
    <Checkbox id="my-checkbox" onChange={(e) => ...} /> 
    <Label htmlFor="my-checkbox" /> 
</>

```

What do y'all think @mshwery @colinlohner ?

**Comment by Anmol270900** [comment]
Hi! Is this issue still open to work on? May I work on it? 😅

**Comment by akleiner2** [comment]
Closing this out as there's a viable workaround!
