### ISSUE TITLE
`border` prop for Pane component does not allow for custom borders

### ISSUE THREAD

**Issue by MrAlexLau** [segmentio/evergreen#1051]
If I have a `Pane` with a custom border like this:

```
<Pane border="2px solid blue">
  I would love to be bordered.
</Pane>
```

A border will not show up (even though that's how ui-box would handle it). Because of the way [the border prop is handled for a Pane](https://github.com/segmentio/evergreen/blob/731e46e/src/layers/src/Pane.js#L62-L89), you instead currently have to declare each side's border directly to accomplish the above:

```
<Pane 
  borderTop="2px solid blue" 
  borderRight="2px solid blue" 
  borderBottom="2px solid blue" 
  borderLeft="2px solid blue"
>
  I am now bordered!
</Pane>
```

I don't think this is intentional - but perhaps I'm wrong. Per [the docs](https://evergreen.segment.com/components/layout-primitives) the border prop for a `Pane` is defined as:
> Can be a explicit border value or a boolean. Values: true, muted, default.

I would propose that border values be resolved with the same precedence established in the code linked above, except with a fallback to the `border` prop when no explicit side is present. Basically if you don't have `borderLeft`, `borderRight`, etc. but *do* have a `border` prop present, use the border prop.

**Comment by mshwery** [comment]
This is already fixed in the next version, but would be supportive of also fixing it in v5!

**Comment by MrAlexLau** [comment]
@mshwery - glancing at [the analogous code](https://github.com/segmentio/evergreen/blob/0befcff/src/layers/src/Pane.js#L33-L48) for v6, the approach seems quite a bit different. Would you recommend trying to mimic this approach for v5 if someone was going to fix this? Or would it make more sense to just modify the existing function?

**Comment by colinlohner** [comment]
Yeah I can look into a patch for this

**Comment by mshwery** [comment]
@colinlohner @MrAlexLau the main difference with the v6 code is actually [here](https://github.com/segmentio/evergreen/blob/0befcff64b901b20f90df15c2163df1e3364786a/src/themes/classic/components/pane.js#L22) we return `border` if `value` is undefined or null. I've just realized now that we probably should only behave like this when the value is explicitly `undefined` because `null` should unset the value.

**Comment by mshwery** [comment]
Could do something like
```js
      return typeof borderSideProperty === 'undefined' ? border : borderSideProperty
```

**Comment by mshwery** [comment]
Closing as this is quite stale. PRs welcome though!
