### ISSUE TITLE
[Docs] Icons: no "import" and 404 on the github page

### ISSUE THREAD

**Issue by kud** [segmentio/evergreen#1062]
The doc https://evergreen.segment.com/components/icons/ doesn't explain how to import it. And the github link is broken.

**Comment by mshwery** [comment]
Hello! Thanks for sharing the opportunity to make this a little clearer. The github link is definitely a bug (cc @akleiner2 @colinlohner)

While there is no example explicitly showing an import statement, all of the component names in the examples are importable:

```js
import { CogIcon } from 'evergreen-ui'
```

Additionally, most IDEs will autocomplete based on the typedefs (like VS Code) what you can import from the package!

**Comment by akleiner2** [comment]
What @mshwery said! For the docs issue - we'll be sure to fix the docs asap. Great spot.
