### ISSUE TITLE
Plain CSS Stylesheet

### ISSUE THREAD

**Issue by virtualgraham** [segmentio/evergreen#1065]
In the case of a site that mixes react with plain HTML, for example when using `dangerouslySetInnerHTML` for a markdown blog using Gatsby, It would be great to have a plain style sheet to match the typography and other styles of the evergreen theme. Does such a style sheet already exist?

**Comment by akleiner2** [comment]
Not as far as I know (at least that we provide). CSS classname generation is non-deterministic in Evergreen, so it wouldn't be something that we would do ourselves. 

Going to close this out for now - but curious to hear / see if you (or someone else) ends up getting Evergreen styles into a plain CSS stylesheet. Would be awesome!
