### ISSUE TITLE
Controlled FilePicker component

### ISSUE THREAD

**Issue by MercuryVladaBelopolskaya** [segmentio/evergreen#1102]
Hi!

I am use react hook forms and I what to make controlled file picker component.
FilePicker don't have value property.
Do you have a way to make file picker controlled?

**Comment by buschco** [comment]
It would be very useful to include a `ref` prop or the event in the `onChange` callback. Right now the only way (that I am aware of) to clear the inputs value, is to use the `key` prop and change it to get a "fresh" state.

**Comment by brandongregoryscott** [comment]
Ah, yeah - we are forwarding the component ref, but it's to the `div` and not the underlying `input`:

https://github.com/segmentio/evergreen/blob/9e5b1a48c067988b96a992d7ec6cff9731755f7a/src/file-picker/src/FilePicker.js#L82-L84

We are actually working on an updated component with Drag & Drop functionality that should look better and be easier to use. I'll take this feedback into account when it's ready to bring in (providing the underlying `input` ref). 

FWIW, the native file input is pretty clunky and there's [only so much you _can_ do to reset it](https://stackoverflow.com/questions/42192346/how-to-reset-reactjs-file-input) (setting `event.target.value = null` or changing the `key` in React to force a re-render as you mentioned). If you need a quick fix for now, the `key` method is probably the easiest route: https://codesandbox.io/s/evergreen-issues-1102-reset-filepicker-state-with-key-bo49u?file=/src/App.tsx

**Comment by brandongregoryscott** [comment]
We just released the new `FileUploader` and accompanying `FileCard` components in [v6.9.0](https://github.com/segmentio/evergreen/releases/tag/v6.9.0)

Check out the documentation here: https://evergreen.segment.com/components/file-uploader

Let us know if you run into any issues with it! The API should be pretty flexible without needing the underlying input ref.
