### ISSUE TITLE
Add containerProps to Autocomplete  

### ISSUE THREAD

**Issue by dplain90** [segmentio/evergreen#1110]
Hi all,

In Autocomplete, there is no way to pass props to the outer container that Downshift sets `role=combobox` to on render. In the current implementation, it's just rendering a div w/ `100%` width. 

https://github.com/segmentio/evergreen/blob/e1050a724413b344f3d1412199a277bdc2243821/src/autocomplete/src/Autocomplete.js#L167

It would be nice to be able to modify the props for this container. Mostly so you can adjust the styles etc if needed. 

Let me know what you think. Happy to make a PR if ya'll think this makes sense

**Comment by jackcwu** [comment]
Me and @tcho0501 are on this

**Comment by akleiner2** [comment]
Yep! Makes sense to me - otherwise, each time you use `Autocomplete` you'd have to wrap in some kind of div that ends up with the size you want. Happy to take a PR for this!

**Comment by mshwery** [comment]
For context: https://github.com/segmentio/evergreen/pull/412

**Comment by mshwery** [comment]
A better option IMO would be to accept any ui-box props, split them with `splitBoxProps`, and apply the box props to this container.

**Comment by tcho0501** [comment]
That makes sense, so just to reconfirm: we should closely follow the outer-container used in combobox for the autocomplete?

**Comment by akleiner2** [comment]
Closing out due to inactivity - I think that either `containerProps` or `splitBoxProps` both work as possible solutions. Please feel free to re-open if time permits!
