### ISSUE TITLE
Add Accordion

### ISSUE THREAD

**Issue by sslgeorge** [segmentio/evergreen#1115]
I think a rich UI library like this needs an accordion.

**Comment by marianayap** [comment]
@sslgeorge Hello! can I work in this issue?

**Comment by sslgeorge** [comment]
> @sslgeorge Hello! Is this issue taken?

Not yet

**Comment by jackcwu** [comment]
Me and @tcho0501 are on this

**Comment by akleiner2** [comment]
Hey folks -- Evergreen is heavily influenced by our own internal component needs at Segment. We don't have plans to include an Accordion component yet, but when we do, we'll be happy to let y'all know. Going to close this out for now.
