### ISSUE TITLE
Add grid or flexbox to make it responsive 

### ISSUE THREAD

**Issue by MohsinAliSoomro** [segmentio/evergreen#1123]

**Comment by akleiner2** [comment]
You can use "styles as props" via any component in Evergreen - so if you choose to make something `display="grid"` or `display="flex"`, you can + should be able to do so. 

Check out https://github.com/segmentio/ui-box  (which is what most of Evergreen is built on top of) for examples of how to set these styles. Let us know if you have any other questions!
