### ISSUE TITLE
CornerDialog position with typescript

### ISSUE THREAD

**Issue by xuoutput** [segmentio/evergreen#1130]
![image](https://user-images.githubusercontent.com/16385443/103353256-59d38c80-4ae3-11eb-921a-075c3b420e7c.png)

**Comment by akleiner2** [comment]
Hey @xuoutput -- good spot, `position` is missing from the type declaration file.  Happy to accept a PR adding it!

**Comment by akleiner2** [comment]
Closing out due to activity - please re-open the PR as I think it's still valid to add.
