### ISSUE TITLE
extractStyles() for Shadow DOM

### ISSUE THREAD

**Issue by drummerjolev** [segmentio/evergreen#1133]
Hey all, 

I'm wondering if there is a way to extract all the styles I'm using through Evergreen components. I'd like to inject that CSS into a Shadow DOM. I tried using `extractStyles`:
```
const { css } = extractStyles();
render() {
    ...
    <style>{css}</style>
    ...
}
```
but that did not work, as the styles keep changing when events fire in the DOM.

Any help is much appreciated – thank you!

**Comment by akleiner2** [comment]
Do you mind posting a CodeSandbox with some minimal repro code? Would be super helpful to take a look!

**Comment by akleiner2** [comment]
Going to close this out for now - let us know if you are able to repro with a CSB link!
