### ISSUE TITLE
Introducing the color picker component

### ISSUE THREAD

**Issue by MrSnix** [segmentio/evergreen#1134]
**Introduction**
Hi, I'm Joseph, a first-time author here.  I have been using Evergreen for a while and currently, the framework does not provide a built-in ColorPicker. The `<input type="color" />` UI may vary on the different operating systems or browsers, so I build one from scratch without using any 3d-party library which could be used as a replacement for UX consistency and usability.

**Design**
> Smaller atoms and primitives are favored over bigger complex components.

As requested by the docs, I started building and dividing the `<ColorPicker />` into little components, and then I came up with the final implementation. This, briefly showcase what I basically did.

<img src="https://user-images.githubusercontent.com/20780192/103470122-4851e500-4d6e-11eb-806b-9eeb927af623.png" width="500px" height="auto"/>

I have three basic components that rely on `<canvas />` and they are the one shown
- `<ColorSpectrum />` (1st on picture)
- `<ColorPlane />` (2nd on picture)
- `<ColorSlider />` (3th on picture)

I wrapped around them a `<Pane />` so they could inherit all its properties and then using the atomic components, I came up with the final and real `<ColorPicker />`. It's obvious that if any user is not satisfied with the basic design he can use one of the modules to build one himself as he wishes.

**Result**
The `<ColorPicker />` has two modes: "Basic" and "Advanced".
On `Basic` mode, it keeps its style really minimal providing only the necessary (it's possible to hide inputs too, showing only the preview) meanwhile on `Advanced` it provides more precision on color selection when really needed by the user using the `<ColorPlane />`.

![Jan-03-2021 02-55-56](https://user-images.githubusercontent.com/20780192/103470176-4177a200-4d6f-11eb-9fff-ad8ef5071ab3.gif)

**P.S** Poor `<ColorSpectrum />` quality is due to .gif compression

**Summary**
There are still some minor tweaks to do and some enhancement I need to finish but if my proposal is approved I can raise a PR and share my work with its updates. Let me know!

**Comment by akleiner2** [comment]
Hey @MrSnix first of all -- this looks incredible! Thank you so much for taking the time to open up an issue and show the work in progress thus far. It definitely has the look + feel of an Evergreen component, and a lot of the core interactions I'd expect from a Color Picker component seem to be present. 

Unfortunately, given that Evergreen is an implementation of Segment's design system, and our products don't have a need for a `<ColorPicker  />` type component just yet, I'm a bit hesitant to take on the maintenance burden of this component living within Evergreen. 

I'd highly, highly encourage you to publish this as a component that can live alongside Evergreen, and that other folks can take advantage of. I'd be willing to do a callout in the README, so other folks can find these types of compositions for themselves relatively easily.

**Comment by MrSnix** [comment]
Hi @akleiner2, thanks for the time you spent on my request, :D
I understand your point and I'm okay with it, I'll let you know if I'll do something with this component.
There are a lot of alternatives on `npm` which can be more suitable and customizable than the one I did.
I built this one specifically for Evergreen and its UX.

Nevermind, I'm glad you have reached me out.
Thanks

**Comment by akleiner2** [comment]
Excited to see the code behind it @MrSnix please circle back if / when you do decide to publish or release it to open source :)
