### ISSUE TITLE
Mobile devices

### ISSUE THREAD

**Issue by Aanandgupta** [segmentio/evergreen#1144]
Should we do some modifications so that our website is more readable for mobile phone users?
Currently, we are just scaling according to the screen sizes it would be better if we would have a nav-bar at the top which on clicking displays no of options
![Screenshot (137)](https://user-images.githubusercontent.com/71023799/107557554-c6bc6500-6bff-11eb-90ef-d2c53507766f.png)
 and stack components for mobile devices

**Comment by akleiner2** [comment]
Hey @Aanandgupta we have some exciting changes to the doc site coming up in the next few weeks, and we'll definitely take into account responsiveness for the upcoming docs site!
