### ISSUE TITLE
Evergreen Link and Next Link

### ISSUE THREAD

**Issue by dikaio** [segmentio/evergreen#1148]
Hi Team. I was playing with Evergreen today and was curious how you are able to use both evergreen ui Link and Nextjs together. Using only evergreen ui's Link I lose the client side routing functionality that Nextjs provides. I couldn't find anything on via Google that covers this but I'm sure the solution is probably very simple I've just missed.

**Comment by mshwery** [comment]
Do you have some minimal sample code you can share that illustrates your issue? 

My assumption (without seeing anything) is that you need to rename one of the imports:
```
import { Link as EvergreenLink } from 'evergreen-ui'
import Link from 'next/link'

// usage
<Link href="/about" passHref>
  <EvergreenLink>About Us</EvergreenLink>
</Link>
```

More info: https://nextjs.org/docs/api-reference/next/link#if-the-child-is-a-function-component

PS. This type of question is the perfect thing to ask in [Discussions](https://github.com/segmentio/evergreen/discussions) in the future!

**Comment by dikaio** [comment]
Hi @mshwery this is exactly what I needed, ugh thank you so much, nesting the import like you did here isn't something that came to mind <you rock>.

[Discussions](https://github.com/segmentio/evergreen/discussions) see you there!
