### ISSUE TITLE
Can not align the icon in the search input

### ISSUE THREAD

**Issue by Abdalrzakalsouki** [segmentio/evergreen#1169]
Hello,
I have been using Evergreen in my project and since the framework is not responsive I had to use CSS breakpoints.
The problem was with the search input icons because I was able to align the search input width and height but can not
align the icon. Leaving with a broken icon outside the input
**Please, is there any way to align the icon probably or at less remove it**
Thank you

**Comment by akleiner2** [comment]
Do you have any external CSS affecting this (namely targeting `input[type="search"]`? Otherwise, this should be working as expected. Please update with a Codesandbox whenever you have time! In the meantime, I'm going to close this out for inactivity.
