### ISSUE TITLE
Clearly Display default theme Object in docs

### ISSUE THREAD

**Issue by wyhinton** [segmentio/evergreen#1171]
Hello,

I think it could be useuful for developers if the default definition for ```ThemeProvider```'s ```value``` was shown somewhere in the docs. Right now you have to dig through the source code for it. [Material UI does this](https://material-ui.com/customization/default-theme/). In order to write custom themes its very helpful to know what the theme object keys are.

**Comment by akleiner2** [comment]
We've started on this, but would love some more help in the coming weeks: https://evergreen.segment.com/introduction/theming. Going to close out for now!
