### ISSUE TITLE
Project still maintained?

### ISSUE THREAD

**Issue by mifi** [segmentio/evergreen#1172]
First thanks for the amazing UI library. The DX and design of this is just awesome and I use it all the time. I don't want to complain, and I appreciate that evergreen is already really good and may not need that much updates, but I can see that the last commit was in December 2020, and there are quite a few issues and PRs waiting. Like some obvious low hanging fruit like the bug #1142 and supporting React 17. So I'm wondering, is Segment still planning on working on this project, or if not, could it get some community collaborators, at least for fixing the obvious issues and keeping it stable? I'm happy to do some contribution if needed.

**Comment by Jupiterrr** [comment]
@akleiner2 and @kamebkj are working a lot on the [v6-docs branch](https://github.com/segmentio/evergreen/commits/v6-docs). I can't wait for the release. 🥳

**Comment by Jupiterrr** [comment]
@mifi [v6.0.0](https://github.com/segmentio/evergreen/releases/tag/v6.0.0) was released two days ago. The docs were updated as well http://evergreen.segment.com/.

**Comment by mifi** [comment]
Awesome! Would be cool if someone could cleanup issues/prs though

**Comment by akleiner2** [comment]
Hi! Sorry about the radio silence - we've been pretty heads down shipping v6 and fixing up any loose ends! We're always happy to accept PRs, so long as they roughly match what we're doing (or fix any bugs that we've introduced :P). We'll be more diligent about the PR / issue grooming process going forward <3 

On that note, going to close out this issue :P  - for all general discussion, head over to our GitHub Discussions and ask away!
