### ISSUE TITLE
SelectMenu closes on click when it shouldnt

### ISSUE THREAD

**Issue by psiho** [segmentio/evergreen#1200]
I upgraded my react 16.13.1 app to evergreeui6 and now my SelectMenu behaves weird. Menu closes:
- on click on the option (even if Multiselect)
- on click outside of options area but within the menu itself

I don't even know where to start debugging :) WIll try to create a code to reproduce it.

**Comment by thiagomdo1** [comment]
Same issue here.

**Comment by akleiner2** [comment]
Thanks for reporting - fix is here: https://github.com/segmentio/evergreen/pull/1199. Will cut a patch release today or tomorrow! Thank you for your patience.

**Comment by akleiner2** [comment]
Should be fixed in `6.0.1`!

**Comment by akleiner2** [comment]
Closing this out, but let me know if this is still an issue.
