### ISSUE TITLE
v6 - warnings with failed prop types for borderTop, borderBottom...

### ISSUE THREAD

**Issue by psiho** [segmentio/evergreen#1208]
My project after upgrade to v6 throws warnings:

```
Warning: Failed prop type: Invalid prop `borderBottom` of type `boolean` supplied to `Box`, expected `string`.
    in Box (created by ForwardRef(Pane))
    in ForwardRef(Pane)
    in ForwardRef(Pane) (created by ForwardRef(Card))
    in ForwardRef(Card)
    in ForwardRef(Card) (created by OfferEdit)
```

same thing for all 4 border types.

**Comment by akleiner2** [comment]
Interesting - I just tried to repro that here, but not seeing it: https://codesandbox.io/s/eloquent-johnson-597k9?file=/src/App.tsx

Are you looking in a dev environment? What does a minimal repro-able example look like?

**Comment by psiho** [comment]
Yes, dev environment. Ill try to setup an example. Will take me a day or two as I'm on a very tight schedule this week.

Basically I just updated evergreen to v6 and reported differences from v5 on my project in progress. 

Will get back to you soon.

**Comment by akleiner2** [comment]
All good - going to keep this open and hopefully see what you're seeing. 👍

**Comment by psiho** [comment]
Ok, iI found out where it is comming from. It's in this line and property `border={false}` causes it:

`<Card {...cardStyle} border={false} background="transparent" display="flex" justifyContent="space-between">`

`border={true}` does not cause it and works properly. I'm pretty sure I was not getting this in v5. I'm building a project in typescript and was relying on my editor to describe props. For `card` prop `border` I get: `(JSX attribute) PaneOwnProps.border?: string | boolean | undefined`

... so I guess either there's a problem with typings or in code. For now, it's easy to get around this by using border="0" instead.

**Comment by akleiner2** [comment]
So, the typings and the run-time behavior are actually correct, it's just a matter of how these props get generated that ends up pretty noisy. 

Under the hood, we use [`ui-box`](https://github.com/segmentio/ui-box/). You can see the prop types declarations are probably incorrect here: https://github.com/segmentio/ui-box/blob/master/src/enhancers/border-radius.ts#L6. Happy to accept a PR over there, but for now going to close this out as the actual behavior is as expected.
