### ISSUE TITLE
v6 Docs - SelectMenu multiselect - deselect example does not work

### ISSUE THREAD

**Issue by psiho** [segmentio/evergreen#1211]
Well, title says it all. Deselcting does not work in this example: 
https://evergreen.segment.com/components/select-menu#multiselect_with_deselect_example

**Comment by psiho** [comment]
I guess lines 33 and 51 should both be:
`setSelectedItems(selectedItems);`

**Comment by akleiner2** [comment]
You are absolutely right - good spot. Fix in #1213
