### ISSUE TITLE
The menu has no menu items

### ISSUE THREAD

**Issue by mifi** [segmentio/evergreen#1223]
I get this error if I use the `disabled` prop for `Menu.Item` and if all menu items in a `Menu.Group` are disabled. Can we remove this line of code?

https://github.com/segmentio/evergreen/blob/29f9c41ff15527dac0892330b8032ccd585b1412/src/menu/src/Menu.js#L29

Maybe instead return?
I can submit a pr if this is the correct solution

**Comment by akleiner2** [comment]
I'd be fine either removing that line, or just throwing that error in dev -- happy to accept a PR either way.

**Comment by dudhatdhavalm** [comment]
Is this issue still open or not?
if it is still open then I would like to do my first contribution.

**Comment by mifi** [comment]
Still an issue. Feel free to contribute :)

**Comment by brandongregoryscott** [comment]
Published with [v6.7.1](https://github.com/segmentio/evergreen/releases/tag/v6.7.1)
