### ISSUE TITLE
ListItem Icon overlays text (gets style .ub-lft_NaNpx)

### ISSUE THREAD

**Issue by psiho** [segmentio/evergreen#1224]
After moving ListItem to a child component, icon positions wrongly. Icon style somehow gets "left: NaNpx".

Modified example from your docs shows this: https://codesandbox.io/s/adoring-austin-m8kiz?file=/index.js

Cannot find a workaround for this. Any ideas?

**Comment by akleiner2** [comment]
Your `Item` component needs to be able to accept Evergreen props, since `UnorderedList` relies on cloning direct children and passing spacing into them. Trade you a sandbox here: https://codesandbox.io/s/peaceful-platform-qr7tf

**Comment by psiho** [comment]
Oh, thx! Solved. Wasn't so obvious. Maybe an example in docs could help.
