### ISSUE TITLE
Make links more visible on documentation pages

### ISSUE THREAD

**Issue by ghost** [segmentio/evergreen#1226]
A tiny issue, but annoying nonetheless. When reading a documentation page, links look like "ordinary" text making it quite difficult to refer to later. It would be nice to make them more visible with a different color or underline applied.

It seems that a link inherits its color from the CSS reset in `/docs/styles`, so I'm not sure if it's a bug :thinking: 

Is there a chance of changing this?

Thanks :)

**Comment by kamebkj** [comment]
Great callout. Fixed. Thanks!
