### ISSUE TITLE
Remove Max Width on Alert component

### ISSUE THREAD

**Issue by systemizer** [segmentio/evergreen#123]
I might be missing context on why maxWidth is set to 400px on Alert components. I ran into an issue where I needed to manually override this property to set the width properly. Do we need it set to 400px?

**Comment by jeroenransijn** [comment]
Max width is used as a default to make sure we don’t end up with Alerts that are spanning the complete page, but also adapt to containers potentially smaller than that. That being said, I see how this might be confusing. Can you give your use case so I understand the constraints you are dealing with?

**Comment by systemizer** [comment]
Sure. The page on which I'm showing the alert has a Card. The Card spans about half of the screen. When we want to notify the user about something, we want to align left and right borders of the Alert with the Card. Using Flexbox, we should get this for free, but since this element sets a max-width, it fails to do that

**Comment by Rowno** [comment]
Just FYI, TextInput doesn't have a max-width and spans the width of the page by default, so this behaviour is inconsistent across the components.

**Comment by jeroenransijn** [comment]
Let’s remove it!

**Comment by jeroenransijn** [comment]
This has been removed in #135
