### ISSUE TITLE
v5 Documentation

### ISSUE THREAD

**Issue by Pruxis** [segmentio/evergreen#1233]
Hey, we are still using the v5 styling evergreen and are wondering where we could find the component documenation
As the main website has been updated to the latest version but it's not clear where to find it from previous versions

Regards,

**Comment by MariusIorgaQuantarium** [comment]
You can download the v5.1.2 source code from [this link](https://github.com/segmentio/evergreen/releases/tag/v5.1.2)  and run the docs locally form the `docs` folder.

**Comment by WingmanImd** [comment]
You can download the source code  for v5.1.2 from [this link](https://github.com/segmentio/evergreen/releases/tag/v5.1.2) and run the docs locally from the `docs` folder.

**Comment by akleiner2** [comment]
Yeah, that's one way - for what it's worth component APIs also haven't changed too much between v5 and v6 (just visual styles...and even then, we've provided a way to get backwards-compatible styling via `classicTheme`). 

If you're mostly looking for component props APIs, then you should just be able to use the EG website as-is. Let me know if this doesn't work for your use cases though!
