### ISSUE TITLE
Warning in a custom button

### ISSUE THREAD

**Issue by msakal20** [segmentio/evergreen#1234]
Hello, I have a problem with custom button, when I create a new appearance, I have this warning, from it, I can see that the component button takes only 3 values ["default", "minimum", "main"], but appearance work.
![image](https://user-images.githubusercontent.com/84870471/122583968-79934880-d062-11eb-83b1-b0dfdf027f3f.png)
The same warning I see in documentation.
![image](https://user-images.githubusercontent.com/84870471/122584112-a182ac00-d062-11eb-8c21-c4ccc3515315.png)
 
Сan I fix this warning ?

**Comment by akleiner2** [comment]
Annswered over in https://github.com/segmentio/evergreen/discussions/1236
