### ISSUE TITLE
Add a Disabled Style for the Link Component

### ISSUE THREAD

**Issue by systemizer** [segmentio/evergreen#124]
The link component currently has a few styles (green, blue, default). We should also include a style for disabled. This would make it a muted color and would show the 'not-allowed' cursor when hovering

**Comment by jeroenransijn** [comment]
Hi Rob! Thanks for taking the time and creating an issue. I am curious as to what the use case is for a link to be disabled an have cursor not-allowed? It seems more so like the functionality of a button, and might be better suited for the button element.

**Comment by systemizer** [comment]
Good point. I'll try using a ghost button instead. Going to close this. thanks!
