### ISSUE TITLE
Select Menu deselect example. Select, deselect, then re-select takes 2 clicks.

### ISSUE THREAD

**Issue by dustincjensen** [segmentio/evergreen#1241]
https://evergreen.segment.com/components/select-menu#multiselect_with_deselect_example

Minor oddity with the Select Menu deselect.
- Open the menu
- select Apricot
- deselect Apricot
- select Apricot again (nothing happens)
- select Apricot again (now selected).

**Comment by mshwery** [comment]
Resolved by #1256
