### ISSUE TITLE
color property in Heading component not working properly 

### ISSUE THREAD

**Issue by zakiAzfar** [segmentio/evergreen#1242]
#### Color names are not working properly in Heading Component, but working fine when using color values or Text Component

```js
// NOT WORKING
<Heading size={600} color="Blue500">
  Lorem Ipsum
</Heading>
```

```html
// WORKING
<Heading size={600} color="#3366FF">
  Lorem Ipsum
</Heading>

<Text color="muted">
  Lorem Ipsum
</Text>
```

**Comment by akleiner2** [comment]
This is a byproduct of the way our props system works at the moment. A couple of things to get around it: 

```
const { colors } = useTheme()

<Heading size={600} color={colors.blue600} />
```

or -- feel free to make `color` a "theme"-able value for heading - we do this already for `Text` if you want to look for an example implementation. PRs welcome!

**Comment by darkknight20032001** [comment]
@zakiAzfar is this issue still open???

**Comment by zakiAzfar** [comment]
> @zakiAzfar is this issue still open???

Don't know, haven't used it since a very long time
