### ISSUE TITLE
Select Menu arrow key events

### ISSUE THREAD

**Issue by derekvelzy** [segmentio/evergreen#1245]
Link to docs: [Select Menu, Single Select Item](https://evergreen.segment.com/components/select-menu#single_selected_item)

Expected: 
Up & Down arrow keys should accurately select options above or below the currently selected item.

Actual: 
Unpredictable behavior with up & down navigation.

**Comment by mshwery** [comment]
Nice catch! I'm guessing this is potentially a bad merge, or perhaps a bad hooks implementation. cc @kamebkj @akleiner2

**Comment by mshwery** [comment]
Resolved by #1256

(give it a spin here https://deploy-preview-1256--evergreen-storybook.netlify.app/?path=/story/select-menu--selectmenu)
