### ISSUE TITLE
Upgrade @types/react dependency

### ISSUE THREAD

**Issue by zuhair-naqvi** [segmentio/evergreen#1291]
Any reason why "@types/react" is still set to "^16.9.5"? This will force developers to either add  `"skipLibCheck": true` to their ts config OR add a "resolutions" field in order to resolve "duplicate identifier" errors with typescript if the rest of their packages (in a monorepo) use React 17 types

**Comment by akleiner2** [comment]
Was an oversight as part of the React 17 upgrade -- PRs welcome! I'm also wondering if we even need to install `@types/react` alongside Evergreen, and instead push that responsibility to the consumers. 🤔

**Comment by zuhair-naqvi** [comment]
@akleiner2 cheers, PR issued

**Comment by brandongregoryscott** [comment]
In https://github.com/segmentio/evergreen/releases/tag/v7.1.0, we've removed this as a prod dependency. Feel free to open a new issue if you're still seeing discrepancies.
