### ISSUE TITLE
Invalid prop `intent` of value `info` supplied to `ForwardRef(IconButton)`

### ISSUE THREAD

**Issue by patrikmasiar** [segmentio/evergreen#1303]
## Description
I was about to use `toaster.notify()`. I just opened the console in the browser and I saw there is an error.
Error appears only with `notify()` function usage. Any other functions `success(), danger(), warning()` **are not** causing problems.

I was trying to find out, what is going on, but I could not see anything. Probably I was searching bad.

Could you please tell me how to resolve the issue?

#### Screenshor from thr browser console
![Snímka obrazovky 2021-08-13 o 7 54 48](https://user-images.githubusercontent.com/8200096/129311805-b546f0a6-745d-44f4-9155-4b29a502d7a7.png)

**Comment by amolerca** [comment]
I'm having the same problem as the one described by @patrikmasiar . This didn't happen to me with version 5.1.2 though, so perhaps it's a bug on the latest version?

**Comment by patrikmasiar** [comment]
@amolerca I am using `6.4.0` version and it is happening there as well. I tried to check the source code of the package but I did not find anything related to this.

**Comment by amolerca** [comment]
@patrikmasiar yes, this started happening to me when I upgraded to `6.4.0`, not before. That's why I believe it must be some newly introduced bug.

**Comment by hyperloo** [comment]
hi @patrikmasiar, seems interesting and a good starting point for a beginner. Can I work on this work?

**Comment by esinanturan** [comment]
![image](https://user-images.githubusercontent.com/7051983/132120582-79c6484b-eb98-4745-a379-c50bfcbd11fa.png)
Same happens when we make a custom appearance theme

**Comment by hyperloo** [comment]
I have rectified this warning. Already made a PR.

**Comment by brandongregoryscott** [comment]
The intent propType warning should be resolved as of [v6.5.2](https://github.com/segmentio/evergreen/releases/tag/v6.5.2) by #1341 and the button propType warning should be resolved in [v6.6.3](https://github.com/segmentio/evergreen/releases/tag/v6.6.3) with #1287. Feel free to open a new issue if you find this is still happening. Thanks 👍
