### ISSUE TITLE
Invalid SelectFields are not bordered red

### ISSUE THREAD

**Issue by seth-wat** [segmentio/evergreen#1316]
This is visible in the documentation of `SelectField`:

https://evergreen.segment.com/components/select#invalid_field

comparatively `TextInputField`:

https://evergreen.segment.com/components/text-input#invalid_field

**Comment by mshwery** [comment]
Good catch. Probably need to update the default theme to include invalid border styles. // cc @kamebkj @zkuzmic

**Comment by brandongregoryscott** [comment]
Published with [v6.6.2](https://github.com/segmentio/evergreen/releases/tag/v6.6.2)
