### ISSUE TITLE
Dialog can not have hasClose when hasHeader is false

### ISSUE THREAD

**Issue by kud** [segmentio/evergreen#1318]
Hello,

Apparently you can not have the close cross when you don't display the header. 

However, this is I'd like to have. 😬

**Comment by pavolmarc** [comment]
Hello, is this still relevant? I would like to work on this issue.

**Comment by kud** [comment]
It is. :)

**Comment by pavolmarc** [comment]
@brandongregoryscott hello, can you assign me to this issue, if that's not a problem?

**Comment by akleiner2** [comment]
Hi both - 

This is intentionally designed - if you pass in `hasHeader={false}`, the open question becomes where would the cross icon sit? The `header` argument takes in `close` as a render prop, so you can implement your alternative header accordingly. 

Let me know if this makes sense! Going to close out this issue in the meantime.

**Comment by kud** [comment]
Ha!

This is exactly why I opened this issue. I didn't want to handle myself the close button when the header isn't displayed. :)
