### ISSUE TITLE
Combobox position issue

### ISSUE THREAD

**Issue by Suroor-Ahmmad** [segmentio/evergreen#1354]
**Issue:**
Position issue on combobox in latest version (6.5.2). When I checked the CSS, `top:0; left:0` which should have been inherited value.

**Last working version: 6.0.1**

**Steps to recreate:**
Just use combobox in the code, or check below storybook
[Evergreen Storybook](https://deploy-preview-1353--evergreen-storybook.netlify.app/?path=/story/combobox--combobox)

**Note:**
Noticed same issue in evergreen-ui storybook too.
[Evergreen Storybook](https://deploy-preview-1353--evergreen-storybook.netlify.app/?path=/story/combobox--combobox)

**Comment by brandongregoryscott** [comment]
Thanks for flagging this. Looks like this behavior started in 6.5.2 (probably with https://github.com/segmentio/evergreen/pull/1346), but it should be working in 6.5.1. Check out these sandboxes:

6.5.2 (top-left position)
https://codesandbox.io/s/evergreen-issues-1354-evergreen-6-5-2-ewvie?file=/src/App.js

6.5.1 (correct position):
https://codesandbox.io/s/evergreen-issues-1354-evergreen-6-5-1-qeq11?file=/src/App.js

We'll work on a fix but feel free to open up a PR in the meantime. The issue originally reported (#1329) may be related to the `Positioner` recomputing too often, not the `Popover` or `Autocomplete` components directly.

**Comment by brandongregoryscott** [comment]
This should be resolved in [6.6.1](https://github.com/segmentio/evergreen/releases/tag/v6.6.1) (see forked [Codesandbox example](https://codesandbox.io/s/evergreen-issues-1354-evergreen-6-6-1-j1bvb?file=/src/App.js). Let us know if you see any other issues!

**Comment by Suroor-Ahmmad** [comment]
Thank you. It's resolved. I couldn't PR in time.
