### ISSUE TITLE
Empty divs in evergree-portal-container using Tooltip

### ISSUE THREAD

**Issue by vojtatom** [segmentio/evergreen#1365]
Hello, I think I have encountered similar issue to this one https://github.com/segmentio/evergreen/issues/329 using the `Tooltip` component. 

I'm using version 6.6.1

React:
```
<Tooltip content="Layers" >
    <IconButton icon={LayersIcon} appearance="minimal" onClick={() => toggleMenu(Menu.Layers)} />
</Tooltip>
```

Looks like tooltip creates one extra div on hover, see:
Before hover:

![before](https://user-images.githubusercontent.com/23740163/142659859-16f202aa-8902-49a6-b166-7d95f22af666.png)

On hover:

![hover](https://user-images.githubusercontent.com/23740163/142659896-be69e5d5-2b90-4a1d-bd19-b7963f968609.png)

After mouse leave:

![after](https://user-images.githubusercontent.com/23740163/142659950-e4ddced7-3ee1-4a48-b23a-b630b651d563.png)

I suppose https://github.com/segmentio/evergreen/pull/330 did not fix the problem or am I missing something? 
Thank you for such a great library guys. 😊

**Comment by brandongregoryscott** [comment]
This should be resolved [v6.13.1](https://github.com/segmentio/evergreen/releases/tag/v6.13.1)
