### ISSUE TITLE
Table border styling issues

### ISSUE THREAD

**Issue by brandongregoryscott** [segmentio/evergreen#1375]
There are some minor styling issues with the base `Table` styles, which can be observed on the documentation site (may need to Zoom in to see them): https://evergreen.segment.com/components/table

- Inner content of `Table.Head` is missing `borderTopLeftRadius` and `borderTopRightRadius` style to match its outer container, which causes a sharp edge to render over the rounded border
![image](https://user-images.githubusercontent.com/11774799/144692205-ed36c906-647c-4525-af99-27d3f86b14f2.png)

- Last `Table.Row` is missing `borderBottomLeftRadius` and `borderBottomRightRadius` style to match its outer container, which causes a sharp edge to render over the rounded border
![image](https://user-images.githubusercontent.com/11774799/144692285-1cbf1714-6f89-4bff-9409-51b973b57f98.png)

- Last `Table.Row` has a `borderBottom` style which is overlapping with the bottom border of the outer container causing a thicker border
![image](https://user-images.githubusercontent.com/11774799/144692326-543d8b0f-dc05-4da0-b1a9-ce06dbc9afe2.png)

**Comment by Gulshanaggarwal** [comment]
@brandongregoryscott  can I start working on this issue?

**Comment by vikasazad** [comment]
Hi @brandongregoryscott I would like to contribute to this issue but as i am beginner in opensource contribution. I am not able to start the project in my local machine.
1- I forked it.
2- Run npm install
But as i looked in package.json file the "start" is missing in the scripts and i am not able to resolve this issue.
Please help me out.

**Comment by brandongregoryscott** [comment]
> @brandongregoryscott can I start working on this issue?

@Gulshanaggarwal Of course - feel free to open up a PR!

@vikasazad Please refer to step 2 in the contributing section: https://github.com/segmentio/evergreen/#-step-2-get-storybook-up-and-running

While you can use `npm`, we have set up the project to prefer `yarn`. The command for running a local development server would be `yarn dev` or `npm run dev`.

**Comment by Gulshanaggarwal** [comment]
@vikasazad sorry to say, but I'm already working on the above issue.

**Comment by Gulshanaggarwal** [comment]
@brandongregoryscott  If I apply borderBottomLeftRadius prop inside table.row then it causes the rounded border to all elements, see the  below image-
![Screenshot (241)](https://user-images.githubusercontent.com/58553401/144736748-808641c2-66fd-4c63-a7e2-7ae155e15823.png)


Can you help little bit more?

**Comment by vikasazad** [comment]
@Gulshanaggarwal ok no problem at all
