### ISSUE TITLE
SelectMenu popover at the bad position

### ISSUE THREAD

**Issue by leosheecool** [segmentio/evergreen#1377]
Hello there,

I submit this issue because on a project I need to use the SelectMenu component and when I click on the button to open the popover it does not take the position that I pass in props.
(I used the documentation code sample)

![image](https://user-images.githubusercontent.com/44168618/145191701-517bf4ab-0d01-414e-8979-43d558ebbbcb.png)

Can you help me to resolve that issue please ?

**Comment by brandongregoryscott** [comment]
Hi @leosheecool - what version of Evergreen are you using? I believe this bug was introduced in [v6.5.2](https://github.com/segmentio/evergreen/releases/tag/v6.5.2) and resolved in [v6.6.1](https://github.com/segmentio/evergreen/releases/tag/v6.6.1). Try upgrading to the latest version and let me know if this issue is still present.

**Comment by leosheecool** [comment]
Hi @brandongregoryscott
I have the latest version the v6.6.2 so that's why it's weird

**Comment by brandongregoryscott** [comment]
My apologies - I misread the issue and I see that you are manually trying to set the `position` prop, which isn't exactly the same issue that was introduced in v6.5.2.

Would you mind providing a code sample, or ideally, a sandbox to reproduce the issue? I spun up a demo sandbox with a simple `SelectMenu` that changes its position based on what value is selected, and I'm not seeing the same issue: https://codesandbox.io/s/evergreen-issues-1377-5ne1f

Note that the `Positioner` handles this heavy lifting and it can't always respect the requested position if there's too little viewport space to render the component. You can test that by reducing the amount of bottom margin on the `Paragraph` in the demo.
