### ISSUE TITLE
Swap faker w/ community maintained @faker-js/faker

### ISSUE THREAD

**Issue by brandongregoryscott** [segmentio/evergreen#1393]
Looks like the original repo/package for `faker` (https://github.com/marak/Faker.js/) has been nuked by its owner. An official fork has been spawned by the community at https://github.com/faker-js/faker. We should swap our dependency since the original is no longer going to be maintained (and it looks like the most recent publish is just an empty package).

**Comment by codeNitesh** [comment]
Hey @brandongregoryscott , I am very new to the open source community and wants to contribute to it. Can you please assign this issue to me? I have good knowledge of technologies used in this project.
Please help me to start :)
Thanks.
