### ISSUE TITLE
A problem was found in the comboBox.

### ISSUE THREAD

**Issue by jj2084jj** [segmentio/evergreen#1445]
If you scroll while the selection box list is exposed, the list is not fixed under the selection box.
The list box item moves along the scroll.
![image](https://user-images.githubusercontent.com/78161565/163755620-7e933032-71af-4bb7-9342-b31ebbcb06ba.png)

**Comment by jj2084jj** [comment]
![image](https://user-images.githubusercontent.com/78161565/163756015-8f3bda1e-adca-43e7-956f-828d593c5e63.png)

In addition, the same problem occurs in the Autocomplete - Results with an external trigger part.

**Comment by brandongregoryscott** [comment]
This was actually fixed in [v6.9.5](https://github.com/segmentio/evergreen/releases/tag/v6.9.5) but the documentation site hasn't been updated yet. I'll bump it in a quick PR!
