### ISSUE TITLE
Extract localizable strings so they can be customized

### ISSUE THREAD

**Issue by evantrimboli** [segmentio/evergreen#1459]
As an example, in the file picker control, the following strings are hard coded:

```
<Text color={disabled ? colors.gray500 : colors.blue400}>Browse </Text>
const orDragCopy = `or drag ${maxFiles === 1 ? 'a file' : 'files'} here`
```

It would be good if both were extracted to props:
- Browse would be a single string prop.
- The data for `onDragCopy` would be a function that would take the count and return a string.

The result would look something like this:
```
<FileUploader
  browseText={t('browse')}
  dragText={(count) => t('fileCount', { count })}
/>
```

The same should apply to other strings.

**Comment by brandongregoryscott** [comment]
I don't think it would be a huge lift (aside from this internal copy, I feel like most of the components are controlled), but I'd want to sit down and audit existing areas with internal/hard-coded copy before going full steam ahead on it. 

We haven't really prioritized i18ning our own app, which would require a much larger lift than just tweaking the Evergreen versions.
