### ISSUE TITLE
Pressing `esc` while focused on `TagInput` component throws error

### ISSUE THREAD

**Issue by brandongregoryscott** [segmentio/evergreen#1472]
Steps to reproduce:

1. Click or tab into an enabled `TagInput` component, such as the ones on the doc site https://evergreen.segment.com/components/tag-input
1. Press the `esc` key, and you should get the following runtime error:
`TypeError: Cannot read properties of null (reading 'split')`

![image](https://user-images.githubusercontent.com/11774799/169078068-b6b4f440-720a-4e36-b8a9-c959ae8a7b39.png)

At a first glance, it seems like pressing `esc` is setting the internal `inputValue` (which is expected to be a `string`) to `null`, which breaks the string-splitting behavior for generating the tag list.

**Comment by pandurijal** [comment]
what is the expected behavior for this case? just simply don't throw an error when the user clicks `ESC` or?

**Comment by pandurijal** [comment]
I believe I already found the workaround for this. Can you please assign this task to me?

**Comment by brandongregoryscott** [comment]
@pandurijal I think the esc should basically be swallowed, the same behavior as our standard `TextInput` or `Textarea` components

**Comment by pandurijal** [comment]
sure @brandongregoryscott I already opened a PR for this issue
