### ISSUE TITLE
`FormField`'s label property is required in JS but not in TS

### ISSUE THREAD

**Issue by harish-prakash** [segmentio/evergreen#1485]
The **`FormField`** component marks the `label` property as **required**

https://github.com/segmentio/evergreen/blob/d77c65342023d468b05b6fc49f345996a8c2a3d9/src/form-field/src/FormField.js#L43-L48

However, the typescript definition of **`FormFieldOwnProps`** marks it as **optional**

https://github.com/segmentio/evergreen/blob/44fe319c8cd05e4827945085c549049e01b443f4/index.d.ts#L1551-L1556

This causes runtime checks (e.g. JEST testing library) to encounter a `PropType` validation error.

```
console.error
    Warning: Failed prop type: The prop `label` is marked as required in `ForwardRef(FormField)`, but its value is `undefined`.
```

**Comment by brandongregoryscott** [comment]
Definitely an annoying discrepancy. It should be as simple as dropping the `isRequired` in the PropType - a PR is welcome!

**Comment by harish-prakash** [comment]
You've got it 😊
* #1486
