### ISSUE TITLE
React 18 warning

### ISSUE THREAD

**Issue by vko-online** [segmentio/evergreen#1491]
```Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot```

Toaster.js

**Comment by brandongregoryscott** [comment]
We'll be stuck with this error until we can drop support for React v16.8 - v17. See https://github.com/segmentio/evergreen/issues/1453#issuecomment-1106751399
