### ISSUE TITLE
Autocomplete: `allowOtherValues` not working?

### ISSUE THREAD

**Issue by egg-juxt** [segmentio/evergreen#1496]
Hi, this doesn't seem to be correct behavior: I'm using Autocomplete with property `allowOtherValues` enabled. When I select an item from the Autocomplete menu, the input value does not get updated.

Reproduction steps:
Navigate to https://evergreen.segment.com/components/autocomplete#default_example
Click on "Open in CodeSandbox".
Check that the Autocomplete component is working correctly.
Edit sample code to add property `allowOtherValues` to the Autocomplete element.
Refresh the "Browser" frame in CodeSandbox.
Select an item in Autocomplete and verify that it is not updating the value of the input element.

**Comment by brandongregoryscott** [comment]
Hmm, yeah, it looks like you're right. It looks like it _does_ select the value (typing in 'a', selecting Apple, backspacing, and then typing 'a' again shows the Apple option selected) but it doesn't seem to be properly updating the input field. Not sure when/if this ever worked, but going as far back as 6.4.0 it is still showing this behavior.

**Comment by brandongregoryscott** [comment]
This should be resolved in https://github.com/segmentio/evergreen/releases/tag/v6.10.4
