### ISSUE TITLE
`<Tooltip />` doesn't hide on mouse leave on disabled buttons

### ISSUE THREAD

**Issue by taochu** [segmentio/evergreen#1498]
When using `<Tooltip />` on a disabled button, as shown in the code sandbox below, the tooltip shows up on hover but doesn't go away when the mouse leaves the element.

This is happening on Chrome & Safari. Didn't test Edge. Firefox works fine.

[Code Sanbox](https://codesandbox.io/s/evergreen-tooltip-on-disabled-element-issue-kdhwnt)

**Comment by brandongregoryscott** [comment]
Is there a good reason to use a standard HTML button instead of our `<Button />` component as the target? It seems to work on our disabled Button component.

**Comment by taochu** [comment]
@brandongregoryscott 

Sorry for the very late reply. I remember back then the `<Button />` didn't work either so I was playing around w/ the native HTML button. Seems to work well now.

Thanks!
