### ISSUE TITLE
Component Request (or Offer): Responsive Icon Button

### ISSUE THREAD

**Issue by ianpaschal** [segmentio/evergreen#1499]
Hello,

I'm working on a project using Evergreen (and very much enjoying it, so: thank you). One thing I really need though is a `ResponsiveButton` which can be toggled between an `IconButton` and a `Button`. The rationale here is that on things like a collapsible sidebar or horizontal toolbar, real estate can become an issue on smaller screens and mobile and this button would allow these features to gracefully shrink.

I have this for the time being for prototyping purposes:

```ts
{isMobile ? (
  <Button
    paddingX={minorScale(4)} // Mimics 40px button with 16px icon (with icon's marginLeft = -4px)
    iconBefore={FilterIcon}
    size="large"
    appearance="minimal"
  >
    Filter...
  </Button>
) : (
  <Tooltip content="Filter...">
    <IconButton icon={FilterIcon} size="large" appearance="minimal" />
  </Tooltip>
)}
```

But what I want is:

```ts
<ResponsiveButton
  icon={FilterIcon}
  size="large"
  appearance="minimal"
  label="Filter...
  expanded={!isMobile}
/>
```

Although it could be as simple as packaging my crude version as its own component, there are some inconsistencies which would be nice to address like icon color differing between the two, and some spacing stuff. It could be nice to add some animation too to make it a little bit more polished looking instead of having some DOM nodes just blink in and out of existence.

Which gets us to the big question: **Does this fit within the Evergreen design system? If so, I'll do this properly and fork Evergreen and get easy access to all the style and theme utils. If not, I'll still build it, but within my project and probably more specifically tailored to its needs.**

What say you, maintainers?

**Comment by brandongregoryscott** [comment]
Hey @ianpaschal! Thanks for using Evergreen, happy to hear it's working well for you. :tada:

While we appreciate the offer, I don't think this is something we're interested in adding to the API at this time. Evergreen is certainly not responsive and it hasn't been a priority for our app, which largely drives decisions on major design changes and implementation. 

Adding one responsive variant of a component but not implementing a system-wide solution will lead to fragmentation and likely an influx of requests for responsive variants of other popular components. For now, I'd recommend rolling your own versions as needed since it isn't on our roadmap for the foreseeable future.

See the small snippet in our doc site here: https://evergreen.segment.com/foundations/layers#responsive_layouts, as well as a related discussion: https://github.com/segmentio/evergreen/discussions/1270

**Comment by ianpaschal** [comment]
Thanks for the quick reply! That's OK, I totally understand. And that's why I ask rather than just diving into the whole fork and PR process assuming it would be appreciated, haha.

If you (and the Evergreen folks) change your mind, let me know. Once this project is... not a massive WIP mess filled with crude glued-together bits like above ^^, I'd be happy to share it with y'all. Maybe you find some of the approaches work pretty well within the system. Who knows...

Out of curiosity, I haven't looked into it closer than I did this morning, but are some of the internally used hooks for theme variables and such accessible outside the module akin to MUI's `useTheme()`? Part of what I like about Evergreen is how rigid the sizing and styling of components is––makes it easy to create stuff that clearly fits in––but being able to tap into the theme would be very helpful.

**Comment by brandongregoryscott** [comment]
> Out of curiosity, I haven't looked into it closer than I did this morning, but are some of the internally used hooks for theme variables and such accessible outside the module akin to MUI's `useTheme()`? Part of what I like about Evergreen is how rigid the sizing and styling of components is––makes it easy to create stuff that clearly fits in––but being able to tap into the theme would be very helpful.

We do have a `useTheme` hook which can be used to access colors and other theme tokens. If you're adding or changing values from the default theme, you'll want to make sure you wrap your component tree in the `ThemeProvider` with your updated theme object as shown in the examples on that page.

**Comment by ianpaschal** [comment]
Makes sense! Sorry, I actually haven't really looked at that page past "Getting Started." Since then I've just been bouncing around between "Foundations" and "Components" for the last few days.

I don't know your policy for how aggressively you clean up the issue count, so I'll leave the decision to close this or not to you!

Cheers and thanks for your help!
