### ISSUE TITLE
Form fields inconsistent styles

### ISSUE THREAD

**Issue by ahsan-sabir** [segmentio/evergreen#1508]
TextInputField and SelectField have inconsistent border and box-shadow styles. There could be other inconsistencies as well.
On a side note it would be nice to have placeholder prop for SelectField as well.

<br/>

TextInputField             |  SelectField
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/56548120/182640923-a857a0a1-21db-4552-99c3-8b2b6c977c55.png)  |  ![](https://user-images.githubusercontent.com/56548120/182640942-2503c697-4477-4963-a4ea-0f41b20b4009.png)
![](https://user-images.githubusercontent.com/56548120/182640946-cd274382-37ef-4962-832d-df217b660106.png)  |  ![](https://user-images.githubusercontent.com/56548120/182640948-f0448193-b5c8-4c33-8ebb-0986caa16d1b.png)

<br/>

Same thing noticed between Combobox input and menu button

<br/>

![Screen Shot 2022-08-05 at 7 41 24 PM](https://user-images.githubusercontent.com/28040841/183101143-0f1237c5-ea6f-47d5-b13f-e7934a198bd7.png)
![Screen Shot 2022-08-05 at 7 42 06 PM](https://user-images.githubusercontent.com/28040841/183101160-745ea27a-1b65-498f-8feb-a17aeed9891e.png) ![Screen Shot 2022-08-05 at 7 42 25 PM](https://user-images.githubusercontent.com/28040841/183101166-0ef3e89c-8a57-4000-9a03-f359b2758395.png)

**Comment by krshnknsr21** [comment]
Hey can I take up this issue?

**Comment by brandongregoryscott** [comment]
@krshnknsr21 Sure! PRs are always welcome. Double check our public Figma library for reference: https://www.figma.com/@segment

**Comment by TheLazron** [comment]
Hey, I wish to take up this issue, but I fear the figma file is still missing. So if you could provide me with that
Thanks!

**Comment by brandongregoryscott** [comment]
Woops! Sorry, I meant to link out the re-uploaded version on the Twilio Figma: https://www.figma.com/@twilio

Let me know if you're still having issues finding the right styles in there, I haven't used it in a minute.

**Comment by TheLazron** [comment]
Hey I could find any defined styles except a banner image in the figma file, so if you could look into it

Besides that I was working on this other thing that was asked for i.e. a placeholder for the selectField. I could only think of implementing it using the "default hidden" option. Should it be fine?

**Comment by iharshspatel** [comment]
Hey, can I work on this issue? If no one has started working on it.
