### ISSUE TITLE
ClassicTheme not overwriting certain defualtTheme component styles in V6

### ISSUE THREAD

**Issue by AnishaTalati** [segmentio/evergreen#1511]
Hi,

My company uses your UI theme for their app and recently wanted to update from v5 to v6 in order to use certain props such as autocompleteItems in tagInputs, but keep the rest of the styling the same as in v5. I have updated and specified the classicTheme in the ThemeProvider component but am coming across some issues where even though most of the app is kept to the classicTheme, certain components such as toaster and any menu with a dropdown is staying as the default theme styling even when I specify classicTheme. Is this an issue or am I going about updating the UI wrong. 

I've attached the images of the previous UI and the new UI differences.
<img width="438" alt="Screenshot 2022-08-11 at 14 57 23" src="https://user-images.githubusercontent.com/83216551/184152248-45133c64-541b-4209-bd96-323e0f487ef1.png">
<img width="402" alt="Screenshot 2022-08-11 at 14 42 45" src="https://user-images.githubusercontent.com/83216551/184152274-ced574b5-27c8-4855-93e5-772a62ec3c6a.png">
<img width="287" alt="Screenshot 2022-08-11 at 14 48 03" src="https://user-images.githubusercontent.com/83216551/184152297-9dc5a6d4-4321-4a00-b19a-b5234c352e67.png">
<img width="298" alt="Screenshot 2022-08-11 at 14 42 37" src="https://user-images.githubusercontent.com/83216551/184152330-cb33c3c2-2503-4042-b1b8-37abe46aad72.png">

Any help would be appreciated, thanks.

**Comment by brandongregoryscott** [comment]
Hi @AnishaTalati,

It's possible that these components internally changed when we upgraded to v6 and released the new default theme, and they don't respect the classic theme tokens. While we aren't prescribing that you move off of the classic theme, we aren't necessarily adding classic theme backwards compatibility for updated or new components, since we have moved off of it entirely in our own applications. 

These two cases seem like an oversight, so we'd be happy to accept any PRs that re-introduce the classic theme where it was previously respected.

**Comment by JayYoungman** [comment]
@brandongregoryscott 

Thanks for the reply, we decided to manually restyle the toaster based on the classicTheme in our global css to solve this one. 

Would be happy to create a PR although it might not be something your interested in? 

Thanks

**Comment by brandongregoryscott** [comment]
If you've wired it up differently, no worries. We aren't actively adding classic theme backfills for new components or when we change existing components, but this seems like a case that was just originally missed in the V6 release, so I'd be OK with fixing support for it - it looks a lot like the Alert component that _does_ have classic styling support.

**Comment by brandongregoryscott** [comment]
Going to close this out as we're removing the `classicTheme` entirely in v7.
