### ISSUE TITLE
Portal breaks the nextjs hydration.

### ISSUE THREAD

**Issue by oxala** [segmentio/evergreen#1512]
Hey,

Recently found your library and was using in one of the projects. Good stuff and thank you for your work!

But is seems like there is an issue with the portal hoc you that you have.
For example, having an `<Overlay isShown={true}>Test</Overlay>` anywhere on the page will result in a failed hydration. 

<img width="702" alt="image" src="https://user-images.githubusercontent.com/1775318/184792274-ad0f31e7-a7e8-4050-a8f3-3aeb667f5e72.png">

I've put a tiny project to reproduce the issue here: https://github.com/oxala/next-evergreen-ssr-issue

**Comment by brandongregoryscott** [comment]
This should be resolved in https://github.com/segmentio/evergreen/releases/tag/v6.10.4
