### ISSUE TITLE
Issue with some Sandboxes

### ISSUE THREAD

**Issue by ahsan-sabir** [segmentio/evergreen#1515]
### [Custom menu items](https://evergreen.segment.com/components/menu#custom_menu_items)

Menu items showing browser default styles

Expected             |  [Sandbox](https://codesandbox.io/s/hzefzj)
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/28040841/185421278-9b02dfdb-9299-4f42-ae70-fae9b273a970.png)  |  ![](https://user-images.githubusercontent.com/28040841/185421293-1a87ae7c-6864-4903-bfe0-929ef1ef4140.png)

<br/>

### [Complete table example](https://evergreen.segment.com/components/table#complete_table_example)

ReferenceError in [Sandbox](https://codesandbox.io/s/i307cr)

**Comment by brandongregoryscott** [comment]
Thanks for flagging these @ahsan-sabir. I think the first one is actually an unintentional side effect of some global styles on the doc site. Those `ul`/`li` elements _should_ be unstyled the way it is currently written. However, I think that defeats the purpose of the example - I'll rework it to be a little more intuitive.
