### ISSUE TITLE
Upgrade core-js version

### ISSUE THREAD

**Issue by avin-kavish** [segmentio/evergreen#1519]
Got this warning,

> warning evergreen-ui > glamor > fbjs > core-js@1.2.7: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

Although it's through fbjs, maybe upgrading the glamor version will fix it.

**Comment by brandongregoryscott** [comment]
Duplicates #1146, #1304.

We ultimately need to move off of glamor.
