### ISSUE TITLE
Component Request: Card Component

### ISSUE THREAD

**Issue by JayKania** [segmentio/evergreen#1523]
I guess can make a component in which we would have the following props:

1. Image
2. Title
3. Subtitle
4. Description
5. Card Actions

**Comment by brandongregoryscott** [comment]
Hey @JayKania - while we do have a Card component, it is a really primitive component (essentially a `Pane` with a border radius), but it does allow for very flexible styling using css props.

We haven't found enough use cases for an opinionated component like you're describing, so I would recommend composing your own version with components like [`Pane`, `Card`](https://evergreen.segment.com/foundations/layers), [`Image`](https://github.com/segmentio/evergreen/blob/80f4f65714a02cdca69f6f4ac5663e38db111ec7/index.d.ts#L1675), [`Heading`, `Paragraph`, `Text`](https://evergreen.segment.com/foundations/typography), and [`Button`](https://evergreen.segment.com/components/buttons).
