### ISSUE TITLE
core-js is no longer maintained and not recommended for usage due to the number of issues?

### ISSUE THREAD

**Issue by lancejpollard** [segmentio/evergreen#1533]
Getting this on a fresh installation of `yarn add evergreen-ui` in a Next.js project:

> warning evergreen-ui > glamor > fbjs > core-js@1.2.7: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

Any ideas? Is this something I can fix on my own, or that should otherwise be fixed?

Excited to try Evergreen out for the first time after spending lots of time in other React UI frameworks (like antd)!

**Comment by lancejpollard** [comment]
Looks like it has already been reported, sorry! https://github.com/segmentio/evergreen/issues/1519

Any thoughts/statements on when it will be fixed?

**Comment by brandongregoryscott** [comment]
>Any thoughts/statements on when it will be fixed?

Unfortunately not 😞 Swapping glamor with another css solution like emotion will take quite a bit of effort + testing, which we don't really have time for at the moment.
