### ISSUE TITLE
security: v6.13.1 dependency contains vulnerable `node-fetch` version

### ISSUE THREAD

**Issue by yeganathan18** [segmentio/evergreen#1552]
I tried fixing by downgrading the `evergreen-ui` as well as `node-fetch` but still there is no change reflecting.

<img width="886" alt="Screenshot 2022-11-23 at 10 46 12 PM" src="https://user-images.githubusercontent.com/63534555/203608787-448d8dc2-345e-4bed-96e9-2c82e8192cea.png">

Can someone from the team suggest me a fix for this security bug?

**Comment by brandongregoryscott** [comment]
Please see #1304
