### ISSUE TITLE
How can I change Overlay color?

### ISSUE THREAD

**Issue by Piero87** [segmentio/evergreen#1553]
Hello, 
I have tried to do this:

  const theme = mergeTheme(defaultTheme, {
    components: {
      Overlay: {
        baseStyle: {
          backgroundColor: 'rgba(0, 0, 0, 0.5)'
        }
      }
    },
  })

but the Overlay components seems not present, anyone can help me to change the background color? 

thanks

**Comment by brandongregoryscott** [comment]
Hey @Piero87, the `Overlay` component doesn't have a full object under `theme.components`, but its color is overridable via `theme.colors.overlay`, for example:

```tsx
const theme = mergeTheme(defaultTheme, {
  colors: {
    overlay: "indianred"
  }
});
```

**Comment by Piero87** [comment]
@brandongregoryscott thank you!!!
