### ISSUE TITLE
Popover disappears when rendered and received a single scroll event

### ISSUE THREAD

**Issue by dengribar** [segmentio/evergreen#1556]
👋 After **6.13.1** update, one of our automated integration tests started failing in the following scenario:

`Popover` shows up at the same moment when scrolling takes place which results in the `Popover` becoming invisible. After looking into this issue, I've found the following:
* we subscribe on `"scroll"` event [here](https://github.com/segmentio/evergreen/blob/master/src/positioner/src/Positioner.js#L155), assigning `update` function as the event handler
* when `scroll` event happens, we pass an `event` object as `prevHeight` param to the `update` function ([ref](https://github.com/segmentio/evergreen/blob/master/src/positioner/src/Positioner.js#L65))
* if `hasEntered` is `false` in the `update` function, then we calculate `height` as `Math.max(number, Object)`, which results in `NaN` ([ref](https://github.com/segmentio/evergreen/blob/master/src/positioner/src/Positioner.js#L91))
* that results in `setDimensions` setting `height` and `top` as `NaN` making the `Popover` disappear from screen ([ref](https://github.com/segmentio/evergreen/blob/master/src/positioner/src/Positioner.js#L110))

I'm pretty sure that `height = Math.max(number, Object) // NaN` was not intentional, and seems like a bug to me.

<details>
  <summary>Console output</summary>
  
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/111731892/204385013-676e9b00-0d86-4679-9d38-1df8f155a25c.png">

</details>

**Comment by brandongregoryscott** [comment]
@dengribar Is this reproducible in a CodeSandbox? https://codesandbox.io/s/create-react-app-evergreen-starter-ts-3q99w

**Comment by dengribar** [comment]
Better late than never, but I was able to reproduce the bug that happens in our automated tests:

https://codesandbox.io/s/evergreen-ui-6-12-0-popover-works-fine-on-scroll-ws9xox?file=/src/App.tsx

https://user-images.githubusercontent.com/111731892/213792623-f8a6104e-47f9-4dd4-b5ca-90529074a568.mov

Not exactly, though, since on v6.12.0 our automated tests work fine, but the sandbox example still doesn't work.

On the other hand, on v7.0.0, despite the same `NaN value for top property` warning, the popover is displayed in an appropriate position:

https://user-images.githubusercontent.com/111731892/213793030-449fa353-34ba-4886-aa16-2c620791a76f.mov

Anyway, even though v7.0.0 kind of patches the issue somehow, the bug with passing an `event` object as `prevHeight` param to the `update` function ([ref](https://github.com/segmentio/evergreen/blob/master/src/positioner/src/Positioner.js#L65)) needs to be fixed, and I hope that it will properly patch the issue. Thanks!

**Comment by brandongregoryscott** [comment]
This should be fixed in https://github.com/segmentio/evergreen/releases/tag/v7.1.3!
