### ISSUE TITLE
Pass value, label as Items on Combobox, selectmenu Props

### ISSUE THREAD

**Issue by Ok9xNirab** [segmentio/evergreen#1589]
Basic combobox example:

```jsx
<Combobox
  items={['Banana', 'Orange', 'Apple', 'Mango']}
  onChange={selected => console.log(selected)}
  placeholder="Fruit"
  autocompleteProps={{
    // Used for the title in the autocomplete.
    title: 'Fruit'
  }}
/>
```

I want to pass items something like : 

```js

const items = [
 { label: "A", value: 1 },
 { label: "B", value: 2 },
]
```

When select any of this item , then it should return only value via `onChange` event.

**Is it possible now ?? I didn't find anything in Documentation !!**

**Comment by brandongregoryscott** [comment]
You can pass a list of custom items to the Combobox ([see example here](https://evergreen.segment.com/components/combobox#custom_items_and_default_selected_item)), you just need to provide an `itemToString` function (which provides the label). The `onChange` handler will return the whole item, though, so you'd need to do something like...

```tsx
<Combobox
  initialSelectedItem={{ label: 'Banana' }}
  items={[{ label: 'Banana', id: 1 }, { label: 'Pear', id: 2 }, { label: 'Kiwi', id: 3 }]}
  itemToString={item => (item ? item.label : '')}
  onChange={selected => console.log(selected.id)}
/>
```

**Comment by Ok9xNirab** [comment]
Thanks !
