### ISSUE TITLE
Chore: Remove tinycolor2

### ISSUE THREAD

**Issue by brandongregoryscott** [segmentio/evergreen#1592]
After removing the classic/deprecated default themes in the v7 branch, I noticed we're only using `tinycolor2` in one place: the `Badge` component theme. https://github.com/segmentio/evergreen/blob/master/src/themes/default/components/badge.js#L19

After running this code in the console, it looks like `isLight` returns true for `yellow` and `orange`, however - I don't think this fallback object is ever really hit. Let's verify that we prevent users from passing arbitrary colors (i.e. anything other than the keys of `fills.colors`) and remove this dependency/unnecessary code.

**Comment by Himu1503** [comment]
Hi @brandongregoryscott  Can you assign me this issue, this is my first open source contribution, would love to work on it. 
Thanks.

**Comment by brandongregoryscott** [comment]
@Himu1503 We don't assign issues to non-Segment contributors, but contributions are always welcome. Take a look at our [contributing guidelines](https://github.com/segmentio/evergreen/blob/82c3a86cf07680f93a743e67bc30255c8372e60e/.github/CONTRIBUTING.md) and open up a PR when your work is ready!
