### ISSUE TITLE
`SideSheet` prevents page scroll even after closing, when `preventBodyScrolling` set to true

### ISSUE THREAD

**Issue by malimccalla** [segmentio/evergreen#1619]
I'm using the `<SideSheet />` component in the following way

```jsx
        <SideSheet
          preventBodyScrolling={true} //  could also be `sheet.visible` and it has same effect.
          onCloseComplete={() => sheet.close()}
          width={420}
          isShown={sheet.visible}
          position="right"
        >
          <Profile />
        </SideSheet>
```

I'm controlling the visibility of the sheet with a basic hook that toggles `sheet.visible` via `sheet.close()` and `sheet.open()`. This is working as expected.

However, when using the `preventBodyScrolling` prop, I can no longer scroll on the page after closing the sheet

**Comment by brandongregoryscott** [comment]
Hey @malimccalla, can you provide a CodeSandbox for reproduction? I'm not seeing the described behavior: https://codesandbox.io/s/issue-1619-sidesheet-preventbodyscrolling-example-3f1sob?file=/src/App.tsx
