### ISSUE TITLE
Can't use (intent) and (type) property at the same time in <Button> component

### ISSUE THREAD

**Issue by addayounes** [segmentio/evergreen#1628]
when using intent in a button and also specifying a button type (submit | reset | button) this will break the styling of the button, more specifically it will lose it's style on certain state like focused state or blured

**Comment by brandongregoryscott** [comment]
@addayounes Can you provide a CodeSandbox to reproduce this? The focus states seem to be working correctly: https://codesandbox.io/s/issue-1628-button-intent-type-yyddq7?file=/src/App.tsx
