### ISSUE TITLE
Button disabled icon color doesn't change

### ISSUE THREAD

**Issue by deli-ght** [segmentio/evergreen#1644]
hi, is there any update for this pr? https://github.com/segmentio/evergreen/pull/1638

**Comment by brandongregoryscott** [comment]
Sorry about the delay here! Let me take another look. I had some concerns around color consistency with other buttons in a `disabled` state, but I think this is fine - matches our current secondary button disabled style.

**Comment by deli-ght** [comment]
Thanks a lot!
