### ISSUE TITLE
Feature Request: Disabled State for Tab component

### ISSUE THREAD

**Issue by systemizer** [segmentio/evergreen#174]
Tabs currently don't have a disabled property. If we want to make a component disabled, and it contains a tabs component, it is not possible to make the tabs component non-interactive.

I'm currently getting around this by adding the passing in the following CSS, but it would be nice to have a disabled property that automatically applies the css and also prevents click actions to fire

```
const disabledTabStyle = {
  cursor: 'not-allowed',

  '&:focus': {
    boxShadow: 'none'
  },

  '&[aria-current], &[aria-selected="true"], &:active': {
    backgroundColor: colors.neutral['5A'],
    color: colors.neutral['500']
  }
}
```

**Comment by jeroenransijn** [comment]
Nice addition! Seems like something we need. Expect this to land in V3 somewhere.

**Comment by jeroenransijn** [comment]
https://github.com/segmentio/evergreen/releases/tag/v4.4.0
