### ISSUE TITLE
Theming / changing colors?

### ISSUE THREAD

**Issue by pluma** [segmentio/evergreen#179]
Evergreen looks great and I'm thinking about using it in an upcoming open-source project.

However the documentation and storybook do not address theming as far as I can tell. Looking at the shared-styles folder it seems that the color references are hardcoded in several places.

Is it possible to override the style choices (e.g. to change the highlight colors) or implement alternative themes (e.g. a dark theme) without forking the project? If not, do you plan to add support for this in the future?

I hope this is the right avenue to ask this question as the README didn't indicate any other support channels for asking questions.

**Comment by jeroenransijn** [comment]
Hi @pluma! Thanks for taking the time to create an issue. We are currently working on a documentation website (http://evergreen.surge.sh/get-started/theming) that also has a small section about theming. Below I give more clarification around the roadmap.

**Evergreen currently does not support theming.**

## Is theming support on the roadmap?
This project is originally build to support the development of product at Segment. This is also the reason theming is not our short term priority. It is on our longer term priority list and hopefully will be supported later in 2018. Expect a clearer roadmap available before that.

## How does that roadmap look like?
We have been thinking about theming and doing research on theming for a while now. There are still higher priority items for us to tackle inside of Evergreen and internally at Segment before we can making theming a priority. 

### Milestones
Roughly I see this is as the milestones to achieve theming within Evergreen:

- Work through dependencies for theming layer
- Centralize all theming information (privately)
- Expose a theming provider to consumers. (public)

### Work through dependencies for theming layer
Before we can start working on theming itself, we have to improve some of the systems inside Evergreen — primarily the color system and some type systems. The following items come to mind:

- Color System overhaul
- Typography tweaks
- 100% documentation for public components and API stability

### Centralize all theming information (privately)
On the short term we are tackling the color system and that should be one of the first steps to enabling a theming layer. Once we got those dependencies figured out we can start working towards centralizing all theme related information that is currently scattered around components. This would give us a centralized place that determines the theme of Evergreen and serve as a basis to start exposing this through a `ThemeProvider` of some sorts.

### Expose a theming provider to consumers. (public)
After we have created an internal API for theming the next step is to expose this through a `ThemeProvider` interface. Material UI and Mineral UI are good examples of how something like that might look.

**Comment by pluma** [comment]
Thanks for the quick response!

That sounds great but sadly this probably means we won't be able to use evergreen for the project right now. I'll make a note to revisit next year or so.

**Comment by tlouth19** [comment]
What is the latest update on theming?

**Comment by zhaoyao91** [comment]
Great is evergreen! Theming only makes it better! Look forward to the good news :)))

**Comment by Jakobo** [comment]
Adding a note here for anyone who's still looking for theming in evergeen. With the `ThemeProvider` in place, it's possible to extract all of the primitives (and derived colors). Doing so would make it possible to pass a 100% custom theme into the `ThemeProvider` object.

There's a PR at https://github.com/segmentio/evergreen/pull/721 which could use 👀 that does exactly this. It pulls all the values from the current theme object before falling back to evergreen's default theme. It allows for custom themes with `defaultTheme.extend()` and properly supports nested themes and nested `ThemeProvider` objects. It's also backwards compatible with v4 of evergreen.
