### ISSUE TITLE
Popover/Positioner does not work on mobile

### ISSUE THREAD

**Issue by jaredpalmer** [segmentio/evergreen#181]
AFAICT popover does not work on mobile as expected. It seems this is an issue with positioner and could be solved by moving to `react-popper` instead of the current implementation.
![kapture 2018-04-08 at 12 33 29](https://user-images.githubusercontent.com/4060187/38469849-322c71a0-3b29-11e8-8f03-daf7b0454112.gif)

**Comment by jeroenransijn** [comment]
Hey @jaredpalmer, thanks for putting in your time to write this issue, much appreciated!

We have been thinking about moving over to popper.js, similar to how BlueprintJS implements popper.js in their Popover. That being said, I am not sure if we can prioritize that on our short term timeline, there is some overhead in porting over to popper.js. Although mobile is not a priority for us atm, I would still like to fix this bug in our current implementation (and do more cross-browser testing). I am honestly not quite sure why this is as broken as it is.

**Comment by jaredpalmer** [comment]
It would appear that the measurement is not working--potentially the wrong position match. Re: React-popper, I've started out with this uncontrolled component for React Popper and added features as necessary. In this case, would need to add keyboard listeners. 

```
import * as React from 'react';
import { Manager, Target, Popper as Pop, IPopperProps } from 'react-popper';
import { Toggle, ToggleHelpers } from './Toggle';

export interface PopperProps extends IPopperProps {
  target?: string | JSX.Element | ((props: ToggleHelpers) => React.ReactNode);
  content?: JSX.Element | ((props: ToggleHelpers) => React.ReactNode);
}

export const Popper: React.SFC<PopperProps> = ({
  placement,
  content,
  target,
}) => (
  <Toggle
    render={(toggleProps: ToggleHelpers) => {
      const { isOpen, handleToggle, handleClose } = toggleProps;
      const targetProps = typeof target !== 'function' && {
        onClick: handleToggle,
      };

      return (
          <Manager onMouseLeave={handleClose}>
            <Target {...targetProps}>
              {typeof target === 'function' ? target(toggleProps) : target}
            </Target>
            {isOpen && (
              <Pop eventsEnabled={true} placement="auto">
                {typeof content === 'function' ? content(toggleProps) : content}
              </Pop>
            )}
          </Manager>
      );
    }}
  />
);
```

**Comment by jeroenransijn** [comment]
Thanks for sharing that snippet! Just realized you work on Formik, I am a big fan of that project 👍 

I do want to move over to Popper, but I am hoping we can solve this issue before migrating. I am afraid moving over to Popper might be a major release (although this doesn't need to be the case).

**Comment by jeroenransijn** [comment]
I found a fix for this, it's as simple as adding `position: fixed;` to the popover. I am creating a PR for this.

**Comment by jaredpalmer** [comment]
Nice!
