### ISSUE TITLE
Dialog + Select Menu dont go work together

### ISSUE THREAD

**Issue by EQuimper** [segmentio/evergreen#185]
Hello, first thing awesome stuff you've done here. I really loved it :).

I'm building a dialog for a user who can create a project from there. All go well for all the stuff until I had Select Menu of Combobox. The menu go bellow the dialog, like behind.

Here in this picture I just click the arrow button and nothing show, cause this is behind. This is the Combobox
<img width="1460" alt="screen shot 2018-04-13 at 10 07 50 pm" src="https://user-images.githubusercontent.com/15819498/38763328-1f5a710c-3f67-11e8-9d6b-5b1f2c3c903e.png">

Here with the SelectMenu, we can see the menu right below
<img width="1330" alt="screen shot 2018-04-13 at 10 09 56 pm" src="https://user-images.githubusercontent.com/15819498/38763355-c55bd3de-3f67-11e8-9c8b-bf980c14bfe9.png">

For the code this is just a copy paste from our docs. Nothing change in the ui, just a plain Dialog with the Component in.

Let me know if you need something more for help with this issue :)

**Comment by jeroenransijn** [comment]
Hi @EQuimper! Thanks for your kind words and for testing out Evergreen for your project. I just saw this ticket yesterday night, I will try to be more responsive next time!


## The Problem Explained
The problem you are experiencing is that the Popover the Combobox is using is rendered inside a Portal. It is rendering correctly, however the z-index of the Popover is lower than that of the Dialog. Really this should work out of the box and I need to figure out a solution for this.

When I was writing this answer I actually thought it is possible to pass  a `zIndex` prop to the Autocomplete component — which would mean you could pass it to `autocompleteProps` on the Combobox component. However it seems that is not the case and I have to put in a actual fix for this. I will try to tackle this today :)

**Comment by jeroenransijn** [comment]
See #187.

**Comment by EQuimper** [comment]
Thank you @jeroenransijn

**Comment by jeroenransijn** [comment]
@EQuimper I am trying to get this PR in today / this week. Just waiting on my buddy to review it :)

**Comment by jeroenransijn** [comment]
@EQuimper quick update, we might roll this up in v4 with a bunch of other upgrades!

**Comment by EQuimper** [comment]
Thank you for the update:)

**Comment by ITforHome** [comment]
@EQuimper Hi, I have a question about your project. In your Screenshots, i could see a gray sidebar and a header with the title "My Projects " and the button  "Create New Project ". 

- How did you build this in React? Are there any finished components from the evergreen framework? (So far I have not been able to find)
 - Which icons did you use?
 - Could you possibly show me some code of it? (I also wanted to develop an React-WebApp according to this scheme (Sidebar and Header)

Thanks for your answer.

**Comment by jeroenransijn** [comment]
Closing this since the issue has been resolved!
