### ISSUE TITLE
Toaster invoked before document is fully loaded error

### ISSUE THREAD

**Issue by anastassia-b** [segmentio/evergreen#192]
Hey Jay! Thanks for discussing a bug with me last night. For documentation/reference, here it is: 

<img width="564" alt="error_message" src="https://user-images.githubusercontent.com/26614978/39384627-5ca1a420-4a22-11e8-9118-8e615d9e9ded.png">

This error occurred when importing anything from evergreen-ui, as tested with two personal projects. Steps to replicate the error were simply to `npm install --save evergreen-ui`, adding any import line, such as `import { Button } from 'evergreen-ui';` webpacking, and visiting the page.  

The cause of this error is `document.body.appendChild(container)` being invoked (Toaster.js#25) before the document has fully loaded. I do not get this error if I place the script at the bottom of the document (instead of in the head), or if I import/require evergreen components from _inside_ a document.ready callback.

Investigating, Toaster and Portal are the only ones with this behavior in the constructor. `new Toaster()` was invoked in `src/toaster/src/index.js#3`. Wrapping the code to be executed only then the document is fully loaded should solve the issue. Thank you!

**Comment by anastassia-b** [comment]
Interestingly, this bug does not occur if I start an app with `create-react-app`, only when I create all the configurations from scratch.

**Comment by Rowno** [comment]
If you include your JavaScript file at the bottom of the HTML file the bug shouldn't occur (this is probably what create-react-app is doing).

**Comment by anastassia-b** [comment]
Yep, I know, I mentioned that in my comment above ("I do not get this error if I place the script at the bottom of the document (instead of in the head)"). I'll do that as a workaround, but just wanted to bring it up. Thanks! :)

**Comment by anastassia-b** [comment]
Haha that's right. Probably can just close this issue then 👌
