### ISSUE TITLE
FireFox Native Select

### ISSUE THREAD

**Issue by jeroenransijn** [segmentio/evergreen#203]
So much for cross browser testing! I think I saw some other libraries use a wider select of like 120% to push this out probably. I am hoping there is a pure CSS solution for this and not just a hacky workaround. @Rowno any ideas?

![image](https://user-images.githubusercontent.com/564463/41492848-aed6744a-70b6-11e8-881d-3060373fc7d4.png)

**Comment by wyattjoh** [comment]
Was this issue not resolved? This is as of today:

https://evergreen.segment.com/components/select
![screen shot 2018-10-17 at 9 58 28 am](https://user-images.githubusercontent.com/633002/47099778-9037d080-d225-11e8-98c5-d9da457da4c1.png)
