### ISSUE TITLE
Table.VirtualBody

### ISSUE THREAD

**Issue by jeroenransijn** [segmentio/evergreen#210]
Virtualization is a annoying and often a bit scary to implement. I have been thinking about some ways to make virtualization super easy. My assumption is that the real rendering bottle neck is all the nodes on the pages, and 

## The world right now
`renderRow` would return `Table.Row`

```jsx
<Table.Body height={640}>
    <VirtualList
        height={640}
        width="100%"
        itemSize={48}
        overscanCount={3}
        itemCount={items.length}
        renderItem={({ index, style }) => {
             return <Table.Row style={style}>{items[index]}</Table.Row>
        }}
    />
</Table.Body>
```

### Option 1

* Is this actually performant, since we are mapping everything?
* We can use `this.props.children` within `Table.VirtualBody` to use `VirtualList` within that component.
* Should `Table.Body` magically determine if it's virtualized based on children length?
* Should we have `<Table.Body virtualized />` ?

```jsx
<Table.VirtualBody height={640}>
    {items.map(item => <TableRow key={item}>{item}</TableRow>)}
</Table.VirtualBody>
```
...or

### Option 2
* `renderRow` would return `Table.Row`

```jsx
<Table.VirtualBody
   height={640}
   renderRow={({ index, rowProps }) => {
      return <Table.Row {...rowProps}>{items[index]}<Table.Row>
    }}
/>
```

**Comment by mshwery** [comment]
It would be great to support auto-sizing height too!

**Comment by jeroenransijn** [comment]
@mshwery yeah I am going to try and support at out of the box 👍
