### ISSUE TITLE
TableRow that has `isSelectable` prop is not propagating onChange event

### ISSUE THREAD

**Issue by emadabdulrahim** [segmentio/evergreen#211]
I'm working on implementing editable table cells using Evergreen components.

My issue comes when I have a `TextInput` component that implements `onChange` event inside a `TableRow` that has `isSelectable` prop.

What happens is `onChange` event does NOT get triggered **when hitting the space key on the keyboard.**

If I remove `isSelectable` from `TableRow` things work as expected`

I suspect this line in `TableRow` is causing the problem
https://github.com/segmentio/evergreen/blob/de5ebddc8a07bfc910cde63c9fd0389025d5a12e/src/table/src/TableRow.js#L61

```jsx
handleChange = e => {
    const { target } = e

    console.log("onChange", target.value)

    this.setState(currentState => ({
      [target.id]: {
        ...currentState[target.id],
        editValue: target.value,
      },
    }))
  }


render() {
  return (
    <TableRow isSelectable>
      <TextTableCell borderRight={borderRight}>
        {isEditing ? (
          <TextInput
            height={28}
            width="100%"
            value={children}
            // onChange doesn't fire when I hit the space key
            onChange={this.handleChange}
            {...rest}
          />
        ) : (
          children
        )}
      </TextTableCell>
    </TableRow>
  )
}
```

Thanks!

**Comment by jeroenransijn** [comment]
This is using Evergreen v4.
