### ISSUE TITLE
[v4] `Select` prop-type appearance warning 

### ISSUE THREAD

**Issue by mshwery** [segmentio/evergreen#212]
`Select` isn't listed as having any breaking changes in [v4](https://github.com/segmentio/evergreen/pull/200) but I'm getting prop-type warnings for not defining an `appearance` prop:

```
Warning: Failed prop type: Select: prop type `appearance` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.
```

<img width="1706" alt="screen shot 2018-07-09 at 4 05 44 pm" src="https://user-images.githubusercontent.com/710752/42480388-f9513b7a-8391-11e8-8b4a-d832d117d93a.png">

**Comment by jeroenransijn** [comment]
https://github.com/segmentio/evergreen/releases/tag/v4.0.0-2
