### ISSUE TITLE
[v4] Invalid DOM property `autofocus` from `Box`

### ISSUE THREAD

**Issue by mshwery** [segmentio/evergreen#213]
In [v4](https://github.com/segmentio/evergreen/pull/200), it seems that `Box` is not implementing the `autoFocus` attribute/prop as expected by React. I'm seeing prop-type warnings:

```
Warning: Invalid DOM property `autofocus`. Did you mean `autoFocus`?
```

**Comment by jeroenransijn** [comment]
https://github.com/segmentio/evergreen/releases/tag/v4.0.0-3
