### ISSUE TITLE
[v4] Alert component's icon and title are slightly misaligned

### ISSUE THREAD

**Issue by mshwery** [segmentio/evergreen#214]
The icon for the `Alert` component seems slightly misaligned (vertically) with the title.

|BEFORE (V3)|AFTER (V4)|
|---|---|
|<img width="208" alt="screen shot 2018-07-09 at 4 52 15 pm" src="https://user-images.githubusercontent.com/710752/42481681-86c0d6d6-8398-11e8-9942-06f3e881cdef.png">|<img width="195" alt="screen shot 2018-07-09 at 4 52 21 pm" src="https://user-images.githubusercontent.com/710752/42481680-86a7bdea-8398-11e8-8c32-22d6d4d96a34.png">|

**Comment by jeroenransijn** [comment]
https://github.com/segmentio/evergreen/releases/tag/v4.0.0-3
