### ISSUE TITLE
Combobox with itemToString prop does NOT autocomplete as I type

### ISSUE THREAD

**Issue by emadabdulrahim** [segmentio/evergreen#215]
I noticed when I use `<Combobox itemToString/>` such as in the last example provided in the docs

```jsx
<Combobox
  defaultSelectedItem={{ label: 'Banana' }}
  items={[{ label: 'Banana' }, { label: 'Pear' }, { label: 'Kiwi' }]}
  itemToString={item => item.label}
  onChange={selected => console.log(selected)}
/>
```

Autocomplete doesn't work in that case.

_P.S._
Also, in that same example in the docs if you try to backspace all the way to remove the selected item, you'll notice this error message
`TypeError: Cannot read property 'label' of null`

I'm guessing that's because `onSelects` fires and sends an empty object. I wonder if there is a better way to implement this without having the consumer of the component to code defensively.

**Comment by timtutt** [comment]
In case anyone comes across this again, after about 2 hrs of digging through code I just figured out the issue and a solution...

By default the underlying AutoComplete Component uses `fuzzaldrin` for the filtering by default and passes items to the `fuzzaldrin.filter` function without the option to handle objects.

Was able to work around this by importing `fuzzaldrin` into my project using:
 ```bash
npm install --save fuzzaldrin-plus
```

And then creating my own fuzzy filter that takes advantage of the "key" option in `fuzzaldrin.filter` for filtering of objects:
```jsx
const fuzzyFilter = (items, input) => fuzzaldrin.filter(items, input, {key: "label"});
```

And passing that as an `autocompleteProp`:
```jsx
<Combobox
  defaultSelectedItem={{ label: 'Banana' }}
  items={[{ label: 'Banana' }, { label: 'Pear' }, { label: 'Kiwi' }]}
  itemToString={item => (item != null ? item.label : "")}
  onChange={selected => console.log(selected)}
  autocompleteProps={{    // Used for the title in the autocomplete.
     title: 'Dataset',
     itemsFilter: fuzzyFilter
  }}
/>
```

Also note the error checking to handle cases where there is no item returned if you backspace all the way out.
