### ISSUE TITLE
(Minor) toaster component misaligned text with icon

### ISSUE THREAD

**Issue by emadabdulrahim** [segmentio/evergreen#217]
toaster component text is misaligned with the close (X) icon, maybe it could have `align-items: center`  as part of it's style?

_without centering_
![screen shot 2018-07-10 at 12 05 14 pm](https://user-images.githubusercontent.com/7950797/42532030-6c91dee8-843a-11e8-8e9a-14b7cfcab89b.png)

_with centering_
![after](https://user-images.githubusercontent.com/7950797/42531977-48884046-843a-11e8-8a30-2c2288acfc51.png)

**Comment by jeroenransijn** [comment]
Fixed.
