### ISSUE TITLE
[v4] TextInputField has different input font-size than TextInput

### ISSUE THREAD

**Issue by mshwery** [segmentio/evergreen#220]
Top one is `TextInput` bottom is `TextInputField`
<img width="693" alt="screen shot 2018-07-10 at 7 48 02 pm" src="https://user-images.githubusercontent.com/710752/42548082-2e9e0f0e-847a-11e8-828c-3617ef436494.png">

**Comment by jeroenransijn** [comment]
v4.0.0-10 set default `inputHeight` to 32.
