### ISSUE TITLE
Select menu behavior

### ISSUE THREAD

**Issue by jfmaggie** [segmentio/evergreen#223]
**Problems**

Check select menu stories in storybook and some use case in our segment app I think there are a few issues for select menu:

1. Use keyboard arrow key up/down, the list doesn't scroll into the selected position, so you can't see where you are at in the list

![kapture 2018-07-12 at 13 43 15](https://user-images.githubusercontent.com/7209644/42658233-951bc45a-85d9-11e8-87b0-f33df0d32708.gif)

2. Use keyboard arrow key up/down are selecting the current item. Checked some select menu examples such as http://blueprintjs.com/docs/versions/2/#select/select-component, Github Assignees issue selector, the list allows us use arrow key to browse list items without triggering select immediately. So we consume the original state of selected item if we only browse list. That being said, hitting enter key should select the item. `onSelect` should be the prop that let user decide if menu should be closed or deselect.

**Example of working select menu**

![kapture 2018-07-12 at 13 44 26](https://user-images.githubusercontent.com/7209644/42658335-dada4fd4-85d9-11e8-9775-0e033538d67a.gif)

3. After close the menu, while it's still focused on the toggle button, hit enter won't open the menu. Only pressing the enter key down will keep the menu open.

**Evergreen select menu**

![kapture 2018-07-12 at 13 59 32](https://user-images.githubusercontent.com/7209644/42659033-dbeb347c-85db-11e8-8202-174bc285c49c.gif)

**Example of working select menu**

![kapture 2018-07-12 at 13 58 37](https://user-images.githubusercontent.com/7209644/42658995-baa2ee5e-85db-11e8-8f4d-d8ca1dbeb120.gif)

**Comment by mshwery** [comment]
Looks like this is (mostly) implemented in recent versions.

**Comment by sdoan16** [comment]
@mshwery Is anyone working on this?

**Comment by mshwery** [comment]
We've had a couple stabs at it that haven't landed like #611 #733 that are related. I would take a look at those approaches and discussions first.

**Comment by mshwery** [comment]
Closing this as 1 has been resolved, and 2 is up for discussion with EG maintainers!
