### ISSUE TITLE
Should buttons have required intents? 

### ISSUE THREAD

**Issue by Flaque** [segmentio/evergreen#224]
In the PropTypes of `Button` in [the code for v4](https://github.com/segmentio/evergreen/blob/v4/src/buttons/src/Button.js#L35-L36), an `intent` is required, including one that would have the `none` intent:

```
<Button intent="none" />
``` 

But in [the docs for v4](http://evergreen-v4.surge.sh/components/buttons/), `none` buttons just have no intent prop: 

```
<Button />
```

I'd submit a PR to fix this, but I'm not sure which is the "correct" way.

**Comment by mshwery** [comment]
@Flaque I think you could remove the `.isRequired` flag on the prop for that component.

**Comment by mshwery** [comment]
But we'd also want to add `intent: 'none'` to `defaultProps` (correct me if I'm wrong here).

**Comment by Flaque** [comment]
From my understanding of how React proptypes work, that makes the most sense.  I'll submit a PR 🙌
