### ISSUE TITLE
[v4] `SegmentedControl` missing focus state

### ISSUE THREAD

**Issue by mshwery** [segmentio/evergreen#229]
This component doesn't have the same focus state as other form controls. In the below screenshot you can't tell the difference between the `SegmentedControl`'s focus state and unfocused state:

<img width="688" alt="screen shot 2018-07-16 at 11 27 57 pm" src="https://user-images.githubusercontent.com/710752/42796474-f8fae8ec-894f-11e8-8093-4485d3f8faa2.png">

**Comment by jeroenransijn** [comment]
Thanks for documenting, have been thinking how to support this properly. Will put this in v4 shortly.
