### ISSUE TITLE
[v4] Add `MenuItem` support for `is` prop 

### ISSUE THREAD

**Issue by mshwery** [segmentio/evergreen#230]
Today the newly minted `Menu` and `Menu.Item` components are awesome, but often menu items are links, or more specifically – _react-router_ links.

I would love to see support for `is={ReactRouterLink}` or `is={MyCustomComponent}` support so we can maintain the look and feel (and keyboard focus management) of menus, but enabling them to link to other urls/paths.

**Comment by jeroenransijn** [comment]
Ah yeah this is super useful! Will move this in shortly.

**Comment by mshwery** [comment]
We should also evaluate _always_ allowing `{...props}` overrides for consumers that want to control the outermost component's props. I see that MenuItem doesn't provide any extra props spreading.

**Comment by jeroenransijn** [comment]
Fixed in https://github.com/segmentio/evergreen/releases/tag/v4.0.0-12
