### ISSUE TITLE
side sheet from the left

### ISSUE THREAD

**Issue by bmcmahen** [segmentio/evergreen#246]
Any interest in a PR that enables the side-sheet to appear from the left? I have a basic fork of this in my app so that I can use it in the material-ui app navigation way. I suspect others might want the same.

**Comment by jeroenransijn** [comment]
@bmcmahen this is for sure something we want in Evergreen! Main reason why it's not in there atm is because we don't have left side sheet in our app (yet). Would be awesome if you could put in a first PR!

**Comment by bmcmahen** [comment]
Great - I'll clean up my code and pass in a PR within the next day or so.
