### ISSUE TITLE
[v4] Popover/Positioner jitter

### ISSUE THREAD

**Issue by jeroenransijn** [segmentio/evergreen#255]
I thought I fixed the jittering of Popover and Positioner multiple times at this point. Today I ran into another instance in which it happens.

![image](https://user-images.githubusercontent.com/564463/43160007-ce7940a2-8f38-11e8-9dab-c8d464d61251.png)

I am using a screen connected to my MacBook, and that is when this issue can happen. As you can see the width of the `html` tag is not an integer, but is `1424.8px`. Now we fully understand the circumstances this happens, I can actually recreate and test it properly.

## Zoomed in by 125%

In this case I am also zoomed in 125%:

![image](https://user-images.githubusercontent.com/564463/43161153-272d37c8-8f3c-11e8-9edc-ab3f15beb5f4.png)

## Different value within Positioner

Within the positioner logic we are using the following statement `document.documentElement.clientWidth + window.scrollX` which returns a number of `1425`. 

### What I am getting from the `targetRef`

![image](https://user-images.githubusercontent.com/564463/43160384-d4e3d690-8f39-11e8-8ace-cc3654772d2e.png)

### `this.positionerRef.offsetWidth` is jumping

Finally I think I found the actual problem, the `positionerRef` constantly gives a slightly different width — off by one pixel.

![image](https://user-images.githubusercontent.com/564463/43160497-26f4bcc4-8f3a-11e8-9725-d8676273463e.png)

**Comment by jeroenransijn** [comment]
# Current potential solution

```javascript
  preventJitter = (prevValue, nextValue) => {
    // When the device pixel is not an integer and
    // ...when the absolute difference between the previous and next value is 1
    // ...kick in anti jitter.
    if (
      !Number.isInteger(window.devicePixelRatio) &&
      Math.abs(nextValue - prevValue) === 1
    ) {
      return prevValue
    }

    return nextValue
  }

  update = ({ prevDimensions }) => {
    if (!this.props.isShown || !this.targetRef || !this.positionerRef) return

    const targetRect = this.getTargetRect()
    const viewportHeight =
      document.documentElement.clientHeight + window.scrollY
    const viewportWidth = document.documentElement.clientWidth + window.scrollX

    const dimensions = {
      height: this.preventJitter(
        prevDimensions.height,
        this.positionerRef.offsetHeight
      ),
      width: this.preventJitter(
        prevDimensions.width,
        this.positionerRef.offsetWidth
      )
    }

    const { rect, transformOrigin } = getPosition({
      position: this.props.position,
      targetRect,
      targetOffset: this.props.targetOffset,
      dimensions,
      viewport: {
        width: viewportWidth,
        height: viewportHeight
      },
      viewportOffset: this.props.bodyOffset
    })

    this.setState(
      {
        left: rect.left,
        top: rect.top,
        transformOrigin
      },
      () => {
        window.requestAnimationFrame(() => {
          this.update({ prevDimensions: dimensions })
        })
      }
    )
  }
```

**Comment by mshwery** [comment]
I'm not super familiar with how this functions today, but couldn't we do something a bit simpler – i.e. always take a `Math.round`ed (or floored) number for calculations. That _should_ result in the same value every time.

It's unclear why the `positionRef` would be giving different values, but I presume it's actually the inclusion of the positioned popover that's causing the subtle difference.

**Comment by jeroenransijn** [comment]
@mshwery we are actually doing `Math.round` in the calculation — which I thought fixed the problem. However, it seems that the input keeps because `offsetWidth` is not reliable in this case. It keeps shifting after the calculation is done when the screen is zoomed in. I am going to test this solution and see if it fixes the problem.

One thing that might be affecting this issue as well is that the contents of the Popover give it a slightly different width on each render when the content exceeds the `minWidth`  — possibly due to the nature of how text is rendered.

**Comment by jeroenransijn** [comment]
Yeah it definitely seems part of the problem:

![image](https://user-images.githubusercontent.com/564463/43163540-4a77dd9e-8f43-11e8-9b3f-942801b2c40d.png)
