### ISSUE TITLE
Question: Nav menu

### ISSUE THREAD

**Issue by aliakakis** [segmentio/evergreen#262]
Hello and excellent library. Just wanted to inquire whether you will be releasing a nav menu or it should be build from a combination of Panes.

**Comment by jeroenransijn** [comment]
Hey @aliakakis! Thanks for showing interest in Evergreen and asking your question. We currently don't have a navigation component scheduled to live inside of Evergreen. I would recommend composing something with Panes, or using CSS / CSS-in-JS if it doesn't work with just Panes.

**Comment by aliakakis** [comment]
Excellent thank you for the quick reply.
