### ISSUE TITLE
DialogManager not exported?

### ISSUE THREAD

**Issue by rakibtg** [segmentio/evergreen#272]
Version: 3.2.4

While trying to use the [dialogue component](https://evergreen.surge.sh/components/dialog) it gives an error:
> 'evergreen-ui' does not contain an export named 'DialogManager'.
Imports are:
```javascript
import { Button, DialogManager, Box, Dialog, Paragraph } from 'evergreen-ui'
```
Am i missing something?

**Comment by JMFURY** [comment]
Hi @rakibtg I think I know what you're trying to do so hopefully this helps.

`DialogManager`, like similar components in the docs, is not an official component for the Evergreen system. It is utilized the docs and examples to serve as an example of how you might manage state for the `Dialog` component. 

See this thread also on how the examples also use Reactions for 'localized' state management
#175 

See also the import statement of DialogManager [here](https://github.com/segmentio/evergreen/blob/master/src/dialog/stories/index.stories.js) and look up [its definition here](https://github.com/segmentio/evergreen/blob/master/src/dialog/docs/DialogManager.js) if you want to know how the Evergreen team developed these sort of 'Manager' type wrapper components.

If you are looking to accomplish something specific I may be able to help! 

Cheers!

**Comment by rakibtg** [comment]
It seems that `Box` and `DialogManager` components are not a part of the ui framework.
Thanks for your help

**Comment by JMFURY** [comment]
Exactly. `Box` , also useful, is here: https://github.com/segmentio/ui-box
