### ISSUE TITLE
[v4] Tooltip on disabled IconButton hangs

### ISSUE THREAD

**Issue by jeroenransijn** [segmentio/evergreen#292]
## `Tooltip`

I got some reports that a Tooltip can hang on a disabled `IconButton`. Might be more universal for buttons.

**Comment by Munsterberg** [comment]
As in the tooltip shouldn't appear when the IconButton is disabled to clarify? (If so I noticed the same issue)

**Comment by vadimdemedes** [comment]
I took a look at this and the reason is that if any `<Button>` is disabled, it's an expected behavior for it to not trigger any events, not even mouseenter/mouseleave.
