### ISSUE TITLE
Export Manager component from main module

### ISSUE THREAD

**Issue by acarl005** [segmentio/evergreen#295]
Hello Segment team,

It would be nice if the `Manager` component was exported from the main module. It's featured in the [Corner Dialog](https://evergreen.surge.sh/components/corner-dialog) page, but I can't import it like
```js
import { Manager } from 'evergreen-ui'
```
Instead, I have to use
```js
import { Manager } from 'evergreen-ui/commonjs/manager'
```

evergreen-ui version: 3.2.4

**Comment by jeroenransijn** [comment]
Hi @acarl005 thanks for contributing! `Manager` was only used internally for creating stories. v4 now uses `@reactions/component` as much as possible.
