### ISSUE TITLE
Configure buttons for CornerDialog

### ISSUE THREAD

**Issue by acarl005** [segmentio/evergreen#297]
Hello Segment team,

The confirm button for the `CornerDialog` is always the green button. But the blue button works much better with my site's color scheme. It would be nice if there was a way to pass in configuration for which buttons I want.

```jsx
<CornerDialog title="Welcome to the search dashboard!"
              isShown={true}
              confirmButtonAppearance="blue"
              onCloseComplete={() => {}}
              onCancel={close => close()}>
  The Corner Dialog component is used for new feature announcements
  and feedback requests from the user.
</CornerDialog>
```

**Comment by mshwery** [comment]
In v4 you can specify the `intent` prop which will use the ThemeContext to provide the button colors/styles.

I don't think this is available in v3, unfortunately (nor is theming).

**Comment by jeroenransijn** [comment]
Thanks for raising this issue, since v4 offers the `intent` prop I will be closing this.
