### ISSUE TITLE
external data source support for `Autocomplete` and `Combobox` components 

### ISSUE THREAD

**Issue by orkideh** [segmentio/evergreen#309]
Dear Contributors,

I found your project cool and I would like to join you here to bring some values to opensource community, So I checked [Autocomplete](https://evergreen.surge.sh/components/autocomplete) and [Combobox](https://evergreen.surge.sh/components/combobox) but seem the do`t support any external data source like ajax request. What do you think about updating them and adding this feature to both ?

**Comment by jeroenransijn** [comment]
@orkideh thanks for interest in contributing! I think this is an interesting idea, the next step could be to provide a example of how you would like to see this implemented. 

I am curious if this should be the baked into the component. My assumption is that with the current setup you could fetch results on `onChange` and load those in the items? Might be oversimplifying it here.

**Comment by orkideh** [comment]
I`m glad you found it interesting.
I read the code it`s dependent on [downshift](https://github.com/paypal/downshift), `onChange` event is called when you already made your choice, so it does`t work for us.

I can describe it in this way just image we have `two` more props `apiCall` and `debounce` that:
* `debounce`: will be `numeric` value defines time to devounce user input.
* `apiCall`: will be function that will receive user input and return promise of array of result.

To implement this i found `prop` in `downshift` name `onInputValueChange`. like : 
 ```
  render() {
    const {
      children,
      itemSize,
      position,
      renderItem,
      itemsFilter,
      popoverMaxHeight,
      popoverMinWidth,
      defaultSelectedItem,
      ...props
    } = this.props

    props.onInputValueChange = this.handleOnchange;
```
and `handleOnchange` will be function internally defined in component that receive input and call the `apiCall` and update `items` with result from `apiCall`.

but here I had problem with rendering new `items` and passed down :(.

I would like hear what do you think about this solution and I will be happy if you share your wise insight about it.
