### ISSUE TITLE
Small suggestion for more compatibility for windows based developer to kick start hacking 

### ISSUE THREAD

**Issue by orkideh** [segmentio/evergreen#319]
As a windows user I had to introduce some changes before start hacking I hope they will be useful to share and  help other windows based developer.

1. To run `yarn dev` windows does not support `export` command so I simplified it to new line in `package.json` like line bellow then developer can enjoy `yarn dev-win` easily. 
```
    "dev-win": ".\\node_modules\\.bin\\start-storybook -p 6006",
```

2. Also there is difference in new line between mac/linux and windows so I had to add new line `package.json` to `xo` configuration in `rules` section like: 
```
  "linebreak-style": 0
```

**Comment by jeroenransijn** [comment]
Thanks @orkideh for hacking around! It seems maybe we can use `cross-env` to solve this problem: https://github.com/kentcdodds/cross-env

**Comment by Rowno** [comment]
And shouldn't have any issues with the line endings when you have [editorconfig](https://editorconfig.org/) enabled in your editor.

**Comment by orkideh** [comment]
@Rowno  the editor like `webstorm` did good but `Atom` can`t handle it event with plugin. the more important thing running command `yarn test`. will throw error millions of error (exactly 18213 :D).

**Comment by orkideh** [comment]
@jeroenransijn I believe it should help, could you give example how `dev` may look like with implementing `cross-env`. For me it has this error :
```
λ yarn dev
yarn run v1.9.4
$ (cross-env EG_PORT=6006 ; if [ $PORT ] ; then start-storybook -p $PORT ; else start-storybook -p $EG_PORT ; fi)
';' is not recognized as an internal or external command,
operable program or batch file.
events.js:167
      throw er; // Unhandled 'error' event
```

**Comment by Rowno** [comment]
I'm not sure those environment variables are even used, maybe we can just change it to `start-storybook -p 6006` 🤔

**Comment by Rowno** [comment]
Looks like it is on the `v4` branch 🙂 https://github.com/segmentio/evergreen/blob/v4/package.json#L20

**Comment by jeroenransijn** [comment]
Hi @orkideh! Since I don't have access to Windows atm, could you provide some context around the current dev experience and hurdles you are still running into?

**Comment by orkideh** [comment]
@jeroenransijn That was just those two point. the rest is the same.
