### ISSUE TITLE
[v4] Switch should support a "value" prop

### ISSUE THREAD

**Issue by Flaque** [segmentio/evergreen#325]
# Overview
In order for an `onChange` prop to be effective in a [switch](https://github.com/segmentio/evergreen/tree/master/src/switch), you have to pass a value in with an anonymous function, which is not consistent with other `input` type items in React.  

## How Evergreen currently does it 

```jsx
<Switch onChange={() => this.onChange(myValue)} />
```

## How Evergreen should do it

```jsx
<Switch onChange={this.onChange} value={myValue} />
```

## How other inputs work

```jsx
import { TextInput } from 'evergreen-ui'
<TextInput onChange={this.onChange} value={myValue} />
```

**Comment by prateekgoel** [comment]
I would like to work on this.

**Comment by Flaque** [comment]
@prateekgoel go for it! 🎉

**Comment by prateekgoel** [comment]
Thank you @Flaque

**Comment by prateekgoel** [comment]
@Flaque PR submitted.

**Comment by jeroenransijn** [comment]
The switch is semantically a checkbox, I think it should be the `checked` prop instead of `value`. https://evergreen.segment.com/components/switch

```javascript
<Switch onChange={this.onChange} checked={isChecked} />
```
