### ISSUE TITLE
No Callback For Dialog onCancel

### ISSUE THREAD

**Issue by jbwhitcombe** [segmentio/evergreen#326]
It appears as though no callback was integrated for Dialog's onCancel event.

**Comment by jeroenransijn** [comment]
Was this in v4?

**Comment by jbwhitcombe** [comment]
Yep, for some reason onCancel isn't getting triggered.

**Comment by jeroenransijn** [comment]
@jbwhitcombe could you provide an example of your setup? I just tested this and it seems to be working?

![dialog cancel](https://user-images.githubusercontent.com/564463/47319865-ad451880-d604-11e8-9e14-02b2227f96f9.gif)

**Comment by jbwhitcombe** [comment]
Can confirm, I was secretly running 3.6.7. My apologies, it does work!
