### ISSUE TITLE
Checkbox isn't working inside a Dialog

### ISSUE THREAD

**Issue by ITforHome** [segmentio/evergreen#328]
Dear Evergreen-Team,
First of all, I would like to thank you for your hard work. I have long searched for a suitable UI framework for React, which I have now found. Thank you for that.

Currently I use the version v4.0.0-39
Unfortunately, the checkbox does not work inside a dialog. I can click the checkbox, but it remains empty. In the linked SandBox.io Project it works, but inside Chrome Version 69 or Safari, it's doesn't work, why?

[![Edit 4zz9rvv3l9](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4zz9rvv3l9)

<img width="468" alt="bildschirmfoto 2018-09-16 um 21 25 41" src="https://user-images.githubusercontent.com/27279514/45600081-1f6b8180-b9f7-11e8-8868-e11f5bd13b11.png">

- How can the problem be solved?
- Moreover, how can I use the component FormField with validation? (I haven't found anything yet)
- A third question: How can I set the autofocus to the first TextInputField? (I don't want the Cancel button in the top left in focus)

**Comment by jeroenransijn** [comment]
Hi @ITforHome. Thanks for giving Evergreen a try and posting your issue here. 

The checkbox is working for me in Chrome Mac OS X, but you should consider a controlled usage of it. Not sure why it's not working. Could you provide your system OS and confirm this behavior with a gif?

## Autofocus bug

It seems you have found a bug with the `autoFocus/autofocus` prop not being passed properly on the `TextInput` inside of the `TextInputField`. I recommend using `tabIndex={0}` for now until we get this fixed.

## No need to nest inside `FormField`

There is no need to nest `TextInputField` inside `FormField`. Take a look at my example here: https://codesandbox.io/s/m9opjm10qx
 

I am not getting the example to load glamor CSS properly and seeing this results in CodeSandbox. Which is something I need to take a closer look at:
![image](https://user-images.githubusercontent.com/564463/45648257-d827d400-ba7c-11e8-851c-33a7a1f810fb.png)

**Comment by ITforHome** [comment]
@jeroenransijn Thanks for your quick answer.
Currently I use MacOS Mojave 10.14 and Chrome Version 69.0.3497.100 (that's the last version of Chrome)

![checkbox_dialog_issue](https://user-images.githubusercontent.com/27279514/45649869-e1409180-bacc-11e8-8c7b-7392312672b5.gif)


## AutoFocus Bug
Where exactly do I have to insert the <code>tabIndex={0}</code> in my dialog so that the Cancel button is not in focus?

## FormFields
Thanks for your example Project on SandBox.io. But except for the import statement from FormField, I can't  find anything about FormField, Validation and ValidationMessages in the file. Can it be that you have linked me to another project?

I would be very happy if you could show me how I could add a formfield with validation and messages to my dialog

---

Yes, you have right. I don't know, why we have CSS Issues on SandBox.io. But this is the same file in my own Project in Visual Studio Code as Environment...

**Comment by jeroenransijn** [comment]
I have updated the CodeSanbox (https://codesandbox.io/s/m9opjm10qx) to show where to put `tabIndex={0}`
![image](https://user-images.githubusercontent.com/564463/45650099-11167780-ba82-11e8-8daa-c3b5dc36642c.png)

`FormField` is mainly a implementation detail, you often won't use it directly. `TextInputField` is a combination of `TextInput` and `FormField` already. Note that all components are presentational, and there is no out-of-the-box form validation — you will need to manually manage that in your application.

# TextInputField

The `TextInputField` component combines a `TextInput` with a label and optional
`description`, `validationMessage` and `hint`.


## Label and description

```jsx
<TextInputField
  label="Default text input field"
  description="This is a description."
  placeholder="Placeholder text"
/>
```

## A hint is under the text input

```jsx
<TextInputField
  label="Default text input field"
  hint="This is a hint."
  placeholder="Placeholder text"
/>
```

## Required text input field

```jsx
<TextInputField
  id="ids-are-optional"
  label="A required text input field"
  required
  description="This is a description."
  placeholder="Placeholder text"
/>
```

## Invalid field

```jsx
<TextInputField
  isInvalid
  required
  label="A required text input field"
  description="This is a description."
  validationMessage="This field is required"
/>
```

## Controlled usage

The `TextInputField` component works the same as using `input` directly.
Use `e.target.value` to get the value of the component on change. 

```jsx
<Component initialState={{ value: '' }}>
  {({ state, setState }) => (
    <TextInputField
      label="A controlled text input field"
      required
      description="This is a description."
      value={state.value}
      onChange={e => setState({ value: e.target.value })}
    />
  )}
</Component>
```

**Comment by jeroenransijn** [comment]
I think I know why the examples are not completely working — the `package.json` has v3 of Evergreen as a dependency:
![image](https://user-images.githubusercontent.com/564463/45650296-b5002300-ba82-11e8-8928-efc65a95ee77.png)

**Comment by ITforHome** [comment]
@jeroenransijn Thank you for your detailed answer. Only the question remains, why the checkbox doesn‘t work. Maybe you already have an idea for the cause?

**Comment by ITforHome** [comment]
@jeroenransijn Update: I solved the issue. I have forgotten to set a controlled usage for this. 
A last question, i don't want to create a new issue for that, because this is a little question and not a big problem... 

How can i set another TextColor on the Cancel Button in the Dialog Footer. I want to set the TextColor to grey and not to blue... But the Apperance "Minimal" should be kept, how can i do that?

**Comment by ITforHome** [comment]
@jeroenransijn For the FormValidation, i use the tutorial: ["Form Validation in React"](https://medium.com/code-monkey/client-side-form-validation-in-react-40e367de47ba) to implemente this. But i have trouble with that, to implemente this to my React-App. I am aware that it takes time to help me, but I would be very grateful for it because I have little knowledge about that. Because the files are too large to insert here, I created SandBox.io project. This is exactly the same project that I use myself:

[![Edit wozl0qmw6w](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wozl0qmw6w)

Could you help me, to solve my Problem? maybe you could use the completed form validationas an example of how to bring form validation and the evergreen UI together...

**Comment by ITforHome** [comment]
@jeroenransijn Update: I solved the Issues with the FormValidation... Do you want to use that as an example, how to use FormValidation with the Evergreen-UI `TextInputField` Component?

**Comment by jeroenransijn** [comment]
@ITforHome currently not possible to change the text color of a minimal button without a hack.

As for the form validation, It might be a useful example to have in codesandbox.io!

**Comment by jeroenransijn** [comment]
@ITforHome closing this since it seems you resolved your issue :)
