### ISSUE TITLE
[Feature Request] Update Native Select

### ISSUE THREAD

**Issue by ITforHome** [segmentio/evergreen#331]
Dear Evergreen-Team,
i really like the Components from Evergreen UI, but honestly, I don't like the design of the native select. In my view, this native element does not fit with the other components of the framework. I would like to bring the Design from the SelectMenu to the native Select. I would also create an option to put icons in front of a label, e.g. as Prop.

<img width="249" alt="bildschirmfoto 2018-09-19 um 21 11 59" src="https://user-images.githubusercontent.com/27279514/45775660-c3039e80-bc50-11e8-949c-ff82101aa8d7.png">

**Comment by jeroenransijn** [comment]
Hey @ITforHome, thanks for creating this issue! I believe there is still room for a NativeSelect alongside a themed on. In the design system we use the following design currently:

![image](https://user-images.githubusercontent.com/564463/47113425-dbde8000-d20d-11e8-99c9-617034a83681.png)

Although low-priority for us, I will keep this open!
