### ISSUE TITLE
Next.js Icons

### ISSUE THREAD

**Issue by Ketcap** [segmentio/evergreen#334]
Hello guys i'm using evergreen on next.js. But icons are not showing. Tried default examples from website.
If i need to do anything extra to work on next.js let me know i'm just a starter.

```
import Link from 'next/link';
import { Text, Icon } from 'evergreen-ui';
import classes from './style.scss';

export default (props) => (
	<header>
		<div>
			<Icon icon="add" color="default" />
		</div>
	</header>
)
```
Output : 
![slice](https://user-images.githubusercontent.com/7689820/45929986-58f13f00-bf59-11e8-8e36-b2eb1078c057.png)

Code : 
![screen shot 2018-09-23 at 5 51 53 pm](https://user-images.githubusercontent.com/7689820/45929988-65759780-bf59-11e8-9421-34745fdaf537.png)

if needed my next.config.js
```
const withSass = require('@zeit/next-sass')

module.exports = withSass({
	cssModules: true,
	cssLoaderOptions: {
		importLoaders: 1,
		localIdentName: "[local]___[hash:base64:5]",
	}
})
```

**Comment by jeroenransijn** [comment]
Hi @Ketcap thanks for putting in your issue! Are you using Evergreen v4? `evergreen-ui@next`? Are you seeing any error logs in the browser console?

**Comment by Ketcap** [comment]
Sorry, i forgot the check the version, now everything is fine icons are fine. I was using 3.x version and i was looking v4 documentation.
