### ISSUE TITLE
[v4] Alert icon default margin-top is causing a layout misalignment

### ISSUE THREAD

**Issue by markuso** [segmentio/evergreen#345]
I am using the latest Evergeen **v4** and the `Alert` component displays its icon misaligned due to a default `margin-top: 2px;` css applied to the icon wrapper. See screenshot below. The [examples](https://evergreen.segment.com/components/alert) on the documentation website do not have this flaw.

![image](https://user-images.githubusercontent.com/56903/46959195-76518e80-d069-11e8-8b00-91e333fa1e52.png)

The code used is exactly this:

```jsx
<Alert
  appearance="card"
  intent="danger"
  title={error.message}
  marginTop={20}
/>
```

It seems that [line 124](https://github.com/segmentio/evergreen/blob/c0d1b8a86a34db93ee6ad02a63d09939fdfa4a38/src/alert/src/Alert.js#L124) within the **Alert.js** code on v4 branch is what is causing this misalignment:

**Comment by mshwery** [comment]
Nice catch @markuso ! That would be a great PR, if you want to submit a quick fix against the `v4` branch!  🎉

**Comment by markuso** [comment]
Sure thing @mshwery — I will do that shortly then.

**Comment by markuso** [comment]
This ended up to be a problem when using `sanitize.css` or other CSS reset libraries that resets `svg` and other embed elements to have a `vertical-align: middle;` css rule. This clashes with Evergreen's icon/svg components in some cases like the Alert.

Either the icon/svg component should set its default `verticalAlign` to `initial` so it can be more reliable, or at least when used in places that was intended to be next to other elements, like inside the Alert component. It is always best to actually be sure to intentionally set any possible alignment related css rules that may have been set globally so components can work as expected, and independently from any css resets. What do you think?

I am not sure which direction the team would like to go, but I think I will leave this up to the core team. To see the issue and to test what I am talking about, just apply a global css rule to the svg element like so:

```css
svg {
  vertical-align: middle;
}
```
Then observe the Alert and toaster components to see the misalignment.

**Comment by mshwery** [comment]
I don't think the icons should rely on external style sanitizers/resets/normalizers to align properly.

@jeroenransijn thoughts?

**Comment by jeroenransijn** [comment]
We could add a explicit `vertical-align` property on icons if that is a easy fix. If not we can keep it as is. I believe Evergreen should work in most environments with resets if it's an easy fix on our side.

**Comment by mshwery** [comment]
I think this depends on how we expect the icon to behave when the text wraps? Should the icon always be center-aligned vertically? Or should it match _the line-height_ of the first line of text? How would consumers override this behavior to meet their needs?

**Comment by markuso** [comment]
If I may pitch in here please. Since Evergreen does concern itself with the layout of the Alert component, then it should have a specific `vertical-align` css rule on its icon. This is because in the Alert component, the wrapper element to the icon has margin related props to adjust the layout of the icon accurately to the adjacent text. It is important so global css rules don't impact or leak into what Evergreen's intention is for the component.

May be it is possible to set svg icons to have `vertical-align: middle;` as it seems to be the most common default out there, and rework the Alert layout to now take into consideration that change by updating the margins or what have you on its icon wrapper. Perhaps there is where it should be overridden to be `vertical-align: baseline;` or similar as needed.

There might be other areas that it could impact down the road as well if no specific `vertical-align` is added. I think this is a good opportunity to just be aware of global alignment css rules that may conflict if not set intentionally. The point is to keep things predictable where Evergreen components are concerned.

Please only consider what I am sharing as a suggestion/comment and the team knows best on how they would like this to behave.
