### ISSUE TITLE
Missing Firefox browser prefix for appearance causing duplicate dropdown arrows

### ISSUE THREAD

**Issue by coreybruyere** [segmentio/evergreen#368]
https://github.com/segmentio/evergreen/blob/2a2f83393d0b5dbb658a922c233b88cbb081803e/src/select/src/SelectField.js#L88

Include 
```
-moz-appearance: none
```

**Comment by jeroenransijn** [comment]
The `appearance` is different in that context. However we do need to remove the system default.

![image](https://user-images.githubusercontent.com/564463/47323948-c9e84d00-d612-11e8-9f7f-c3a501aa0229.png)

**Comment by coreybruyere** [comment]
Ah I see, didn't look into styles all that much. Where are those styles be called from (appearance)?

**Comment by mshwery** [comment]
BTW I think I have a fix for this in my PR... #399

**Comment by jeroenransijn** [comment]
@mshwery fixed in his PR 👍
