### ISSUE TITLE
yellow solid fill is using undefined palette color

### ISSUE THREAD

**Issue by minheq** [segmentio/evergreen#371]
Per description yellow solid fill is using undefined palette color. Found this issue when converting the code to TypeScript

https://github.com/segmentio/evergreen/blob/abe2b007cc55740d7a0fd1348905086fa5e7d6eb/src/theme/src/default-theme/foundational-styles/fills.js#L27

https://github.com/segmentio/evergreen/blob/abe2b007cc55740d7a0fd1348905086fa5e7d6eb/src/theme/src/default-theme/foundational-styles/palette.js#L32-L37

**Comment by jeroenransijn** [comment]
Nice find!

**Comment by prateekgoel** [comment]
@jeroenransijn So let me change it to dark and submit a PR.
