### ISSUE TITLE
Question: How to use React Router 'Link'

### ISSUE THREAD

**Issue by karltaylor** [segmentio/evergreen#376]
Hello 👋

Love the framework, just wondering what the best way is to implement a `<Link>` component from `react-router-dom` and use the `<Link>` component from `evergreen-ui`?

**Comment by jeroenransijn** [comment]
Hey @karltaylor, you can use the `is` prop for that:

```javascript
import { Link as ReactRouterLink } from 'react-router'
import { Link } from 'evergreen-ui'

const EvergreenReactRouterLink = props =>
  <Link is={ReactRouterLink} {...props} />
```
