### ISSUE TITLE
v5 Roadmap

### ISSUE THREAD

**Issue by jeroenransijn** [segmentio/evergreen#379]
## Committed

* [x] Upgrade Downshift to v3 #356 
* [x] Change `<Icon icon="search" />` to `<SearchIcon />` to support tree-shaking

## Potential

* Add `size` prop #221
* Continue working on theming support and `v4-create-theme`.
* Increase font sizes throughout Evergreen (13–14px)
* Focus traps for modal dialogs
* Upgrade `SelectMenu` to use `Downshift` and standardize interfaces among `Autocomplete`

## Upgrade path

We will to minimize breaking changes as much as possible and optimize for deprecations.

**Comment by jeroenransijn** [comment]
@vadimdemedes follow along theming on the new `v5-create-theme` branch!

**Comment by rejifald** [comment]
I'd like suggest:
- Datepicker
- Grid system
- Pagination
- Divider
- Hero in Bulma or Jumbotron on Bootstrap (with full-height version)
- Progress
- Tree view

**Comment by tj** [comment]
Themeing would be great. Personally I would have _only_ structural styles by default—just the basics required for layout—leaving any subjective stuff up to custom styles. If this were done, this would probably be the first extensible suite of UI components, they always seem to have very opinionated styles and themeing systems, which seems entirely unnecessary.

I'd prefer the use of regular CSS for the custom side, no crazy override system required, and IMO CSS is perfectly fine without css-in-js, just name the classes to match the components.

**Comment by mshwery** [comment]
BTW, these is some basic theming support today in v4, it's just not very well documented.

>Does this mean, as far as v5 is concerned, our ability to customize will only be from some global top level, instead of directly passing style={{}} directly to a component?

@krainboltgreene no, I don't think we intend to take away the ability to directly manipulate `style` on components. The intent for improved theming is to make it easier to set site-wide styles through some context (or similar pattern).

**Comment by tj** [comment]
Brought it up a bit on https://github.com/segmentio/ui-box/issues/25, but I guess it's more related to Evergreen.

I'd really like to see a scoped style solution personally (shadow dom), `<Box>` is a cool primitive but glamor is really restrictive and unintuitive, at least coming from someone who likes regular CSS. If a theme could just swap in new scoped styles for a given component, and said component used classes it would be much more approachable IMO.

**Comment by tj** [comment]
wouldn't mind if most of it was themeable with regular CSS, I'm porting over my typography and whatnot but it takes quite a while to move it into js-isms. CSS vars have decent adoption these days too, might be more portable to have the bulk of vars/styling in CSS so you can use it in marketing sites etc as well

**Comment by mshwery** [comment]
Closing this as v5 has shipped but we will definitely consider some of these remaining items in future versions!

In v5 we did ship:
- 100% tree-shakable icons (or BYO-icons if you want)
- Smaller bundle size (shaved off about ~100kb minified, though still room for improvement here!)
