### ISSUE TITLE
Remove deprecated React lifecycle methods

### ISSUE THREAD

**Issue by prateekgoel** [segmentio/evergreen#386]
While going through the codebase, it came to my notice that we are using React lifecycle methods that will be deprecated soon by React team and will no longer be supported in future. i.e. `componentWillMount`,
`componentWillRecieveProps` and `componentWillUpdate`

Are there any plans to switch to new lifecycle methods or other alternatives?
I would like to contribute to this.

**Comment by mshwery** [comment]
I think we may need to make considerations for our React version support before deciding on how to handle deprecated lifecycle methods.

Given that our target is `react@^16.3.0` I think we could safely migrate to `static getDerivedStateFromProps` and use `componentDidMount` or `componentDidUpdate` in other cases.

Thoughts @jeroenransijn ?

**Comment by prateekgoel** [comment]
@jeroenransijn Let me know if I can be helpful in this.

**Comment by jeroenransijn** [comment]
@prateekgoel be my guest if you want to take a stab at it.

These 4 files need to be updated to `static getDerivedStateFromProps`:

![image](https://user-images.githubusercontent.com/564463/47319639-0c565d80-d604-11e8-93e7-ac8051090b92.png)

`componentWillUpdate` is used once in `ScrollbarSize.js`

**Comment by prateekgoel** [comment]
Sure @jeroenransijn :) I will start working on this today. Thank you.

**Comment by prateekgoel** [comment]
Seems like someone submitted a PR!
