### ISSUE TITLE
Menu examples are broken

### ISSUE THREAD

**Issue by andrwh** [segmentio/evergreen#389]
https://evergreen.segment.com/components/menu/

**Comment by prateekgoel** [comment]
Also, https://evergreen.segment.com/components/table is broken with the same error.
I believe this is due to the change here https://github.com/segmentio/evergreen/commit/a1f477ce547b57ff1b2634e5550a751468c40b93

**Comment by fraindz** [comment]
I can work on this.

**Comment by fraindz** [comment]
Already fixed under #370
