### ISSUE TITLE
Autocomplete uses item string as key

### ISSUE THREAD

**Issue by atombender** [segmentio/evergreen#406]
If you create an `Autocomplete` with items that have identical "item strings", then you will get a React warning about duplicate keys, because the component simply uses the string as the key:

https://github.com/segmentio/evergreen/blob/abce343d186f371322cbf8de34199bd3f58c290b/src/autocomplete/src/Autocomplete.js#L162

This seems naive. There are situations where two items may have the same string for perfectly good reasons. For example, you may have users who have the same full name, but are backed by two different records, each with its own unique ID. ~~They may be rendered differently via `renderItem`, too. It shouldn't be necessary for the parent component to generate "fake unique" strings just to work around this issue.~~ I just realized that since `renderItem` doesn't have access to the original item, just the string, you can't provide a unique string with `itemToString` since it's used to _display_ the item.

Version 4.1.1.

**Comment by jeroenransijn** [comment]
Thanks for reporting @atombender !

**Comment by mshwery** [comment]
Closing as the issue is very stale.
