### ISSUE TITLE
Autocomplete renderItem prop does not support arbitrary rendering

### ISSUE THREAD

**Issue by atombender** [segmentio/evergreen#407]
Consider this:

```jsx
const fruits = [
  {id: "banana", label: "Banana, yum!"},
  // ...
];

// ...

<Autocomplete items={fruits}
  itemToString={item => (item ? item.label : '')}/>
```

Let's say we want to render a banana icon next to bananas by checking the `id` against an icon list. `Autocomplete` does support a `renderItem` prop, but it only receives baked props that look like this:

```json
{
  "children": "Banana",
  "id": "downshift-0-item-0",
  "isHighlighted": false,
  "isSelected": false,
  "key": "Banana",
  "style": {"position": "absolute", "top": 0, "left": 0, "width": "100%", "height": 32}
}
```

There's no item here — all you get is the string returned by the `itemToString` function.  From what I can tell, there's no way to provide a custom rendering here that has access to the item. It's actually extremely limited what you can do with `renderItem` if you want to do this cleanly.

It's worth pointing out that the props sent to `renderItem` are in fact undocumented, and it's unclear that it's expected to use an `AutocompleteItem`; the interface is low-level and somewhat tighly coupled.

I think there's an opportunity here to distinguish between rendering the container around the item (which will have things like position, highlight/select and so on) and the contents. Consider a hypothetical `renderItemContents` prop:

```jsx
<Autocomplete items={fruits}
  itemToString={item => (item ? item.label : '')}
  renderItemContents={item => (
    <div>
      <FruitIcon fruit={item}/> <strong>{item.label}</strong>
    </div>
  )}
/>
```

This renderer doesn't need to know about anything (selection, position, etc.), just how to render the actual item.

**Comment by jeroenransijn** [comment]
@atombender thanks for creating the issue! This seems like an interesting proposal. There are a ton of things about Autocomplete and SelectMenu that I would love to improve and change, but haven't had the found the time for it yet. Feel free to take a stab at it if you want.

**Comment by mshwery** [comment]
Closing as the issue is quite stale.
