### ISSUE TITLE
createAppearance() only accepts whitelisted properties, key 'WebkitAppearance' is not whitelisted in whitelist: 

### ISSUE THREAD

**Issue by churcho** [segmentio/evergreen#408]
I am getting the error in my codebase. I have just included this into an already existing UI application since I want to only use bits and pieces of it. Is that possible or it needs a complete buy in? The page I am using it on has pieces of `reactstrap` UI as well. Could this be the cause?

**Comment by mshwery** [comment]
Resolved by https://github.com/segmentio/evergreen/pull/405
