### ISSUE TITLE
Create MatchMedia component for supporting responsive layouts.

### ISSUE THREAD

**Issue by aliakakis** [segmentio/evergreen#409]
By using the Windows objects [Match media](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia) you could hide/show specific components based on media queries.

For example:
```jsx
<MatchMedia sm md>
   <div />
</MatchMedia>
```
Where "sm", "md" would be props as follows e.g. sm = window.matchMedia("(min-width: 768px)").matches.

The user could pass an object with custom media queries checks but will have to provide the new media query mapping.

**Comment by jeroenransijn** [comment]
I used [react-component-queries](https://github.com/ctrlplusb/react-component-queries#readme) that pretty well for me. Not sure if this is something we will add to Evergreen.

**Comment by aliakakis** [comment]
Something simpler actually :) Below I have written something simpler.

```javascript
<MatchMedia mediaWidth={["(min-width: 768px)"]}>
          <Checkbox
            id="check_1"
            label="Hello World!"
            checked={isChecked}
            onChange={() => this.setState({ isChecked: !isChecked })}
          />
```

```javascript
import React, { Component } from "react";
import PropTypes from "prop-types";

export default class MatchMedia extends Component {
  constructor(props) {
    super(props);
    this.state = {
      isMatch: false
    };
  }

  componentDidMount() {
    const { handleMatchMediaOnResize } = this;

    handleMatchMediaOnResize();

    window.addEventListener("resize", handleMatchMediaOnResize, false);
  }

  handleMatchMediaOnResize = () => {
    const { mediaWidth } = this.props;

    mediaWidth.forEach(width => {
      this.setState({ isMatch: window.matchMedia(width).matches });
    });
  };

  render() {
    const { children, tag, className } = this.props;
    const { isMatch } = this.state;
    const Component = tag;

    return isMatch && <Component className={className}>{children}</Component>;
  }
}

MatchMedia.defaultProps = {
  tag: "div",
  className: "",
  mediaWidth: []
};

MatchMedia.propTypes = {
  tag: PropTypes.string,
  className: PropTypes.string,
  mediaWidth: PropTypes.arrayOf(PropTypes.string)
};
```

**Comment by jeroenransijn** [comment]
@aliakakis yeah this looks great! Have you considered making this a standalone package?

**Comment by aliakakis** [comment]
@jeroenransijn Thank you. I have considered it including it with my other package [react-templates-components](https://www.npmjs.com/package/react-templates-components) but it is very small therefore a gist would be best. Feel free to use it :-)

**Comment by jeroenransijn** [comment]
Awesome, that is useful! This looks great, since we won't add this to Evergreen right now I will close this issue.
