### ISSUE TITLE
[v4] Popover spills out of viewport

### ISSUE THREAD

**Issue by 7c78** [segmentio/evergreen#417]
First, thank for awesome work!

**Problems**

The following snippet of `Positioner` component cause Popover to spill out of viewport.

```javascript
const viewportHeight = document.documentElement.clientHeight + window.scrollY
const viewportWidth = document.documentElement.clientWidth + window.scrollX
```

See the picture I capture from [https://evergreen.segment.com/components/popover](https://evergreen.segment.com/components/popover).

![issue](https://user-images.githubusercontent.com/42330300/47839540-a462fc80-dde5-11e8-8c96-6a1bec701eb6.PNG)

**Comment by 7c78** [comment]
In `getPosition.js`, can

```javascript
// Push rect to the left if overflowing on the right side of the viewport.
if (rect.right > viewport.width - viewportOffset) {
  const delta = Math.ceil(rect.right - (viewport.width - viewportOffset))
  rect.left -= delta
  rect.right -= delta
}
```
be changed to

```javascript
// Push rect to the left if overflowing on the right side of the viewport.
if (rect.right > viewport.width - viewportOffset) {
  const right = viewport.width - viewportOffset;
  rect.left = right - rect.width
  rect.right = right
}
```
I'm just curious.

**Comment by jeroenransijn** [comment]
@7c78 could you screenshot the entire screen? I am curious if there was enough space at the top.

**Comment by 7c78** [comment]
@jeroenransijn  It is enough space at top.

![Uploading issue.PNG…]()

**Comment by 7c78** [comment]
@jeroenransijn  It is enough space at the top.

![issue](https://user-images.githubusercontent.com/42330300/47887574-c35ba000-de72-11e8-8ea2-57a616fa1e62.PNG)

**Comment by jeroenransijn** [comment]
Yeah that is weird, this used to work differently/correctly. I think there is a PR that got in recently that might have accidentally changed this. Do you think you could put in a PR for this?

**Comment by 7c78** [comment]
I am very willing!

**Comment by 7c78** [comment]
@jeroenransijn I have submitted a PR

Btw, I think `getPosition.js` is using a wrong formula to calculate `spaceBottom` and `spaceTop`. Please take a look at the attached picture.

What do you think?
![b](https://user-images.githubusercontent.com/42330300/48058689-9c41fd00-e1e9-11e8-8a33-0b05f0918091.png)
