### ISSUE TITLE
Maybe the Pagination  component is needed

### ISSUE THREAD

**Issue by tiyee** [segmentio/evergreen#418]
as the title said ~

**Comment by mshwery** [comment]
Hey @tiyee ! Can you elaborate on what your use case is? What type of pagination? How would you envision consuming it?

We've definitely thought about whether this belongs in Evergreen, or not. Interested in hearing your thoughts!

**Comment by tiyee** [comment]
> Hey @tiyee ! Can you elaborate on what your use case is? What type of pagination? How would you envision consuming it?
> 
> We've definitely thought about whether this belongs in Evergreen, or not. Interested in hearing your thoughts!

it is a standard component of data-view page.for example, in your blog article list page,it can not show all the articles in one page,so you need pagination.

How to design ? maybe could learn from others' practices ,like [ant.design/components/pagination/](https://ant.design/components/pagination/)
