### ISSUE TITLE
Dialog from menu button closes dialog on click inside

### ISSUE THREAD

**Issue by ludviglundgren** [segmentio/evergreen#421]
Hello! Nice set of components!

I have a menu with a button that triggers a dialog. The trigger works as expected but when I click inside the dialog everything closes.

Version: 4.3.0

https://codesandbox.io/s/llr11q8qll

Code from stories/docs examples.

Tested with both Chrome and Firefox but I suppose it's not browser related but rather how the clicks are handled.

Any solutions to this or does this not simply work as it's built at the moment?

Thanks in advance!

**Comment by ludviglundgren** [comment]
Okay, so I tried that, but don't really know if it's exactly how you meant. But it's the same result..

@mshwery could you take a look maybe? https://codesandbox.io/s/q9n86z8o66

Some other solution? Or use another component which does not use portals..?

**Comment by mshwery** [comment]
Hm, no that's exactly what I was thinking of. This looks like a bug (nice find!).

The menu is closing and puts focus back to the initial activeElement because it's listening for clicks outside. Does this sound right to you @jeroenransijn ?

**Comment by ludviglundgren** [comment]
Have you had a chance to look at it @jeroenransijn ?

**Comment by mshwery** [comment]
Here's an example – the problem was having everything in the same Popover. https://codesandbox.io/s/forked-menu-example-hbvy7
