### ISSUE TITLE
create-package scripts don't execute node scripts on windows

### ISSUE THREAD

**Issue by gkemp94** [segmentio/evergreen#429]
This might be a windows specific issue, but running yarn create-package etc. doesn't do anything unless I edit the package and add node before the script file in question. 

```js
 "create-package": "node ./tools/create-package.js",
 "create-package:components": "node ./tools/create-package-components.js",
```

Version: Master Branch
Operating System: Windows 10, Yarn 1.12, Node 8.11.2

**Comment by jeroenransijn** [comment]
Thanks for posting your issue! I am not quite sure what would be required to make this work for Windows. `#!/usr/bin/env node` is present at the top of the file—do you know what is required to make this work on Windows?
