### ISSUE TITLE
The button of FilePicker submits forms

### ISSUE THREAD

**Issue by SpartanPlume** [segmentio/evergreen#433]
**Issue:** If a `<FilePicker>` is in a `<form>`, the button of the `FilePicker` will submit the form
**Steps to reproduce:** Having a `<FilePicker>` in a `<form>` and click on the button of the `FilePicker`
**Version:** 4.3.0
**Browser name and version:** Firefox 63.0.1/ Google Chrome 70.0.3538.77
**Operating system:** Windows 10

**Link to project:** https://github.com/SpartanPlume/evergreen-minimal-project
**Expected:** Popup to choose the file
**Actual:** Submit the form

**Possible fix:** I don't know how ui-box works but maybe adding `type="button"` to the button would work ?

**Comment by jeroenransijn** [comment]
Great issue description! Looping @Rowno in for any ideas since he authored the component.

**Comment by Rowno** [comment]
Looks like we just need to add `type="button"` here: https://github.com/segmentio/evergreen/blob/b4402881a463a0e1a29346b8d65311454c6830ad/src/file-picker/src/FilePicker.js#L125

**Comment by kcjpop** [comment]
I think to make `type="button"` by default in `<Button>` would be a better solution, as it prevents this unexpected behavior in all other components using `Button` internally.

**Comment by mshwery** [comment]
>make `type="button"` by default in `<Button>`

@kcjpop while I agree with that default, it's technically a breaking change. Some consumers may actually rely on the current behavior to submit their forms.

Adding it to just the filepicker button would be a safe and simple alternative.

**Comment by kcjpop** [comment]
@mshwery I see your point :+1: Any chance this new behavior could be in the next major version?
