### ISSUE TITLE
Allow passing props for content container in Dialog

### ISSUE THREAD

**Issue by kcjpop** [segmentio/evergreen#434]
My specific use case is that I need to make a dialog as shown below.

![image](https://user-images.githubusercontent.com/172503/48199703-a25ce880-e365-11e8-846a-13499b2031f5.png)

Yet at the moment Dialog has a 16px padding by default, so I wonder if we can introduce a new prop `contentContainerProps` to make it easier to customize? The change could be:

```js
<Pane
  data-state={state}
  display="flex"
  overflow="auto"
  padding={16}
  flexDirection="column"
  minHeight={minHeightContent}
  {...contentContainerProps}
>
  <Pane>{this.renderChildren(close)}</Pane>
</Pane>
```

Then as a user,

```js
<Dialog
  hasFooter={false}
  hasHeader={false}
  contentContainerProps={{padding: 0}}
>
  <Text>Hello</Text>
</Dialog> 
```

**Comment by jeroenransijn** [comment]
I love seeing how you used Evergreen for your project! This sounds reasonable, any chance you create a PR for this?

**Comment by kcjpop** [comment]
Evergreen is the soundest UI framework I have seen so far. Just so much in love with compiled atomic CSS classes and UI box primitives :smile: 

Definitely. I will submit a PR soon :wink:
