### ISSUE TITLE
Ghost buttons dont exist

### ISSUE THREAD

**Issue by Winni-** [segmentio/evergreen#435]
Version: 4.3.0
Buttons have no "ghost" and 'ghostBlue" appearance.
code:
![image](https://user-images.githubusercontent.com/3993929/48218995-54afa280-e39c-11e8-9563-06ebda381175.png)
result:
![image](https://user-images.githubusercontent.com/3993929/48219004-5d07dd80-e39c-11e8-9135-fa9e15b9da25.png)
console:
![image](https://user-images.githubusercontent.com/3993929/48218982-4b263a80-e39c-11e8-9d20-6e7d48ab0dec.png)

**Comment by mshwery** [comment]
Use `appearance="minimal"`

`ghost` was removed in v4.

**Comment by jeroenransijn** [comment]
Take a look at #200 for more information on migrating components.
