### ISSUE TITLE
Search Input label prop

### ISSUE THREAD

**Issue by lndgalante** [segmentio/evergreen#440]
Should this component be able to have a `label` prop ? Like the TextInputField?

**Comment by mshwery** [comment]
Hey @lndgalante ! 

I don't think `SearchInput` itself should have one. But you have identified a missing component: `SearchInputField` :)

I think we are missing a few, but most of the form input components come along with a more enhanced version called `*Field`. These components are wrappers around the main input component to provide things like labels, error messaging, input descriptions, hint text, etc.

**Comment by lndgalante** [comment]
Great thanks for the info @mshwery @jeroenransijn 👍
