### ISSUE TITLE
Combobox breaks when input is blank

### ISSUE THREAD

**Issue by giocodes** [segmentio/evergreen#447]
Great job on the library! I really like the approach and decision you've made. 👍 
Here's something I found while using the combobox. 

- Issue 
Combobox breaks when the input is cleared.

- Steps to reproduce
1. Go to https://evergreen.segment.com/components/combobox
2. Scroll to the section "Custom items and default selected item"
3. Select the text on the input and delete it

- Versions
"evergreen-ui": "^4.7.0"

- Screenshots.
![evergreen-combobox](https://user-images.githubusercontent.com/19365690/48630657-6ab3f900-e982-11e8-8108-d51933039b08.gif)

- Expected.
User can leave the value blank.

- Actual.
The component breaks throwing an error:  
`TypeError: Cannot read property 'label' of null`

- Link to your project.
N/A

- Browser name and version.
Chrome 70

- Operating system.
Mac OS

**Comment by kcjpop** [comment]
I think it's due to that particular snippet, where `itemToString` doesn't handle the case of empty selected item well. A working demo: https://codesandbox.io/s/l5jr9mq3y7

**Comment by vadimdemedes** [comment]
@giocodes Thanks for reporting, we'll look into it!

**Comment by RetWolf** [comment]
I believe this issue has been resolved by https://github.com/segmentio/evergreen/blob/master/src/autocomplete/src/Autocomplete.js#L114
Can we close this issue?

cc @mshwery

**Comment by mshwery** [comment]
Yep! This should be resolved.
