### ISSUE TITLE
IconButton is not inline

### ISSUE THREAD

**Issue by atombender** [segmentio/evergreen#449]
`IconButton` ends up with `dspl_flex`, which makes it a block element, whereas `Button` has `dspl_inline-flex `.

This is inconsistent, and means every `IconButton` needs to be wrapped in a `<span style="display: inline-block">` or similar in order to be used inline.

**Comment by mshwery** [comment]
@atombender note: you can simply add `display="inline-flex"` directly to the `IconButton` for now.

**Comment by atombender** [comment]
Thanks! Where is the documentation for that?

**Comment by mshwery** [comment]
https://evergreen.segment.com/components/button

Anything that says 
>This component composes `ui-box`

will benefit from all the same styling props that `ui-box` provides.

**Comment by atombender** [comment]
Right, but there's no link that in the documentation. You might want to link [here](https://github.com/segmentio/ui-box) and ideally integrate that into the documentation.

**Comment by mshwery** [comment]
You're right – each spot that has that comment could link out. We do cover it a bit in the Intro: https://evergreen.segment.com/get-started/introduction

**Comment by cstrat** [comment]
I've just run into this inconsistency too. Any reason why `IconButton` can't share the same display type as `Button` or `BackButton` or `TextDropdownButton`... it is the odd one out.

I'm fine if there is a reason, maybe explain the reason in the documentation. It doesn't mention there either.
