### ISSUE TITLE
Combobox does not scroll to selected item

### ISSUE THREAD

**Issue by 7c78** [segmentio/evergreen#450]
Steps to reproduce:

1. Select an item from combobox.
2. Open combobox by click toggle button.

See the attachment! Do you need a PR?

![bug](https://user-images.githubusercontent.com/42330300/48662567-52dd9180-eab6-11e8-975f-0ef256a0bae1.gif)

**Comment by mshwery** [comment]
This sounds like a nice feature to add! Thanks for the suggestion @7c78, and yes – PRs are definitely welcome!! 👍

**Comment by ukita** [comment]
Can I work on this? 👋

**Comment by vadimdemedes** [comment]
@ukita of course!

**Comment by jongsue** [comment]
Sorry @ukita, If you’re working on this
