### ISSUE TITLE
Text in button can't be centered

### ISSUE THREAD

**Issue by agusnavce** [segmentio/evergreen#455]
If i have a `button` that is larger than the average, i would expect to be able to center the text of the button with a property like `align-items`. But this is not the current behavior.

It's is possible to include this feature, to align the text in a button. Maybe i'm not aware of a property for this or i am using it wrong. But it would be cool to have this.

**Comment by mshwery** [comment]
`justifyContent="center"`

Buttons are flex containers by default, but you can change that as well: `display="inline-block"` (or any other valid display value).

**Comment by agusnavce** [comment]
Thanks for the response.
