### ISSUE TITLE
SelectMenu close on click

### ISSUE THREAD

**Issue by andrwh** [segmentio/evergreen#456]
Would love the ability to close the SelectMenu when an option is clicked

**Comment by robphoenix** [comment]
Not stale. :smiley_cat: 
Would be good to hear any opinion from the maintainers, whether this is a possible consideration.

**Comment by mshwery** [comment]
Sounds like a good addition! If y'all want to take a stab at a PR to implement this, I would be happy to review.  If not, we can add it to the docket.

// cc @solon-aguiar

**Comment by robphoenix** [comment]
I'll take a look at opening a PR for this, though I'm new-ish to React so it may take a wee while to get my round what needs to be done where. Making no promises.
