### ISSUE TITLE
Table Documentation: SearchHeaderCell takes incorrect arguments

### ISSUE THREAD

**Issue by ncammarata** [segmentio/evergreen#457]
Hi Evergreen Team,

It looks like the props in this example need to be updated [here](https://evergreen.segment.com/components/table/). Instead of taking the event, it looks like onChange takes the new textbox value.

![image](https://user-images.githubusercontent.com/204989/49054894-a896f580-f1aa-11e8-98be-acf73cdb01b6.png)

Thanks!

**Comment by mshwery** [comment]
This is resolved in the latest docs. Thanks!
