### ISSUE TITLE
Large bundle size with webpack v4

### ISSUE THREAD

**Issue by epitaphmike** [segmentio/evergreen#458]
I may be missing something, but the only way I was able to get the bundle size own in `v4` was to import the components like this: `import Pane from 'evergreen-ui/esm/layers';`.

Also, why is @blueprintjs a dependency, I am not using it at all in the components I am importing and it is still a part of my bundle.

<img width="734" alt="screen shot 2018-11-27 at 2 39 44 pm" src="https://user-images.githubusercontent.com/677832/49106886-5c06f500-f252-11e8-991d-10d82cda4a8d.png">
<img width="567" alt="screen shot 2018-11-27 at 2 40 44 pm" src="https://user-images.githubusercontent.com/677832/49106936-73de7900-f252-11e8-96d9-5f5acc93e1ba.png">

Unfortunately this doesn't do anything about `evergreen-ui/esm/icon/Icon.js`. It still contains all of `@blueprintjs/icons`

I had to edit the Icon.js file and do the same thing to reduce the bundle. 

<img width="788" alt="screen shot 2018-11-27 at 2 36 06 pm" src="https://user-images.githubusercontent.com/677832/49106809-28c46600-f252-11e8-9deb-d8a48ed9fe44.png">
<img width="747" alt="screen shot 2018-11-27 at 2 35 54 pm" src="https://user-images.githubusercontent.com/677832/49106810-28c46600-f252-11e8-9fb5-8c9f9f34913a.png">

_Originally posted by @epitaphmike in https://github.com/segmentio/evergreen/issues/311#issuecomment-442190755_

**Comment by dericgw** [comment]
@epitaphmike Can you paste the Webpack output for a build when importing the components the "normal" way and also the output when using the `esm` modules? I trust the Webpack output more than the VS Code Import Cost extension.

As far as the `@blueprint` dependencies, you can see [here](https://github.com/segmentio/evergreen/blob/master/package.json#L43) that this project uses the Blueprint icons.

**Comment by mshwery** [comment]
For the icons, we may need to fork `@blueprint` because [it doesn't seem like they are investing in tree-shaking support any time soon](https://github.com/palantir/blueprint/pull/2356).

As for the rest of evergreen, it should be tree-shakable. @dericgw is right – the webpack output will be the best way to diagnose your bundle size issues.

**Comment by Rowno** [comment]
Cross posting from #311:

I don't think the VS Code Import Cost plugin does tree shaking, it just traces all the files imported from the file you imported. To see the real tree shaken size you should use the [webpack-bundle-analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer).

As for the icons size issue, I'm currently working on tree shaking support for the icons. In Evergreen v5 you'll import individual icons directly instead of referencing them via a string, which will allow Webpack remove almost all of the icons (since less than 5% of them are used internally).

For example, this:
```jsx
import { Icon } from 'evergreen-ui'
<Icon icon="cross" />
```
Will become this:
```jsx
import { CrossIcon } from 'evergreen-ui'
<CrossIcon />
```

**Comment by epitaphmike** [comment]
@Rowno Attached is a screenshot of the evergreen-ui bundle from the webpack-bundle-analyzer

I am using evergreen in 3 files with the following imports.
`import { Popover, Pane, Switch, Text, Button, Select } from 'evergreen-ui';`
`import { Pane, Dialog, Text } from 'evergreen-ui';`
`import { toaster } from 'evergreen-ui';`

<img width="664" alt="screen shot 2018-11-28 at 10 40 51 am" src="https://user-images.githubusercontent.com/677832/49163068-37665800-f2fa-11e8-8710-1000cceabd92.png">

**Comment by epitaphmike** [comment]
This is the bundle with individual imports
eg.
```
import Popover from 'evergreen-ui/esm/popover';
import Pane from 'evergreen-ui/esm/layers';
import Switch from 'evergreen-ui/esm/switch';
import Text from 'evergreen-ui/esm/typography';
import Button from 'evergreen-ui/esm/buttons';
import Select from 'evergreen-ui/esm/select';
```
<img width="573" alt="screen shot 2018-11-28 at 10 48 48 am" src="https://user-images.githubusercontent.com/677832/49163550-52859780-f2fb-11e8-94b2-ad333196be31.png">

**Comment by Rowno** [comment]
I'm created this reduced test case that proves that Webpack's tree shaking works on Evergreen. I would make sure that you're using Webpack 4 and that it's running in production mode. Obviously the icons still need to be made tree shakable though.

https://github.com/Rowno/evergreen-tree-shaking

![image](https://user-images.githubusercontent.com/605501/49178513-c8423100-f304-11e8-9988-1f8f500eb2d4.png)

[evergreen-tree-shaking.zip](https://github.com/segmentio/evergreen/files/2626407/evergreen-tree-shaking.zip)

**Comment by epitaphmike** [comment]
@Rowno I appreciate your assistance on this and your repo. Unless something is not configured properly on my end I am not understanding why my builds aren't the same as yours. I'll chip away at this a bit more and post my results. Thanks again for your help.

**Comment by Rowno** [comment]
I noticed that Webpack doesn't tree shake in development mode if that helps.

**Comment by epitaphmike** [comment]
I have found the issue. I forked the repo and added React to make this a more real life example.

This is the fork with the `master` branch just adding `babel-preset-react`
https://github.com/epitaphmike/evergreen-tree-shaking/tree/master
`presets: ['react']`

This is the fork with the `with-preset-env` branch adding `babel-preset-react` and `babel-preset-env`
https://github.com/epitaphmike/evergreen-tree-shaking/tree/with-preset-env
`presets: ['env', 'react']`

When adding the `babel-preset-env`, it seems tree shaking no longer works.

After doing some more digging, if I add `{modules: false}` to the env preset, all is back to normal.
https://github.com/epitaphmike/evergreen-tree-shaking/tree/with-preset-env-modules-false
`presets: [['env', { modules: false }], 'react']`

**Comment by epitaphmike** [comment]
I am at a total loss..... But from the looks of it, it is not an evergreen-ui issue. Thanks for the help

<img width="1081" alt="screen shot 2018-11-28 at 6 14 02 pm" src="https://user-images.githubusercontent.com/677832/49188665-95666000-f339-11e8-9023-deb5fe64eacc.png">

**Comment by epitaphmike** [comment]
I almost gave up.....
But for anyone who comes across this in the future, 

Make sure you don't have a `.babelrc` file overwriting your webpack config.

The `.babelrc` file had no `{ modules: false }`

```
{
  "presets": ["env", "react"],

  "plugins": ["transform-class-properties", "transform-object-rest-spread"]
}
```

**Comment by jasonbarry** [comment]
For those still following along, [this solution](
https://github.com/palantir/blueprint/issues/2193#issuecomment-453326234) helped me reduce the footprint of the iconSvgPaths in produciton. A bit of a PITA to maintain but IMO worth the cost in savings.

**Comment by tj** [comment]
😢 definitely huge haha, I like [Feather](https://feathericons.com/)'s icons better anyway personally, leaving them out would be nice

**Comment by epitaphmike** [comment]
I've been using [icongr.am](https://icongr.am/) to test icons first, then once I like what I have chosen, I convert them into icon components. It has kept my bundle size down tremendously.

**Comment by mshwery** [comment]
Hm, yeah I think the right away to handle this would be to extract the icons from the package. We can provide some defaults that are used internally by evergreen components (which we would probably allow you to swap out with your own).

If we could get tree-shaking though... that would largely solve the problem.

**Comment by tj** [comment]
would be nice if it were light enough to use for marketing sites as well as apps, could be a pain to strip all the css-in-js colors/typography and port them back into vanilla CSS, but might be a non-goal for Evergreen I imagine?

**Comment by Rowno** [comment]
I started working on making the blueprint icons tree shakable in this branch, but haven't gotten around to finishing it: https://github.com/segmentio/evergreen/tree/icon-code-splitting
