### ISSUE TITLE
Adding custom font family

### ISSUE THREAD

**Issue by alqahtani** [segmentio/evergreen#460]
Hello, 

Thank you for the amazing work!

I just started using Evergreen on a project for a customer and the project will be in Arabic and in the Designs we agreed on using [Cairo Google Font](https://fonts.google.com/specimen/Cairo) but I can't get it to work with the kit.

Any help

**Comment by mshwery** [comment]
Evergreen doesn't set any font family by itself. You'll have to add it yourself to your styles alongside evergreen.
