### ISSUE TITLE
Alert titles are always h4

### ISSUE THREAD

**Issue by alampros** [segmentio/evergreen#462]
Accessibility best practices are to maintain an ordinal hierarchy of semantic heading tags, however, there is currently no means to override the `is="h4"` prop on the `Alert` component's `Heading`:

https://github.com/segmentio/evergreen/blob/e33d0f03394fac0c4bcc38fa90e77d1ea663d047/src/alert/src/Alert.js#L131-L137

## Possible solutions
1. Accept a `titleProps` prop to spread onto the `Heading`
1. Use a block `<strong>` instead
1. Don't wrap the `title` at all and leave it up to the consumer to style it

I'd be happy to submit a PR for any of the solutions - let me know if you have a preference. I like the first approach best as it allows for overriding defaults and won't break anything existing.

**Comment by mshwery** [comment]
@alampros spreadable `titleProps` or `headingProps` would probably be the most versatile, but it also is doing a lot more than we need to solve this.

Perhaps a safer and more flexible approach is to let consumers define the heading component themselves:
```jsx
<Alert titleRenderer={MyCustomHeader} title="My title" />
```
