### ISSUE TITLE
Popover uses deprecated "innerRef"

### ISSUE THREAD

**Issue by arobert93** [segmentio/evergreen#463]
Hi there,

I've been trying to use your "**Popover**" component and it seems to work as expected with the "**Button**" component from your library, but when I tried  my own button component, I get an error:

`styled-components.browser.esm.js:1969 The "innerRef" API has been removed in styled-components v4 in favor of React 16 ref forwarding, use "ref" instead like a typical component.`

I also tried with a basic component, without styled-components, and I get the same error, but this time from React itself.

I'm using:

- **React** version **16.6.1**
- **Styled Components** version **4.1.1**

As a quick fix on Popover children I'm passing innerRef prop to ref attribute, but I would like to avoid doing this...

I believe this lines should be updated:

https://github.com/segmentio/evergreen/blob/2b6b76df27638eff32fb391bc2c8ea1ff7a081df/src/popover/src/Popover.js#L298-L301

Thank you,
Alexandru Robert Comanescu

**Comment by tj** [comment]
I'd also like to know how to get it working for custom components :D or a bit of documentation there would be helpful

**Comment by k5o** [comment]
This affects [Tooltip component](https://github.com/segmentio/evergreen/blob/master/src/tooltip/src/Tooltip.js#L125) and should probably be updated there as well.

Exact error: 

```
Warning: React does not recognize the `innerRef` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `innerref` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

**Comment by auderer** [comment]
I just ran into this problem, causing my popover not to show on-screen.

Here's a temporary workaround:

```js
// HOC to apply innerRef to ref
function withInnerRef (WrappedComponent) {
  return function WithInnerRef ({ innerRef, ...rest }) {
    return <WrappedComponent ref={innerRef} {...rest} />
  }
}

// Usage with styled-components
const MyCustomButton = withInnerRef(styled.button`
  /* custom styles */
`)
```

Or, if you fancy a one-liner:

```js
const withInnerRef = C => ({ innerRef, ...rest }) => <C ref={innerRef} {...rest} />
```

Of course this is not ideal; I'd like to work on a fix for this.

**Comment by kud** [comment]
+1 here when I use Emotion as trigger:

```
 `innerRef` is deprecated and will be removed in a future major version of Emotion, please use the `ref` prop instead in the usage of `ReactiveSearch-SortOptions--Trigger` 
```


Thank you for the workaround :)

**Comment by mshwery** [comment]
Closing this as `innerRef` has been fully removed in v5. Trigger components are now required to support ref or ref-forwarding.
