### ISSUE TITLE
SelectField isInvalid not treated as boolean

### ISSUE THREAD

**Issue by chrisvxd** [segmentio/evergreen#464]
The `<SelectField />` component has a property `isInvalid`, which should be treated as a boolean (as with the `<TextInputField />` component).

It seems the component is checking for presence of the property, rather than it's value.

## What I did

Set `isInvalid={false}` on the `<SelectField />` component:

```jsx
<SelectField
  isInvalid={false}
  required
  label="A required text input field"
  description="This is a description."
>
  <option value="foo" checked>Foo</option>
  <option value="bar">Bar</option>
</SelectField>
```

## What I expected to happen

The component to render with a _valid_ state (and no red border) - just like the `<TextInputField />` component.

## What happened

The component rendered with the _invalid_ state. From your live docs:

<img width="822" alt="screenshot 2018-12-07 16 28 29" src="https://user-images.githubusercontent.com/985961/49659893-22e23800-fa3d-11e8-8d44-bbda07fd1a32.png">

## Workaround

Remove `isInvalid` entirely so the field renders as expected.

---

Thanks for the awesome component library 🙌

**Comment by mshwery** [comment]
Nice catch @chrisvxd !

Would you be open to submitting a PR to tackle this? Looks like a fairly minor tweak from here.

**Comment by chrisvxd** [comment]
Sure thing, once I get a second - will try to look into it early next week.

**Comment by chrisvxd** [comment]
Thanks for fixing 🙏 Unfortunately I was unable to find time to look at this.

**Comment by vadimdemedes** [comment]
@chrisvxd Absolutely no worries, this is open source, everybody's working in their free time :)
