### ISSUE TITLE
Support for Adobe XD?

### ISSUE THREAD

**Issue by ITforHome** [segmentio/evergreen#465]
On you website, i have seen the new section FOR DESIGNER - really great, but i am working with Adobe XD and not with Sketch... Please add Support for Adobe XD, an also great tool for UI/UX-Experience 

Many Thanks

**Comment by ahtik** [comment]
@ITforHome have you tried to open the evergreen .sketch in Adobe XD?

Adobe XD does have the Sketch file support and "Evergreen Community v4.sketch" opens alright for me, at first sight don't see anything wrong with it.

**Comment by mshwery** [comment]
AFAIK we don't have any immediate plans for Adobe XD files, but we'll take it into consideration for the roadmap with the design team.
