### ISSUE TITLE
Invariant Violation in Jest test for RadioGroup

### ISSUE THREAD

**Issue by volkanunsal** [segmentio/evergreen#466]
Hello, 

I've been using evergreen's RadioGroup component in my app. It works fine in the browser, but when I'm testing it in Jest, the test runner complains and fails with this error:

```
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `withTheme(Pane)`.
```
My component looks like this:

```js
<RadioGroup
  value={value}
  size={16}
  options={[{label: 'foo', value: 'foo'}]}
  onChange={() => {}}
/>
```
Does anyone know what might be going on? It looks like `ui-box` is passing an object to `React.createElement` instead of a string or a function.

**Comment by mshwery** [comment]
@volkanunsal Are you able to create a minimal reproduction of the issue in code (e.g. codesandbox or a repo)?

**Comment by volkanunsal** [comment]
@mshwery sorry, I can’t. I no longer use this framework.
