### ISSUE TITLE
How to remove warning:  "ui-box deprecation.."

### ISSUE THREAD

**Issue by indrabinridwan** [segmentio/evergreen#469]
this warning always show on console.
```
ui-box deprecation: the “css” prop will be removed in the next major version in favour of importing glamor directly and passing it՚s generated class to the “className” prop.
render @ `box.js:175
```

**Comment by mshwery** [comment]
Migrate off the `css` prop in `ui-box` or `evergreen-ui` to get rid of that warning. There might be some evergreen components that use it, too, which would have to be migrated off of the `css` prop as well.

**Comment by dillonhafer** [comment]
It looks like it comes from `Pane` https://github.com/segmentio/evergreen/blob/master/src/layers/src/Pane.js#L177

**Comment by indrabinridwan** [comment]
oh still confusing,  okey. thats warning will have effect to render performance?

**Comment by dillonhafer** [comment]
In my experience, they only console log in development environment, not production.

**Comment by mshwery** [comment]
Yeah, it should have no effect in production. They also shouldn't impact render performance, generally, even in development.

That said, we should consider migrating off of that prop in evergreen.

**Comment by amalo95** [comment]
Is this fixed? should this be closed?
