### ISSUE TITLE
Low Contrast Between Disabled and Regular Text

### ISSUE THREAD

**Issue by notfelineit** [segmentio/evergreen#472]
Just a nit: the contrast between 'muted' and regular text could be higher. Please see this gif for an example:

![disabled](https://user-images.githubusercontent.com/31225471/50865142-3b55b300-1359-11e9-8b3f-5e0c661c863d.gif)

**Comment by mshwery** [comment]
Totally agree @notfelineit ! Feel free to PR it :)

**Comment by sdoan16** [comment]
@mshwery Is anyone working on this?

**Comment by mshwery** [comment]
@sdoan16 go for it!

**Comment by mshwery** [comment]
Closing as this is quite stale (and can be themed)
