### ISSUE TITLE
Date Picker Component

### ISSUE THREAD

**Issue by Chrischuck** [segmentio/evergreen#473]
I think this UI could benefit from a date picker since many of the open source React date pickers look very different from Evergreen's UI scheme.

**What I have in mind:**
Date Picker closed:
<img width="292" alt="screen shot 2019-01-12 at 7 27 56 pm" src="https://user-images.githubusercontent.com/13311268/51081289-0fac3300-16a1-11e9-8ce2-66aeb2ec2653.png">
Date Picker opened with no selected date:
<img width="300" alt="screen shot 2019-01-12 at 7 28 29 pm" src="https://user-images.githubusercontent.com/13311268/51081291-133fba00-16a1-11e9-9685-51e5cff6c131.png">
Date Picker open with selected date:
<img width="293" alt="screen shot 2019-01-12 at 7 28 48 pm" src="https://user-images.githubusercontent.com/13311268/51081292-15097d80-16a1-11e9-9337-ad59a62915d7.png">

If this is something that is wanted, I'd be more than happy to build this out and make a PR :)

**Comment by vadimdemedes** [comment]
Hi @Chrischuck, we're holding off on including date picker into Evergreen, as it's a component with too many varying needs and it's something we haven't even discussed yet with our design team at Segment. There was already an attempt to implement it here https://github.com/segmentio/evergreen/pull/453, but we passed on it for now. See https://github.com/segmentio/evergreen/pull/453#issuecomment-442787984 for more explanation.

**Comment by Chrischuck** [comment]
Thanks for the reply. I'll probably try and pick up a bug in that case :)
