### ISSUE TITLE
SelectMenu Throws Warning on: Unknown event handler property `onFilterChange`

### ISSUE THREAD

**Issue by zischwartz** [segmentio/evergreen#475]
Small bug, after updating to `4.9.0` I get an error from `react-dom-development.js` whenever I click on a `SelectMenu` which says  "Unknown event handler property `onFilterChange`. It will be ignored." 

[Here's an example replicating it](https://codesandbox.io/s/jn67wn90q3) based on the docs. It doesn't seem to matter if I'm using the filter or not. 

To reproduce, click on the `SelectMenu` and then see click on the console in the bottom left (or open the browser console).

I'm running Chrome 71.0.3578.98 on a Mac.

Thanks!

**Comment by vadimdemedes** [comment]
cc @notfelineit

**Comment by mshwery** [comment]
This seems to be resolved.
