### ISSUE TITLE
Badge with color set to "automatic" throws error 

### ISSUE THREAD

**Issue by zischwartz** [segmentio/evergreen#476]
The automatic color on the Avatar component is great, but when using it on the `Badge` component according to the [documentation](https://evergreen.segment.com/components/badge-and-pill), `<Badge color="automatic">Hi</Badge>`  doesn't seem to work and throws an error:
```
TypeError
Cannot read property 'color' of undefined
Badge.render
../../../src/badges/src/Badge.js:58:12
```
It looks like it's trying to get it from the theme, which I'm not messing with at all.

[Here's some examples reproducing the error](https://codesandbox.io/s/5k2n9o5y7l)

I'm running Chrome 71.0.3578.98 on a Mac. Using evergreen `4.9.0`

Thanks!

**Comment by mshwery** [comment]
Ah, that might be a mistake (copy pasta) in the docs. I don't think Badge is supposed to support the same color values as Avatar.
