### ISSUE TITLE
Heading 200 doesn't have Letter spacing

### ISSUE THREAD

**Issue by zeroslope** [segmentio/evergreen#479]
When I read the document, in the chapter on Typography, I found that it has no corresponding config Letter spacing.

![image](https://user-images.githubusercontent.com/10218146/51450106-48679e80-1d6a-11e9-8925-4941d25c21f3.png)

When I read the source code of the theme, I found that only heading 200 does not have Letter spacing config. 

https://github.com/segmentio/evergreen/blob/master/src/theme/src/default-theme/typography/headings.js#L80

```
  '300': {
    fontSize: '12px',
    fontWeight: 600,
    lineHeight: '16px',
    letterSpacing: '0',
    marginTop: 16,
    fontFamily: fontFamilies.ui,
    color: colors.text.dark
  },
  '200': {
    fontSize: '12px',
    fontWeight: 600,
    lineHeight: '16px',
    marginTop: 16,
    fontFamily: fontFamilies.ui,
    color: colors.text.muted
  },
  '100': {
    fontSize: '11px',
    fontWeight: 400,
    textTransform: 'uppercase',
    lineHeight: '16px',
    letterSpacing: '0.6px',
    marginTop: 16,
    fontFamily: fontFamilies.ui,
    color: colors.text.muted
  }
```

So I want to know if evergreen did this purpose, or forgot it.

**Comment by vadimdemedes** [comment]
I think this is just an oversight. Would you be willing to submit a PR with a fix for it?

**Comment by zeroslope** [comment]
> I think this is just an oversight. Would you be willing to submit a PR with a fix for it?

Of course, that‘s my pleasure. I think the missing value is `letterSpacing: '0'`. I will read the contribution guide to complete a correct PR.

**Comment by vadimdemedes** [comment]
Let's keep the issue open until it's fixed ;)
