### ISSUE TITLE
Remove browser tooltip from icons

### ISSUE THREAD

**Issue by vadimdemedes** [segmentio/evergreen#483]
There's a `<title>icon name</title>` inside each icon's svg and there's no way to remove it via `<Icon>`'s props:

![icon-tooltip](https://user-images.githubusercontent.com/697676/51711133-05aefc00-1fe0-11e9-9e04-329cfa1b205e.gif)

It's especially annoying when there's a `<Tooltip>` for that icon and user ends up seeing 2 tooltips: one from evergreen, one from browser. I think we should remove it.

**Comment by jongsue** [comment]
How about this?
It looks not good because of empty string for title but it's working.

```javascript
<Tooltip content="cross">
    <Icon icon="cross" title="" />
</Tooltip>
```
