### ISSUE TITLE
Tooltip doesn't work on iOS

### ISSUE THREAD

**Issue by mifi** [segmentio/evergreen#496]
1. Open iOS safari (ios 12.1.2)
2. Navigate to: https://evergreen.segment.com/components/tooltip/
3. tap on the first tooltip and it appears
4. zoom in
5. the tooltip moves out of the way as you zoom and ultimately disappears

**Comment by Chrischuck** [comment]
It's most likely an issue w/ `position:fixed`  style property that's set on the tooltip.

See: https://stackoverflow.com/questions/4889601/position-fixed-doesnt-work-on-ipad-and-iphone

I can try and mess around with it and see if I can fix it later today

**Comment by Chrischuck** [comment]
After exploring this a little, it seems to be a pretty tricky bug especially since I can't recreate the issue in storybook, but I'm thinking it might be possible to get the correct coordinates by using `visualViewport`'s properties.

**Comment by mshwery** [comment]
Closing as this issue is quite stale.
