### ISSUE TITLE
SelectMenu onDeselect 

### ISSUE THREAD

**Issue by rejifald** [segmentio/evergreen#504]
Hi all. I am newbie in React and in evergreen too.
I use `4.12.1` evergreen version. MacOS, Chrome 72. Haven't published this project yet.
But i believe there is a bug with SelectMenu:onDeselect event.
My event handler isn't invoking. 
onSelect works ok, but onDeselect isn't. BTW, when i open menu at the first time, i see get this error in console:
![image](https://user-images.githubusercontent.com/42000283/53287982-be0cc300-378b-11e9-8dd6-286dafbae2aa.png)
Here is how i use it:
```
        <SelectMenu
          title={'Choose level'}
          selected={this.state.filters.levels}
          onSelect={item => this.onLevelSelect(item.value)}
          onDeselect={item => this.onLevelDeselect(item.value)}
          hasFilter={false}
          options={[
            'error',
            'warn',
            'info',
            'verbose',
            'debug',
            'silly'
          ].map(label => ({ label, value: label }))}>
          <Button>Select level</Button>
        </SelectMenu>
```

**Comment by mshwery** [comment]
The proptype warning is a regression – nice find. As for the `onDeselect` behavior it's really hard to help without a link to a minimal reproduction of the issue in code @rejifald

**Comment by rejifald** [comment]
@mshwery NP ! Here is repo with my experimentals. https://github.com/rejifald/k just clone it, and run `npm start`. 
And open `localhost:3000`. In top lever corner u will see `Select level` button. This is SelectMenu trigger.
Hope, it will help.

**Comment by mshwery** [comment]
The example in the docs works. Have you tried the `isMultiSelect` prop?

**Comment by rejifald** [comment]
Yes. I've checked docs, and i know that there it works.
Hm... I've tried... But i think it wasn't work. But now i see that it works... Thanks :)
But why i can't deselect item if **isMultiSelect** is false ?
And, i still see same error.

**Comment by mshwery** [comment]
That is a good question. It might be by design (although I'm not sure I agree with that design now).

I think it behaves similar to a native browser `<select>` in that once you've selected something you cannot deselect it unless you have `multiselect` set. You can only select a _different item_ but not deselect the currently selected item.

**Comment by rejifald** [comment]
If i want to let user ability deselect item, i can't anyway, right ?
It forces me to implement additional buttons, etc.
Combobox also disallow this. For example 
![image](https://user-images.githubusercontent.com/42000283/53353211-eaac1080-392c-11e9-9dc5-17823b6d3699.png)
I chosen item, and i modified it, but drowdown still looks like that item selected.

**Comment by JMFURY** [comment]
@rejifald I added the `onDeselect` method way back when, and all it does is function as a way to 'prop drill' an event down to the `onClick => handleClick` part of the [`<TableRow>`](https://github.com/segmentio/evergreen/blob/master/src/table/src/TableRow.js) within SelectMenu's `<Option>`

[Here's that:](https://github.com/segmentio/evergreen/blob/master/src/table/src/TableRow.js)

![image](https://user-images.githubusercontent.com/7191639/53382583-69f41100-393a-11e9-9c5f-6df945971187.png)

Notice the `isSelectable` part. I believe `isMultiSelect` was added to help decide that part of it more clearly and explicitly.

[On the `<OptionsList >` component ](https://github.com/segmentio/evergreen/blob/master/src/select-menu/src/OptionsList.js)(parent of `<Option>`), here's where `isMultiSelect` is used to decide where an item should be 'selectable':
`   isSelectable: !isSelected || isMultiSelect `

So I think it is necessary to have `isMultiSelect` to get the desired behavior on a 'multiselect-able' implementation of `<SelectMenu>` and NOT on the original (single-select) implementation as @mshwery explored.
