### ISSUE TITLE
Set up ref forwarding for input components

### ISSUE THREAD

**Issue by danedavid** [segmentio/evergreen#508]
Assigning a ref to `SearchInput` should assign the ref to the inner `<input type="text"/>`.

**Comment by mshwery** [comment]
You should be able to do this by using `innerRef` already.

**Comment by mshwery** [comment]
Here's an example: https://codesandbox.io/s/qx63wzk149

**Comment by maycy92** [comment]
innerRef does not work for Select or Combobox components. Any thoughts?
