### ISSUE TITLE
Error scrolling thru table with down arrow: "TypeError: Failed to execute 'removeChild' on 'Node'

### ISSUE THREAD

**Issue by sheminusminus** [segmentio/evergreen#519]
## Issue

When scrolling through a `Table.VirtualBody` row-by-row, using the down arrow key, a `TypeError` is thrown when reaching the last item.

## Expected Behavior

Reach the end of the list, last item becomes highlighted, and nothing else happens when the down arrow is pressed again.

## Actual behavior

TypeError

## Steps to Repro

Create a table with a virtual body. Select a row. Keep pressing down until you reach the end.

You can't do this super slowly-- you have to scroll through them semi-quickly, at a believable pace for someone scanning a list, and it doesn't seem like you can trigger this by starting the selection on any of the last few rows. Would recommend starting (clicking on an initial row) at least five or six rows from the bottom of the list.

It may or may not be important for the following handlers to be present on the table rows, so here is a copy-paste of the code I'm using:

```
<Table.VirtualBody height={400}>
    {resources.map((item, idx) => (
        <Table.Row
            isSelectable
            key={item.id}
            onDeselect={() => {
                this.handleRowDeselected(item.id);
            }}
            onSelect={() => {
                this.handleRowSelected(item.id);
            }}
            onKeyPress={(evt) => {
                this.handleTableRowKeypress(evt, item.id);
            }}
        >
         ... // row contents
```

## Specs

- Chrome 72
- macOS 10.14
- react/react-dom 16.6.1
- Evergreen 4.13.1

## Sentry Logs

[Sentry Error Logs](https://sentry.io/share/issue/8bcc05af7cac4134b67bf7ca664ab6d1)

## Etc

This technically errors in the development build of react-dom, but the stack trace points to maybe something in the tiny virtual list code, so I'm not sure if the catalyst here is Evergreen or not. Screenshot:

![Screen Shot 2019-03-12 at 11 32 01 PM](https://user-images.githubusercontent.com/9907610/54253987-dc124b80-451f-11e9-83b1-24c2ea0fac29.png)

What the UI looks like just before this is thrown:

![Screen Shot 2019-03-12 at 11 32 41 PM](https://user-images.githubusercontent.com/9907610/54253994-e2082c80-451f-11e9-89f2-f9a100b77037.png)

**Comment by mshwery** [comment]
I'm not able to repro this. Can you create a codesandbox that reproduces the error?

**Comment by mshwery** [comment]
Closing as this is stale and cannot reproduce. Feel free to reopen with a minimal reproduction linked in the issue!
