### ISSUE TITLE
Position property for CornerDialog

### ISSUE THREAD

**Issue by dy** [segmentio/evergreen#520]
Corner dialog is a bit different from main dialog in terms of it provides nicer default UI for prompts/confirmations. Having `position` property, similar to tooltips, would be handy.

Is there any sense in such PR?

**Comment by mshwery** [comment]
Are you thinking it'd be used to change which corner the dialog is anchored to?

**Comment by dy** [comment]
Yes, to make it a lightweight alternative to big dialogs.
Would be also nice to have “alignButtons” property.

**Comment by dy** [comment]
I could come up with PR
