### ISSUE TITLE
Popover hover support

### ISSUE THREAD

**Issue by tj** [segmentio/evergreen#534]
It would be sweet if you could hover the contents to show the popover, for hover menus. I was going to use Tooltip but it's missing the optional callback with `{ close }`. Just going to leave it as a click for now but happy to send a PR later when I have a chance if you're interested.

**Comment by mshwery** [comment]
Sounds like a good addition @tj!

**Comment by jtanya34** [comment]
Can I take up this issue?

**Comment by robphoenix** [comment]
@tj Can this be closed by #565?

**Comment by mshwery** [comment]
Yep! Closing.
