### ISSUE TITLE
Allow component as props for Icon

### ISSUE THREAD

**Issue by eoinmurray** [segmentio/evergreen#535]
This is a minor issue but sometimes when using Buttons I pass an `Image` for `iconBefore` like so:

```
<Button
  onClick={() => {}}
  iconBefore={(
    <Image src="some-icon.png" />
  )}
>
  blah blah...
</Button>
```

It's useful because I can specify anything I want - but I get lots of propType warnings since Icon is expecting a string - maybe we can relax this condition a bit?

**Comment by mshwery** [comment]
I wouldn't be opposed to updating the proptypes to match the internal behavior. Would you want to submit a small PR with the fix @eoinmurray ?
