### ISSUE TITLE
Disable closing Popover on outside click

### ISSUE THREAD

**Issue by mehmetnyarar** [segmentio/evergreen#544]
Hi,

>Popovers Close On
Outside click
Escape key
The close function being called (advanced)

I'd like to disable closing `Popover` on `Outside click`, enable only `Escape key` or `The close function being called`.

Is there a way to do that with the current API? If not, could you please add this feature?

"evergreen-ui": "^4.15.0",

**Comment by mshwery** [comment]
Doesn't look like that's currently available but it should be relatively straightforward if you wanted to open a PR and add that feature. We support [a similar api in the `Dialog` component](https://github.com/segmentio/evergreen/blob/352cbc78177699bf7e41fec3951a5220963ff672/src/dialog/src/Dialog.tsx#L149)

**Comment by mehmetnyarar** [comment]
Hey @mshwery,

I've tried using `Dialog` but it doesn't play well with `react-datepicker` when it comes to popup a calendar  inside the `Dialog`, calendar/time picker appears in an irrelevant position.

Regarding PR, I don't have any experience contributing to an open-source project on GitHub yet (

**Comment by mshwery** [comment]
Oh! I highly recommend it :) There are some decent instructions on contributing in the readme: https://github.com/segmentio/evergreen/#contributing-to-evergreen

**Comment by palmer-cl** [comment]
I can take a stab at this. I'll update here with the PR when ready! :+1:
