### ISSUE TITLE
Hide SideSheet's close button

### ISSUE THREAD

**Issue by mehmetnyarar** [segmentio/evergreen#548]
Hi,

I'd like to hide the close button in `SideSheet` component.

Is there a way to do that with the current API? If not, could you please add this feature?

"evergreen-ui": "^4.15.0",

**Comment by mshwery** [comment]
You can do that. `SideSheet` let's you pass children as a render function that receives a `close` callback so you can hook it up however you like.

>Children can be a string, node or a function accepting `({ close })`.

**Comment by mehmetnyarar** [comment]
Hey @mshwery,

You can see an example [here](https://imgur.com/5EcbcX9).

I added transparency to the `SideSheet` via `containerProps`. That makes the close button far away from the content, which I feel is a bad UX. If I could hide it, I'd add my own close button somewhere and use `({ close })`.

One option is to add `id` attribute to the container of the close box, then it can be targeted via CSS, or a property like `hideCloseButton` would be more awesome.

**Comment by mshwery** [comment]
Interesting. This looks a bit more like a dialog to me than a sidesheet. You can probably customize the dialog a bit more to meet your needs. If not, I'd recommend implementing a custom composition of Overlay + Pane to meet your needs. Evergreen exposes all the fundamental building blocks you need to build customized components like this.

**Comment by mehmetnyarar** [comment]
In a technical sense, a kind of dialog yes, but i like how `SideSheet` pops up from the bottom.

Do you mean using `Positioner` component? If yes, I'd appreciate an example how `target` is used. `({ getRef: () -> Ref, isShown: Bool }) -> React Node`.

**Comment by mehmetnyarar** [comment]
Fixed it for now, hoping that it will not break the UI in somewhere else )

```css
.📦box-szg_border-box.📦w_32px.📦h_32px {
  display: none;
}
```

**Comment by mshwery** [comment]
@mehmetnyarar that isn't safe since there are other components that may end up with that same composition of atomic classes.
