### ISSUE TITLE
Event onCloseComplete don't execute on use close() in onConfirm event

### ISSUE THREAD

**Issue by paegle** [segmentio/evergreen#559]
Hi guys!

When I use close function in onConfirm event, the onCloseComplete don't execute...

`onCloseComplete = () => {
    console.log('onCloseComplete');
  };`

`onConfirm = close => {
    close();
  };`

`<Dialog isShown={true} onCloseComplete={onCloseComplete} onConfirm={onConfirm}><Text>Test</Text></Dialog>`

If you see in console, the 'onCloseComplete' don't execute when confirm button is clicked

Is this correct and I use the events in the wrong way?

**Comment by mshwery** [comment]
Can you provide more information about the version of `evergreen-ui` and a link to a minimal representation of the issue? Otherwise we can't really help you.

Based on what you've described this works as it should: https://codesandbox.io/s/vibrant-leakey-56efk
