### ISSUE TITLE
Should TagInput onAdd return an Array?

### ISSUE THREAD

**Issue by karltaylor** [segmentio/evergreen#560]
In the docs for the `onAdd` prop for [TagInput](https://github.com/segmentio/evergreen/blob/master/docs/src/pages/components/tag-input.mdx#using-onadd-and-onremove-advanced) there is an `if` statement that checks if the value includes an `@`.

However after testing, I realised the `onAdd` returns an `array` so `if (!value.includes('@')` would never work.

```jsx
<Component initialState={{ values: ['matt@awesome.com'] }}>
  {({ state, setState }) => (
    <TagInput
      inputProps={{ placeholder: 'Add email...' }}
      values={state.values}
      onAdd={value => { // returns ['hello']
        if (!value.includes('@')) { // Will never work
          toaster.danger('Oops, you tried entering a invalid email. Try again.')
          return
        }
        setState({
          values: [...state.values, value]
        })
      }}
      onRemove={(_value, index) => {
        setState({
          values: state.values.filter((_, i) => i !== index)
        })
      }}
    />
  )}
</Component>
```

Not sure if this is a documentation issue, or an `onAdd` issue. Should `onAdd` just return a string?

**Comment by mshwery** [comment]
`onAdd` returns an array of all tag values input so far – it cannot return just a single string because you can enter multiple tags via copy/paste or typing delimited values (delimited by your `separator` prop) all at one time. We cannot guarantee that you'll get only a single value added at a time.

It looks like the example in the docs is wrong.

**Comment by karltaylor** [comment]
Interesting, the value from `onAdd` looks like it only returns the value entered in an array. Check this [codesandbox](https://codesandbox.io/s/blazing-glitter-y9g9i)

**Comment by mshwery** [comment]
Ah right, but it's an array because you can enter multiple values at one time.

**Comment by akleiner2** [comment]
Closing out due to inactivity
