### ISSUE TITLE
Request: link to headings in docs

### ISSUE THREAD

**Issue by kevinSuttle** [segmentio/evergreen#562]
👋 Hey Segment! Loving Evergreen. You folks have done some great work here. I find myself sharing links from Evergreen pretty regularly. 

What would be super nice, is if the headings were linked, so I could share a URL to a specific section of a page, like it does here on GitHub: 

https://github.com/segmentio/evergreen/blob/master/docs/src/pages/components/icons.mdx#resizing-the-icon

Thanks!

**Comment by solon-aguiar** [comment]
Hi @kevinSuttle,

Thanks for reaching out! Just to make sure that I understand your request correctly, are you asking if the headings in the Evergreen documentation under `evergreen.segment.com` to be links?

Example: on https://evergreen.segment.com/components/layout-primitives to be able to link directly to `Pane component` or `Never pass a string of text as direct children` etc?

**Comment by kevinSuttle** [comment]
Yes, exactly!

**Comment by solon-aguiar** [comment]
I think this makes sense. The links should be working actually. It might be a misconfiguration when we're generating the website. I'll look into it (or you can send a PR if you want!) this week.

In the meantime, the docs are all in this repo as `mdx` files, so you can actually link someone to them if you want. Example: [the file](https://github.com/segmentio/evergreen/blob/dc64b46759e5f3a40fa201d9a41b20be625e1d07/docs/src/pages/components/layout-primitives.mdx#never-pass-a-string-of-text-as-direct-children) that we've been talking about.

**Comment by solon-aguiar** [comment]
I played around with this today and couldn't get the links to come up.

I looked at the `gatsby-mdx` plugin (which is what we use to render) and there are a couple of issues about this: https://github.com/ChristopherBiscardi/gatsby-mdx/issues/396 and https://github.com/ChristopherBiscardi/gatsby-mdx/issues/204 (using a `remark` plugin).

There's a PR (https://github.com/ChristopherBiscardi/gatsby-mdx/pull/389) going on that might address it (linked in the first issue). I'm not a gatsby expert (my first time using it). I'll try to poke around more and see if I can get the plugin to work while that PR is not merged.

**Comment by kevinSuttle** [comment]
Thanks! I looked around also and couldn't figure out where it was triggering, either. When you mentioned that it should be working, did you have a commit or PR you were thinking of that reminded you?

**Comment by solon-aguiar** [comment]
Hey Kevin!

> When you mentioned that it should be working, did you have a commit or PR you were thinking of that reminded you?

No, when I mentioned that it should be working I meant that it should be working by default from `gatsby-mdx`'s implementation (this is the plugin we use to render md content). Looks like they have to fix it to get it working by default. Once they fix it, we'll have to update our version and deploy.

What I did was to try to use another plugin just to generate the slug for the heading sessions and attach id to the HTML elements similar to what is recommended in https://github.com/ChristopherBiscardi/gatsby-mdx/issues/204, but that didn't work (I could have done it wrongly!).

**Comment by kevinSuttle** [comment]
Awesome. Thanks for the follow-up!

**Comment by mshwery** [comment]
The new doc site has all of this! Closing :)
