### ISSUE TITLE
Css not loading in Chrome, emoji encoding issue?

### ISSUE THREAD

**Issue by agonist** [segmentio/evergreen#566]
### Bug report 🐞 

Hello, I and @ugogo are working on a website with the following stack:
Rails api + react-static for the front + Heroku, obviously using Evergreen for the UI.
And we're facing one last issue that gives us a really hard time, and after a long investigation, someone from Heroku has pinpointed something that might come from evergreen. 
As we are getting desperate you are the last people we haven't asked from help now and you might have an idea.

The details : 

## Issue and steps to reproduce.
The issue is easy to reproduce, visit our [website](https://www.gilitrip.com/) using Google Chrome as the issue only appears with Chrome.
On the first visit, or with a force refresh you will see quickly that often the CSS is not getting loaded and the layout is then not really beautiful 💅
The issue also only appears in the deployed version on Heroku not in local.

## Versions
Evergreen 4.17.0

## Current investigation
After many useless back and forth, I opened a ticket with Heroku and here is the answer that actually makes sense and could be a good hint. Let us know what do you think about it: 

---- HEROKU ANSWER ------

Hi Bastien,

Thanks for writing in.

I've been taking a look at your site and I could easily reproduce the CSS issues that you're seeing with Chrome. Something I noticed is that the stylesheet "evergreen-css" is using emojis as CSS selectors.

When CSS works correctly in Chrome, or for other browsers, I see that the developer tools show the styles as:

```
.📦w_100prcnt{width:100%}.📦max-w_65rem{max-width:65rem}.📦ml_auto{margin-left:auto}
```
However, when inspecting the "evergreen-css" styles from Chrome when the CSS is not applied correctly, I see:
```
.ðŸ“¦w_100prcnt{width:100%}.ðŸ“¦max-w_65rem{max-width:65rem}.ðŸ“¦ml_auto{margin-left:auto}
```
so it seems this is caused by an encoding issue.

-----

What do you think? It's a fact that the evergreen css encoding is broken when the problem happens. have you ever faced something like that? Or do you think it might come from some of our configuration in the project? We can provide any file that might help you.

In the meantime thanks a lot for any future help 🙏

**Comment by mshwery** [comment]
Definitely looks like an encoding issue. Although I've never seen this issue raised from `evergreen-ui` or `ui-box` yet.

**Comment by mshwery** [comment]
Without knowing much about your setup I would look to Rails because it's handling your assets and their encoding, right?

**Comment by joshlarsen** [comment]
Rails in API mode doesn't handle assets. I'm not familiar with `react-static`, but it looks to be responsible for static page generation - and possibly plays a role in encoding issues.

I have an app on Heroku with a Rails API backend and React frontend with `evergreen-ui`. I have not encountered any issues like this (though I do agree with removing the box emoji for cosmetic reasons).

**Comment by stephenmathieson** [comment]
Not sure if this is the cause, but...

You're setting `<meta charSet="UTF-8" />` _after_ using a bunch of emojis in your HTML document. This is possibly causing Chrome to use its default charset (ISO-8859-1) which does not contain emojis. So it's not correctly registering the selectors defined in your `<style type="text/css">` tag.

I suggest putting `<meta charset="utf-8">` as the very **first** thing in the `<head>` of your document and seeing if this corrects the encoding issue.

---

As a side note, I would like to see the emojis removed from `ui-box` selectors. They're "cute" and all, but the source of more confusion than anything else.

**Comment by stephenmathieson** [comment]
Another observation: it looks like the server is sending a `content-type` header (which is awesome), but it's not including a `charset=` there either (which again, instructs the browser to do whatever it wants).

![contenttype](https://user-images.githubusercontent.com/571265/58705580-9fffc180-837d-11e9-99d5-226488e17623.png)

Try updating CloudFlare configuration to ensure `Content-Type: text/html; charset=utf-8` is sent along with your HTML document.

**Comment by agonist** [comment]
🎉 OKAY, everything is working now finally 😍 
after we add the charset to the correct place and make sure about the order of things in the <head>

we had one last issue, our own css was also loaded too early and after I removed 
```
  extractCssChunks: true,
  inlineCss: true,
```
from the react-static config everything was back to normal. 

So thank a lot to all of you that helped us 🙏 We really appreciate and can finally move forward. Enjoy the weekend

**Comment by superhighfives** [comment]
Glad you got to the bottom of it, @agonist! 👍 to everyone for helping out, too.
