### ISSUE TITLE
Avatar example src URL points to invalid image

### ISSUE THREAD

**Issue by humphd** [segmentio/evergreen#574]
I was looking through your docs and noticed that the example at https://evergreen.segment.com/components/avatar for using an Image for the Avatar is showing the fallback initials:

<img width="836" alt="Screen Shot 2019-06-04 at 9 54 21 PM" src="https://user-images.githubusercontent.com/427398/58924871-78a94b80-8713-11e9-9e9c-697d8124dae0.png">

It looks like the image is 404:

```
curl https://pbs.twimg.com/profile_images/756196362576723968/6GUgJG4L_400x400.jpg -I
HTTP/2 404
accept-ranges: bytes
access-control-allow-origin: *
access-control-expose-headers: Content-Length
cache-control: max-age=3600, must-revalidate
content-type: image/jpeg
date: Wed, 05 Jun 2019 01:56:10 GMT
last-modified: Wed, 05 Jun 2019 01:51:24 GMT
server: ECS (ord/26AD)
strict-transport-security: max-age=631138519
x-cache: 404-HIT
x-connection-hash: 11ab8df88bcb6af4872b8351f07d93f0
x-content-type-options: nosniff
x-response-time: 10
content-length: 0
```

**Comment by solon-aguiar** [comment]
Thank you for finding this issue! I've created a PR to address that: https://github.com/segmentio/evergreen/pull/585.

In the future, feel free to also contribute with the fixes if you want/can. You can read more about contributing in [our docs](https://github.com/segmentio/evergreen#contributing-to-evergreen).

Cheers
