### ISSUE TITLE
Add disabled prop and styles to SegmentedControl

### ISSUE THREAD

**Issue by sbrichardson** [segmentio/evergreen#575]
Would you accept a pull request to add a `disabled` prop to `SegmentedControl`? I'm thinking it would be similar to `Button` or `Tab`. 

One thought, to avoid duplicate code, could be an option to provide a `Button` (or array of buttons), or just refactor `SegmentedControl` to inherit or be similar to `Button` (or `Tab`)? That would allow it to have features like icons also.

A new style may be needed to differentiate which is disabled and also the active segment, etc.

From [Button](https://github.com/segmentio/evergreen/blob/master/src/buttons/src/Button.js#L64) docs:

```js
 /**
   * When true, the button is disabled.
   * isLoading also sets the button to disabled.
   */
    disabled: PropTypes.bool,
```

If you have any other examples of components inheriting/sharing Button, I can review that code. Any other ideas or considerations?

**Comment by mshwery** [comment]
Sounds reasonable to me! I'm not 100% sure what behavior makes sense – should the entire control be disabled or individual buttons within the group?

**Comment by robphoenix** [comment]
I have a use case that would benefit from being able to disable individual buttons. I'd be interested in seeing this added.

**Comment by allenlai18** [comment]
I think we need UI designs for this.

**Comment by mshwery** [comment]
The prop and behavior is there, but we don't have any visual indicator the segmented control is disabled // cc @akleiner2 @colinlohner 

Going to close for now!
