### ISSUE TITLE
Invalid is prop on Link

### ISSUE THREAD

**Issue by robphoenix** [segmentio/evergreen#581]
I'm using the evergreen `Link` component along with Reach Router's `Link` component, as suggested [in this issue](https://github.com/segmentio/evergreen/issues/376)

```javascript
import React from 'react'
import { Link } from 'evergreen-ui'
import { Link as RouterLink } from '@reach/router'

const NavLink = (props) => {
  const { to, children } = props
  return (
    <Link is={RouterLink} to={to} textDecoration="none" color="neutral">
      {children}
    </Link>
  )
}

export default NavLink
```

It works but shows a warning in the console (truncated for brevity)

```
Warning: Failed prop type: Invalid prop `is` supplied to `Text`.
...
Warning: Failed prop type: Invalid prop `is` supplied to `Box`.
```

I don't know if this is expected, a bug or something wrong with my code?

Thanks :+1:

**Comment by mshwery** [comment]
Not sure we can help with this – We use custom components internally all the time with `evergreen-ui`.

If you think there is a bug can you produce a minimal reproduction of the issue in codesandbox or similar?

**Comment by robphoenix** [comment]
@mshwery sure, I'll see if I can reproduce it in codesandbox, it's entirely likely it's my code.

**Comment by robphoenix** [comment]
ok, I can't reproduce it :roll_eyes: 

I should've done that before opening this issue. Sorry for the noise.

**Comment by mshwery** [comment]
No worries! Might be worth posting to stackoverflow to get help from the community since it doesn't seem to be a bug with `evergreen-ui`.

**Comment by senasi** [comment]
Hello, I have encountered similar problem with evergreen's Link and react-router's Link. As correctly stated by @mshwery it's not a bug in `evergreen-ui`.

Problem is, react-router's `Link` is wrapped in `React.forwardRef()`, which is returning an object (which can still be rendered, more info here: https://github.com/facebook/react/issues/12453).

`is` prop is being taken from `ui-box` library and is not expecting an object, that's where the errors come from:
```
is: PropTypes.oneOfType([PropTypes.string, PropTypes.func])
```

It seems that quick workaround for this use case could be to wrap react router's `Link` in another function component, for example:
```
import { Link as EvergreenLink } from 'evergreen-ui';
import { Link as ReactRouterLink } from 'react-router-dom';

const Link = (props) => (
	<EvergreenLink is={(p) => <ReactRouterLink {...p} />} {...props} />
);
```
Then you can use `Link` as expected and without errors.
