### ISSUE TITLE
Multiple mode for Menu.OptionGroup

### ISSUE THREAD

**Issue by dy** [segmentio/evergreen#584]
SelectMenu has a prop to make it support multiple options: `isMultiSelect`.
In Menu.OptionGroup there's no such documented option. I guess enabling that would be useful.

**Comment by akleiner2** [comment]
Closing this out due to inactivity - for now, the UI treatment is intentionally different, and we haven't seen a use case for multiselect Menu, but happy to consider alternate solutions.
