### ISSUE TITLE
SelectMenu with multiselect allows selecting the same item many times with keyboard

### ISSUE THREAD

**Issue by solon-aguiar** [segmentio/evergreen#589]
🐛 

- Issue and steps to reproduce.

SelectMenu: in a multi-select menu, a user can select the same element many times. `SelectMenu` has an option to allow users to select multiple elements and when users select the elements using their keyboard (e.g. just hitting the arrow down key) rather than the mouse, the same item is selected many times (one per keystroke to be precise). This is evident when the menu displays the number of selected items and that is more than the number of options.

- Versions.
Latest.

- Screenshots.
![Screen Shot 2019-06-19 at 10 12 43 AM](https://user-images.githubusercontent.com/1903101/59786188-86b2ac80-927b-11e9-94fa-5727057a1d6b.png)
(☝️ from storybook)

The console (after a modification to log the selected elements):
![Screen Shot 2019-06-19 at 10 22 16 AM](https://user-images.githubusercontent.com/1903101/59786446-22441d00-927c-11e9-8b1b-4e4e24602f76.png)

- Expected.
Each element can only be selected once.

- Actual.
Each element can be selected more than once.

- Link to your project.
https://github.com/segmentio/evergreen :)

- Browser name and version.
Chrome:  74.0.3729.169 (Official Build) (64-bit)

- Operating system.
Any

**Comment by solon-aguiar** [comment]
Turns out that this is not a bug in the implementation of the component. It is just a bug in our stories and docs example. I can fix that. However, while at it, I'd like to propose a change in the way the `SelectMenu` component works for keyboard navigation.

The way that the keyboard navigation works today doesn't allow a user to select non-continuous elements. It doesn't allow for gaps in the list. For example. Let's say the options are:

```
Apple
Apricot
Banana
```

If a user, using the keyboard, wants to select just `Apple` and `Banana` (fruits that I normally put on my smoothie), there is just no way! This doesn't seem to be very useful. You can try that yourself on the storybook or in our docs example: https://evergreen.segment.com/components/select-menu.

This happens because on the `handleArrowDown` and `handleArrowUp` functions we select and de-select the components ([code](https://github.com/segmentio/evergreen/blob/master/src/select-menu/src/OptionsList.js#L168-L192)). Therefore, a user has no way to get to banana without selecting apricot. And once apricot is selected, they can only deselect by using the arrow up, which will deselect banana as well.

I propose that we change this. Up and down arrows should just to navigate the list up and down. Selecting or deselecting an element should be handled by another key (either left right arrows or the space bar for example).

**Comment by mshwery** [comment]
Sounds good to me @solon-aguiar ! I think it's common to use tab or enter (or even provide a choice between the two) as "select" whereas arrow keys up/down (and optionally left/right) navigate prev/next.

**Comment by solon-aguiar** [comment]
Actually, this is a bit more complicated than anticipated. The problem is that when we have the search filter input, navigating using the arrows should be done inside the input field, not the menu items. The way I had implemented (using the arrows) causes un-intended effects (selecting an element when you're actually trying to move the cursor in the search query).

My idea to tackle this is: 
1. TAB to navigate to the next element in the options list
1. SHIFT + TAB to navigate to the previous element in the options list
1. ENTER to mark an unselected element as selected
1. ENTER to mark a selected element as unselected
1. ESC to close the menu option list

**Comment by mshwery** [comment]
I would do something similar to downshift's keyboard support where the up/down arrow keys also navigate the options list. 

The rest sgtm!

**Comment by solon-aguiar** [comment]
There's another bug with the up and down arrows today: up arrow navigates to the end of the search query and down arrow to the beginning. At the same time, they navigate in the menu options (selecting new options). Everything is completely and "bugly" coupled. I want to deactivate this up and down in the input field. `cmd/windows + left` and `cmd/windows + right` make more sense in navigating to the end or beginning.

**Comment by mshwery** [comment]
Closing as the issue is quite stale. Feel free to reopen or submit a new PR!
