### ISSUE TITLE
support for vue.js or plain css !

### ISSUE THREAD

**Issue by id1385** [segmentio/evergreen#592]
hello
i dont use react 
i use vue.js 
 i like ur components 
is your project support for vue js ? or share plain css we convert it to vue

**Comment by maraisr** [comment]
Hello 👋 sorry - There is little to no css in this project. And a port to it would actually be quite difficult. The project uses [ui-box](https://github.com/segmentio/ui-box) quite heavily. If that helps 🤷‍♂

**Comment by mshwery** [comment]
We don't have any plans to support Vue at this time.

You can make use of plain css alongside `evergreen-ui` but it may not behave quite as you expect, due to the CSS-in-JS solution we get from ui-box. You'll probably run into things like specificity clashes and order hierarchy.
