### ISSUE TITLE
FilePicker onBlur throws an error

### ISSUE THREAD

**Issue by dy** [segmentio/evergreen#597]
```js
import React from 'react'
import { render } from 'react-dom'
import { FilePicker } from 'evergreen-ui'

render(<FilePicker/>, document.querySelector('#app'))
```

If we click on filepicker text input and then blur, it throws an error.
That happens in all the examples in docs https://evergreen.segment.com/components/filepicker

**Comment by ronocod** [comment]
Looks like it's related to https://github.com/segmentio/evergreen/pull/533

**Comment by Chrischuck** [comment]
If nobody's working on this, I'd like to take this issue

**Comment by mshwery** [comment]
@Chrischuck go for it! 🙌
