### ISSUE TITLE
Add Segment's SideNav component

### ISSUE THREAD

**Issue by danielmhanover** [segmentio/evergreen#612]
First off, great work on this project - these components look awesome!

I'm wondering how one would go about building [Segment's sidenav](https://www.dropbox.com/s/ewfjgi750i26ct2/Screenshot%202019-08-25%2013.32.49.png?dl=0) with this kit. if the component is not already in the kit, would you guys be open to adding it?

**Comment by solon-aguiar** [comment]
Hi @danielmhanover,

we don't have plans to build the `sidenav` of our app in the evergreen UI. It is not a generic component that other developers can or should re-use to build their applications.

Why do you need the sidenav in a component?

**Comment by danielmhanover** [comment]
I want to create a dashboard with a sidenav. Many dashboards have them now and they are increasingly becoming the norm.

**Comment by mshwery** [comment]
The best part about `evergreen-ui` is that it's incredibly simple to build something like this yourself exactly tailored to your needs! Here's a quick example:

https://codesandbox.io/s/youthful-hermann-lmq9r?fontsize=14
