### ISSUE TITLE
Feature request/ Treeview

### ISSUE THREAD

**Issue by Larissagilliane** [segmentio/evergreen#621]
I would like to suggest a component that works as a "Treeview", it would be a component very useful for displaying large amounts of nested data. 

I didn't find any component that act like this, so would be a very good adiction for 🌲.

That's a look of how the component can be:

![Screen Shot 2019-09-05 at 18 15 02](https://user-images.githubusercontent.com/27821672/64381259-2412b680-d009-11e9-92c9-5331de12bb7a.png)

I would love help to create this component if the idea were approved.

**Comment by calumbrodie** [comment]
We had this problem and used this -> https://ant.design/components/tree/

**Comment by akleiner2** [comment]
Hi there! We haven't had a chance to prioritize a component like this just yet internally. That being said, we'll be sure to keep this in mind and circle back to this issue once we figure out our needs for a `<Tree />` component internally. 

Going to close this out for now! Let us know if you have any additional questions.
