### ISSUE TITLE
UI example

### ISSUE THREAD

**Issue by skitsanos** [segmentio/evergreen#632]
Not really an issue, just wanted to share my sandbox, maybe someone will find it handy.  I had few components missing in my own project so wrapped up some test bed on [https://codesandbox.io/s/2sr2r](https://codesandbox.io/s/2sr2r) You are welcome to fork and play around.

**Comment by calumbrodie** [comment]
Spectrum board might be a better place for this:

https://spectrum.chat/evergreen?tab=posts

This isn't an issue

**Comment by mshwery** [comment]
Closing but thanks for sharing! Feel free to repost in the spectrum channel :)
