### ISSUE TITLE
Question: Any plans to migrate React.FC?

### ISSUE THREAD

**Issue by Pasalietis** [segmentio/evergreen#642]

**Comment by mshwery** [comment]
The biggest motivation for that would be to simplify render trees using hooks like `useTheme` (I want this), and potentially shaving down the overall file size of the library.

I'm for it!

**Comment by Chrischuck** [comment]
@mshwery Is there a roadmap for this migration? I'd be happy to lend a hand

**Comment by mshwery** [comment]
@Chrischuck no roadmap specific to migrating to React.FC, but you are welcome to take a stab at it if you can find some ways to incrementally introduce it in a non-breaking way!

**Comment by mshwery** [comment]
This will be ongoing targeting @next releases for v5.
