### ISSUE TITLE
Inconsistent use of 'icon' prop in SelectMenu

### ISSUE THREAD

**Issue by calumbrodie** [segmentio/evergreen#645]
This PR:

Add optional icon to SelectMenu options https://github.com/segmentio/evergreen/pull/618

Added an optional 'icon' option to select menu options. This is a good feature in theory, but I'd argue that this prop should have been called 'image' rather than icon.

The prop 'icon' I'd have expected to add a <Icon> Component. This change forces having to use an image src, where this usage doesn't happen anywhere else in the library.

I propose changing this prop to 'image' and adding an optional 'icon' prop that would add an <Icon> to the option.

An alternative would be to relax the 'label' proptype to allow 'node', which would allow the end user to do whatever they wanted in this context.

**Comment by mshwery** [comment]
I tend to agree, though we'd have to support this prop name now unless we want to introduce a breaking change.

I agree that the label could actually be a node – that way it's infinitely customizable. But that could yield other unknown problems.

**Comment by calumbrodie** [comment]
Not wanting to introduce a breaking change shouldn't prevent us from rectifying the mistake (even if it means only merging it prior to a major release).

In any event I think the wider issue here would be making the use of icon/labels and 'option renderers' more consistent between the various components with a goal of making things more generally flexible.

I understand the push for v5 at the moment is the move to ts and this seems to be where all the development effort is going, but the state of the issues backlog here and the lack of communication makes it hard to know where contribution to this project would be welcome.

I understand the time it takes to maintain an open source project like this and appreciate all the effort that has gone into this library, it would be good to be able to contribute.

**Comment by akleiner2** [comment]
There is now an `itemRenderer` for `SelectMenu` which should be able to support this.
