### ISSUE TITLE
Initials in Avatar not centered

### ISSUE THREAD

**Issue by tohjustin** [segmentio/evergreen#673]
## Description

In [v4.21.3](https://github.com/segmentio/evergreen/releases/tag/v4.21.3), the [Avatar](https://evergreen.segment.com/components/avatar) component doesn't seem to be centering the initials anymore.

<img width="1111" alt="Screen Shot 2019-11-06 at 22 23 06" src="https://user-images.githubusercontent.com/8844886/68364871-113d6080-00e4-11ea-9b26-d1f87ebfb36c.png">

**Comment by mshwery** [comment]
Thanks for reporting! I've got a fix proposed in PR #675
