### ISSUE TITLE
SelectMenu's input element not getting styled correctly

### ISSUE THREAD

**Issue by tohjustin** [segmentio/evergreen#674]
## Description

In [v4.21.3](https://github.com/segmentio/evergreen/releases/tag/v4.21.3), the [SelectMenu](https://evergreen.segment.com/components/tooltip/) component's input element seems to be "inheriting" the browser's default styling which makes it look different from previous releases.

<img width="1161" alt="Screen Shot 2019-11-06 at 22 29 29" src="https://user-images.githubusercontent.com/8844886/68365367-4dbd8c00-00e5-11ea-8010-55d1f86dd468.png">

**Comment by mshwery** [comment]
Thanks for reporting! I've got a fix proposed in PR #675
