### ISSUE TITLE
[Menu] Define how many elements can be displayed (overflow)

### ISSUE THREAD

**Issue by kud** [segmentio/evergreen#679]
Hello :)

On `<Menu>`, it could be great to have an overflow and define how many items you want to be displayed on the screen, because I've got like 200 items and it takes the whole website.

Is there any way to do this?

Thank you.

**Comment by mshwery** [comment]
`Menu` doesn't support additional ui-box props unfortunately, so you would have to wrap your `Menu` in `Pane` and specify the maxHeight and overflow props on that component instead. Would that work?

**Comment by akleiner2** [comment]
Going to close this issue out, but let us know if the recommendation specified doesn't work, and we can always revisit!
