### ISSUE TITLE
Using Button > "is" with React Router Link gives PropTypes warning

### ISSUE THREAD

**Issue by andycarrell** [segmentio/evergreen#681]
Hi 👋 - when I use the button component, setting the 'is' prop to be react router link, I get a prop type warning:

_Edit - this issue might be more closely related to `ui-box` - [Box doesn't accept React components](https://github.com/segmentio/ui-box/blob/master/src/box.tsx#L28) -the correct type should be `PropTypes.elementType`_
```js
import { Link } from "react-router-dom";
import { Button } from "evergreen-ui";
...
<Button iconBefore="arrow-left" is={RouterLink} to="/manage/accounts">
    Accounts
</Button>
```
[The docs tend to suggest this is recommended:](https://evergreen.segment.com/components/button)
![image](https://user-images.githubusercontent.com/22784983/69303726-f130a400-0c82-11ea-8e18-1b28cd1f2781.png)

But unfortunately I get this error: 
```js
index.js:1375 Warning: Failed prop type: Invalid prop `is` supplied to `Box`.
    in Box (created by Text)
    in Text (created by Context.Consumer)
    in withTheme(Text) (created by Button)
    in Button (created by Context.Consumer)
    ...
```

More info:
evergreen-ui - v4.21.5
MacOS Mojave 10.14.6
Chrome Version 78.0.3904.97 (Official Build) (64-bit)

**Comment by tomitrescak** [comment]
Same thing with Menu.Item:

```
Warning: Failed prop type: Invalid prop `is` supplied to `MenuItem`.
    in MenuItem (created by Context.Consumer)
    in withTheme(MenuItem) (at header_authorised.tsx:96)
    in div (created by Box)
    in Box (created by Pane)
    in Pane (created by Context.Consumer)
    in withTheme(Pane) (created by MenuGroup)
```

used as 

```ts
<Menu.Item icon="badge" is={Link} to="/admin/roles/system">
    Roles
</Menu.Item>
```

**Comment by andycarrell** [comment]
Thanks @tomitrescak :)
Can repro with `TableRow` too - seems to be either these components need to avoid passing "is" down to `Text` / `Box`, or the proptype needs to be updated?

```js
index.js:1375 Warning: Failed prop type: Invalid prop `is` supplied to `Box`.
    in Box (created by Pane)
    in Pane (created by Context.Consumer)
    in withTheme(Pane) (created by TableRow)
    in TableRow (created by Context.Consumer)
```

**Comment by tomitrescak** [comment]
Hi, is it possible to have a look at this issue? I tried to look into code, but I am not sure which component should "swallow" the "is", or does it need to be added to all of them.

**Comment by andycarrell** [comment]
I think it might be ["box" from ui-box](https://github.com/segmentio/ui-box/blob/master/src/box.tsx#L28) - Box doesn't accept React components -the correct type should be `PropTypes.elementType`

**Comment by tomitrescak** [comment]
Yah, I was just exploring that, but I cannot find the definition of that propType in the ui-box repo.

**Comment by andycarrell** [comment]
This PR in ui-box has been merged: https://github.com/segmentio/ui-box/pull/51 & released https://github.com/segmentio/ui-box/releases/tag/v3.0.3

So to close this I believe Segment would need to update to version 3.0.3 🤔

**Comment by mshwery** [comment]
Yeah I think we'd also have to patch a `ui-box@^2.0.0` version to pull it into evergreen without a breaking change. The breakage in `ui-box` is that classnames no longer use the 📦 emoji. Some folks may be relying on classnames in weird ways so we don't want to disrupt that.

If that's not do-able we can sync up on whether or not it's worth a major version change in `evergreen-ui`.

**Comment by andycarrell** [comment]
Agreed - a patch on v2 would allow consumers to pull it into their project. Is the best way to do that to open a PR for the same fix against the v2 branch in `ui-box`

**Comment by andycarrell** [comment]
Closing this issue as Box prop-type in `ui-box` has been fixed in both version 2 & 3. - upgrading to https://github.com/segmentio/ui-box/releases/tag/v2.1.3 should resolve.
