### ISSUE TITLE
Dialog: no way to easily change the button order?

### ISSUE THREAD

**Issue by t7m** [segmentio/evergreen#682]
Regarding the [dialog](https://evergreen.segment.com/components/dialog): Not everyone wants the "confirm" button on the right and the cancel button on the left. Not everyone wants these things in the lower-right corner, either.

I had to hijack onOpenComplete to move things around and restyle them (code below). Was there an easier way? Also, it's just about impossible to select DIVs in the dialog because of the emoji class names. If there's a better way to do this, let me know. I'd suggest that the code should allow something as basic as switching the order of the buttons. As for centering the buttons or making other modifications, it would be nice if things were more easily selectable.

```
          onOpenComplete={
            () => {
              window.$( ".css-1dccw9w > div:last > div" ).css( "float", "none").css( "textAlign", "center")
              window.$( ".css-1dccw9w > div:last > div button:first" ).insertAfter( window.$( ".css-1dccw9w > div:last > div button:last" ) );
              window.$( ".css-1dccw9w > div:last > div button:first" ).css( "marginRight", "8px" );
              window.$( ".css-1dccw9w > div:last > div button" ).css( "width", "120px" ).css( "textAlign", "center" ).css( "display", "inline-block" );
            }
          }
```

**Comment by lBilali** [comment]
instead of doing that I would have removed default footer and add buttons on the content
and if you need to reuse it multiple times create a custom component wrapping the dialog with hidden footer and add your own footer
I did not try this but I don't see why it should not work

**Comment by t7m** [comment]
Yes, but the default footer made easy use of the ok/cancel buttons. Changing the order of the buttons seems like a better configuration option.

**Comment by Chrischuck** [comment]
If this is something that the maintainers would like to support, I'd be more than happy to take this as a first issue.

**Comment by mshwery** [comment]
All of the functionality needed to compose the buttons however you like is already there – as @lBilali suggested. 

Rather than bloating the convenience props to accommodate many different configurations, I think it's preferable to use the "I know what I'm doing" approach and render the content and buttons yourself.

Open to other thoughts/opinions of course!

**Comment by akleiner2** [comment]
Going to close this thread out - there are workarounds to this, but let us know if you still have issues with the approaches mentioned!
