### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by tomitrescak** [segmentio/evergreen#685]
I absolutely love Evergreen, but with the lack of activity I am wondering what is the plan for this package? Do you plan to support it in the future? I am starting a new project that will run for several years and it would be great to know. sorry for such a direct question.

**Comment by maraisr** [comment]
This project is far from dead! I don't work here, but I have been following it for quite some time. It's just very mature, so doesn't need a lot of tinkering. There is however currently a huge project, where they are re-writing it in TypeScript, which is probably why master looks quite empty in terms of activity lately.

**Comment by tomitrescak** [comment]
Wow, typescript rewrite! Now that’s all I needed to hear;) I’m THAT kind of person ;)

**Comment by tomitrescak** [comment]
Mature or not mature though it would be great to head some kind of response to PRs or issues targeting API functionality that clearly does not work. Throw a dog a Milestone 3.0 bone or something ;)

**Comment by mshwery** [comment]
Hi @tomitrescak! Evergreen is far from dead :) 

@maraisr is pretty spot on – the library is fairly stable and we are considering/planning next versions (v5). Internally, Segment uses Evergreen heavily, so it's not going anywhere. We actively respond to bugs and maintenance, but new features are a little slower given that we need to consider how to incorporate them in a holistic way across the library.

That said, we do have an initiative to migrate to TypeScript (the `index.d.ts` types are a stop-gap until we get there) and we'll be rethinking a few patterns in future versions (e.g. hooks, ref forwarding, easier customization/styling)
