### ISSUE TITLE
Make Blueprint a Peer dependency

### ISSUE THREAD

**Issue by seanemmer** [segmentio/evergreen#688]
Blueprint Icons are currently adding 300kb to my final build, despite the fact that I have opted out of using them in favor of FontAwesome.

This has been discussed previously in:

https://github.com/segmentio/evergreen/issues/458
https://github.com/segmentio/evergreen/pull/525

I think an easy stopgap solution is to transition blueprint from being a required dependency to a peer dependency, so that those of us who are opting out of the icon set don't have the overhead.

**Comment by mshwery** [comment]
Unfortunately it could significantly break parts of evergreen today because of internal use of the `Icon` component. We do want to implement support for tree-shaking icons though.

**Comment by mshwery** [comment]
Closing this issue since moving to a peer dep isn't possible in v4, but we are exploring complete tree-shaking support in v5.
