### ISSUE TITLE
Request: Upgrade react-transition-group version

### ISSUE THREAD

**Issue by itzsaga** [segmentio/evergreen#689]
I was recently throwing a `Uncaught TypeError: this.updater.enqueueCallback is not a function` error that caused my app to crash. After digging I believe the root case was that `react-transition-group` was utilizing a different version of `react` than my project. See the `extraneous` tag below.

```
$ npm ls react
*******@0.1.0 /Users/seth/************/*******
├─┬ auth0-lock@11.18.1
│ └── react@15.6.2 
├─┬ evergreen-ui@4.21.2
│ └─┬ react-transition-group@2.9.0
│   └── react@15.6.2  extraneous
└── react@16.11.0 
```

When I looked into the `react-transition-group` project it looks like they moved `react` and `react-dom` from `dependencies` to `peerDependencies` at v3.0.0. In my quick testing, clone `evergreen`, change the version to `^3.0.0` and run the tests the only errors are JSDoc and unused import related so I believe this is a safe upgrade.

Anything else I would need to look for or should I open up a PR?

**Comment by mshwery** [comment]
[`react-transition-group@2.9.0`](https://github.com/reactjs/react-transition-group/blob/v2.9.0/package.json#L52-L55) has react and react-dom as peer deps. I don't think that's what's introducing your duplicate react versions. I think it's [`auth0-lock`](https://github.com/auth0/lock/blob/v11.18.1/package.json#L105-L106).

Try removing all versions of `react` and `react-dom` from your lockfile and re-installing. Not sure if that works the same with `npm` but you should see a single version of react. I'm guessing `auth0-lock` is preventing you from using react@16
