### ISSUE TITLE
Combobox deselcts on mobile device

### ISSUE THREAD

**Issue by clarkkozak** [segmentio/evergreen#690]
- Issue and steps to reproduce.

- I'm using a Galaxy S7 and Free Adblocker Browser 72 and the following code example:
`
<Combobox
  items={ ['Autobiography', 'Anime', 'Biography', 'Classic', 'Comics', 'Crime', 'DIY (Do It Yourself)', 'Dystopia', 'Fantasy', 'Folktale', 'Historical', 'Horror', 'Humor', 'Legend', 'Memoir', 'Mystery', 'Mythology ', 'Personal Development', 'Pyschology', 'Political Science', 'Romance', 'Satire', 'Science fiction', 'Science', 'Short', 'Spirituality / Religion', 'Textbook / Reference Book', 'Thriller', 'Western', 'Other']}
  onChange={selected => console.log(selected)}
  placeholder="Genres"
  autocompleteProps={{
    // Used for the title in the autocomplete.
    title: 'Genres'
  }}
/>
`

I'm unsure if it happens on any other mobile device since I can only test on my own, yet I've replicated it on the Combobox example at https://evergreen.segment.com/components/combobox/

- Expected.
When selecting a value on a large combobox, I can scroll through the options on a mobile device

- Actual.
When scrolling through the options, it will select when the finger leaves a select box

**Comment by mshwery** [comment]
Nice find! Is this specific to Evergreen or is it happening in `downshift` too (which is what Evergreen is wrapping here)?

**Comment by juxley** [comment]
Hi @mshwery ! Thank you for your reply and patience.

I took a deeper look into this, and it seems to be specific to Evergreen. Here's an example of `downshift` working properly; although slightly different.

https://codesandbox.io/s/github/kentcdodds/downshift-examples/tree/master/?module=%2Fsrc%2Fordered-examples%2F02-complete-autocomplete.js&moduleview=1

**Comment by juxley** [comment]
Hello again!

Here's where I think it goes wrong:

https://github.com/segmentio/evergreen/blob/e4e350239c782843d6c2ae7d68119a28a384bf8e/src/autocomplete/src/Autocomplete.js#L224

I tried playing with the events to see if anything would change yet I couldn't figure it out.

**Comment by mshwery** [comment]
@juxley seems like we may need to remove `onMouseUp` and `onTouchEnd` to replace them with `onClick`?

**Comment by mshwery** [comment]
Or maybe we should remove the `onMouseUp` and `onTouchEnd` altogether?

**Comment by juxley** [comment]
I'm unsure. When I attempted to do that, than functionality stopped working. Did you attempt to replace or remove it?

**Comment by mshwery** [comment]
Hm. Yeah it breaks in different ways. 

I think it might be a bug in downshift still (it's applying mouse event props to the items instead of touch events on mobile) but it might be quite specific to this usage.

**Comment by juxley** [comment]
With the example provided above, `downshift` doesn't have this bug. In the example above they use an `onChange`. I'm unsure what's wrong.

I suggest to write this component. This component is quite important for forms on mobile devices and long lists. If I have some free time I'll give it a shot! :smile: 

Thank you for your time.

**Comment by mshwery** [comment]
I think this will be fixed once #793 lands
