### ISSUE TITLE
Feat: How about `append` compatibility?

### ISSUE THREAD

**Issue by wangcch** [segmentio/evergreen#691]
**`append`** compatibility data:
![compatibility data image](https://user-images.githubusercontent.com/28584349/71229565-fab03900-2320-11ea-8530-3183f1401ab4.png)
https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/append

**`appendChild`** compatibility data:
![image](https://user-images.githubusercontent.com/28584349/71229953-97bfa180-2322-11ea-914c-38a6b5912b63.png)
https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild

https://caniuse.com/#feat=mdn-api_parentnode_append
https://caniuse.com/#feat=mdn-api_node_appendchild

Like `Portal` / `Toaster` don't need to append multiple nodes and `DOMString` objects. Can we consider using **`appendChild`** to get more compatibility?

I am ready to submit pr. But I see the limit[(Prefer append over appendChild)](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/prefer-node-append.md). So I want to consult in advance.

Thanks～🙋‍♂️

**Comment by mshwery** [comment]
PRs welcome!
