### ISSUE TITLE
Downshift Actions unavailabe in Autocomplete Typedef

### ISSUE THREAD

**Issue by seanemmer** [segmentio/evergreen#696]
Downshift comes with a number of actions for controlling autocomplete functionality:

https://github.com/downshift-js/downshift#actions

These are not included in the typedef of the Autocomplete component's render-props.

Happy to put together a PR :)

**Comment by seanemmer** [comment]
Resurfacing this.  Is a PR welcome?

**Comment by mshwery** [comment]
@seanemmer yes!

**Comment by seanemmer** [comment]
Pull request created:

https://github.com/segmentio/evergreen/pull/766

**Comment by akleiner2** [comment]
Closing out due to inactivity. Please re-open and re-visit! Thank you!
