### ISSUE TITLE
Firefox Inconsistencies: isInvalid not working

### ISSUE THREAD

**Issue by itsdarrylnorris** [segmentio/evergreen#697]
### Problems:
- The `TextInputField` component  is very hard to read on Firefox browser. See the screenshot below.
- The `isInvalid` prop does not add the red color around the input field. See the screenshot below.

![Inconsistencies](https://user-images.githubusercontent.com/6808460/71709694-9922ac80-2dad-11ea-8a42-5331f4ff9ec4.png)

### Device Details:

- Evergreen version: `4.21.5`
- Browser name and version. `Firefox 71.0`
- Operating system: `Catalina 10.15`

Do you think is possible to get `isInvalid` working on Firefox? And maybe add some styles to make the input fields more readable in Firefox?

**Comment by mshwery** [comment]
I agree that the placeholder text is quite low contrast, more so on Firefox than in Chrome. However, are you sure you don't have some other styles at play?

Here's what Firefox looks like on the docsite evergreen.segment.com:
<img width="301" alt="Screen Shot 2020-01-05 at 4 22 09 PM" src="https://user-images.githubusercontent.com/710752/71787006-af13b580-2fd7-11ea-8b48-0c72a2326edd.png">

**Comment by mshwery** [comment]
Closing this issue as it's stale and was unable to repro in Firefox.
