### ISSUE TITLE
Plans to introduce a module bundler like webpack or rollup?

### ISSUE THREAD

**Issue by Chrischuck** [segmentio/evergreen#700]
Curious if there are any plans to introduce either WebPack or Rollup to build/minify the code rather than just using babel to transpile.

Reason being using a bundler can help bring down bundle sizes and remove dead code

**Comment by mshwery** [comment]
No immediate plans, but wouldn't be opposed to it.

**Comment by mshwery** [comment]
Rollup is now being used (thanks @g1eny0ung!)
