### ISSUE TITLE
UMD support

### ISSUE THREAD

**Issue by g1eny0ung** [segmentio/evergreen#714]
Are there any plans to support the UMD module? If any, I would glad to help.

**Comment by mshwery** [comment]
We currently create both esm (import/export) and commonjs (require) style modules which works quite well for a broad majority of consumers (e.g. TypeScript / babel users typically rely on the esm modules).

What did you have in mind for supporting UMD? PRs welcome! :)

**Comment by g1eny0ung** [comment]
My original idea was to integrate evergreen into [cljsjs](http://cljsjs.github.io/), which is a package set with google closure externs support, use in clojurescript. It easy to implement this with a UMD module.

I will make a PR to support UMD and try not to affect the current production build.~

**Comment by g1eny0ung** [comment]
@mshwery Hi, I already make a PR.

I use rollup to emit the UMD bundles. Include development and production versions.

In order to be able to pack, I create `index.umd.js`, it removes the `ssr` imports. But I'm not sure Is this a good way because the UMD module also supports node.js environment. Currently, I think it's not very important because we use the main entry to import the commonjs module in node.js.

`{  "main": "commonjs/index.js" }`

This PR also relates to issue #700. I also prefer to use a module bundler instead of through babel directly.
