### ISSUE TITLE
Minor: Docs typo.

### ISSUE THREAD

**Issue by xAvarice** [segmentio/evergreen#734]
https://github.com/segmentio/evergreen/blob/78cf402525b59fcac49e53236f382dba0c60256f/src/buttons/src/IconButton.js#L26

**Comment by Chrischuck** [comment]
I assume it's the `primitivie` part? Looks like it occurs on other lines as well, you can make a pr for the fix if you'd like, if not this would be a really nice first issue.

**Comment by xAvarice** [comment]
I have the fix ready but permission denied.

**Comment by mshwery** [comment]
Have you forked the repo to submit the patch?

**Comment by xAvarice** [comment]
No comrade, I was just publishing to a branch here. PR on fork now, you're assigned. Ty.
