### ISSUE TITLE
Docs: Popover Styling ClassName

### ISSUE THREAD

**Issue by xAvarice** [segmentio/evergreen#737]
I had to review the source code for Popover to figure out that className is passed via statelessProps, I realise that there's not really much wrong with that but it's at best faux-intuitive without any mention in documentation.

DOCS:
https://evergreen.segment.com/components/popover/

SRC:
https://github.com/segmentio/evergreen/blob/37d141457a82297fc2de14b252c68fa1a5e965f1/src/popover/src/Popover.js#L382

**Comment by xAvarice** [comment]
Bigger issue:

The following works and adds class:
```
  <Popover 
    statelessProps={{
      className: "TEST"
    }}
```

This CSS module via JS does not add any class to Popover :(
```
    statelessProps={{
      className: layout.popMenu
    }}
```

**Comment by xAvarice** [comment]
Going to compare to another implementation that is working for me. 

So far I have found that:
Popover passes statelessProps (where className is provided) to PopoverStateless.
PopoverStateless takes its propTypes from layers/Card
layers/Card takes its propTypes from Pane
Pane takes its propTypes from Box **(LOWEST LEVEL FOR ASSIGNMENT)**

The the lowest level for passing className 

  ```
// /src/layers/src/Pane.js
  const className = cx(
      props.className,
      glamorCss({
        ...css,
        ...hoverElevationStyle,
        ...activeElevationStyle
      }).toString()
    )

    return (
      <Box
        ..............
        {...props}
        className={className}
      />
    )
```

**Comment by xAvarice** [comment]
This works, I'm going leave another comment after this one comparing the lowest level className assignment for Icon versus Popover (Box?)

![Screenshot 2020-02-07 at 13 19 35](https://user-images.githubusercontent.com/17517508/74033206-8fdcbf00-49ad-11ea-95df-372c8bb67c85.png)

**Comment by xAvarice** [comment]
Okay, so:

Icon extends PureComponent but it does not have any props passed using the spread operator (which includes the className from Box in the case of Popover - I believe)

Button also works for passing a className, on button it has a className props type on its own class (non-inheritance)

https://github.com/segmentio/evergreen/blob/37d141457a82297fc2de14b252c68fa1a5e965f1/src/buttons/src/Button.js#L79

There is some fiddling with it regarding themedClassName but this obstructs nothing for me.

https://github.com/segmentio/evergreen/blob/37d141457a82297fc2de14b252c68fa1a5e965f1/src/buttons/src/Button.js#L126

Then className assignment to component is quite straightforward:

https://github.com/segmentio/evergreen/blob/37d141457a82297fc2de14b252c68fa1a5e965f1/src/buttons/src/Button.js#L163

**Comment by xAvarice** [comment]
I haven't done any testing but would adding the following propType to Popover and escaping statelessProps (or the same thing within statelessPopover instead) allow the className to be passed?

https://github.com/segmentio/evergreen/blob/37d141457a82297fc2de14b252c68fa1a5e965f1/src/buttons/src/Button.js#L79

**Comment by xAvarice** [comment]
Another difference would be that the css module is usually passed as

`className={MODULE.RULENAME}`

Whereas for popover to pass to statelessProps it has to be within an object, surely this should not matter? (Need to do some console.logging)

```
statelessProps={{
      className: MODULE.RULENAME
}}
```

**Comment by xAvarice** [comment]
Updated evergreen and its working now 🤷🤷‍♂️🤷🤷‍♂️🤷🤷‍♂️🤷🤷‍♂️🤷🤷‍♂️🤷🤷‍♂️🤷🤷‍♂️🤷

**Comment by mshwery** [comment]
@xAvarice do you know which version you were on before?
