### ISSUE TITLE
Table issue with header row not aligning with content rows.

### ISSUE THREAD

**Issue by cstrat** [segmentio/evergreen#748]
Unsure if I am doing something wrong, but I can't ever get my header row to align with the content rows. It is always off... either too far left or right.
Even copying the example code from the documentation I can't get it to align:

![image](https://user-images.githubusercontent.com/4209076/75415018-72808c80-597e-11ea-9742-68213b7fc9b4.png)

https://codesandbox.io/s/evergreen-table-position-bug-i2el8

I've tried wrapping the table in a <Pane> but that doesn't seem to help.

In the code-sandbox linked above, how can I fix that alignment issue? Any ideas?

In this one, I've removed the search header and added more columns, still not working.

https://codesandbox.io/s/evergreen-table-position-bug-more-columns-ffgjd

![image](https://user-images.githubusercontent.com/4209076/75415194-fb97c380-597e-11ea-9dc8-7101139a3dea.png)

The red boxes are just drawn on top and aren't exact - but you can see the gap changes with each column, typically getting more exaggerated with the distance from the left.

**Comment by Chrischuck** [comment]
What browser are you on?

I'm on chrome 80.0.3987.87

<img width="665" alt="Screen Shot 2020-03-01 at 15 06 54" src="https://user-images.githubusercontent.com/13311268/75635869-84f10500-5bce-11ea-81a5-791ac3025fa3.png">

<img width="754" alt="Screen Shot 2020-03-01 at 15 07 06" src="https://user-images.githubusercontent.com/13311268/75635870-86223200-5bce-11ea-9ed6-20793b24614e.png">

**Comment by cstrat** [comment]
I'm using Brave browser (current version).

**Comment by Chrischuck** [comment]
Super weird...I'd expect all of those browsers to have the same behavior... Would it be possible for you to inspect those elements and try to highlight where exactly the discrepancy in width is stemming from?

**Comment by cstrat** [comment]
I think I found where the issue is coming from... but can't work out why it is displaying inconsistently...

See this extra padding on the right (red box is mine).
![image](https://user-images.githubusercontent.com/4209076/75645257-41af9880-5c99-11ea-94e6-891f1805e412.png)

In my browser when checking:

- All the header cells are equal width: 295.25 (1181px)
![image](https://user-images.githubusercontent.com/4209076/75645404-eaf68e80-5c99-11ea-8e94-c495704de3cd.png)
- All the content cells are equal width: 299.5 (1198px)
![image](https://user-images.githubusercontent.com/4209076/75645412-f1850600-5c99-11ea-8a49-83a722a5c31c.png)

- 17px difference, which is the same as that right-padding.

![image](https://user-images.githubusercontent.com/4209076/75645322-9eab4e80-5c99-11ea-9d03-d70791d95233.png)

My code doesn't add any padding:
```
<Table>
  <Table.Head>
    <Table.TextHeaderCell>Date</Table.TextHeaderCell>
    <Table.TextHeaderCell>User</Table.TextHeaderCell>
    <Table.TextHeaderCell>Entry</Table.TextHeaderCell>
    <Table.TextHeaderCell>Data</Table.TextHeaderCell>
  </Table.Head>
  <Table.Body>{pages}</Table.Body>
</Table>
```

**Comment by cstrat** [comment]
I am seeing the same thing in the code-sandbox examples from my original post too...

![image](https://user-images.githubusercontent.com/4209076/75645504-4163cd00-5c9a-11ea-9c6a-bf52bbd1c832.png)

**Comment by cstrat** [comment]
I can confirm that if I simply delete the 17px right padding class in the inspector `📦pr_17px` the table aligns perfectly...

https://github.com/segmentio/evergreen/blob/326c4a2cc283b89b76a410d4d7809e62b949f685/src/table/src/TableHead.js#L48

This looks to be the culprit?

**Comment by mshwery** [comment]
It's there to account for the table scroll bar, not the window scrollbar. 

https://github.com/segmentio/evergreen/blame/21feaa5491752a8f612ec123312b35b980ff709f/src/table/src/TableHead.js#L15-L16

**Comment by cstrat** [comment]
So strange though, I checked and my windows settings.
I've toggled this on/off and done full reboot in case the browser doesn't honor the setting immediately. No difference.

There is no scrollbar in the table in any examples where I am seeing the incorrect padding.

![image](https://user-images.githubusercontent.com/4209076/75724488-9d7a3000-5d32-11ea-8168-2946f6664c6a.png)

**Comment by cstrat** [comment]
I updated my comment above.
Looking at the docs - it does incorrectly appear there too - only where there is no scrollbar in the table as @mshwery pointed out...

Wrong. ❌
![image](https://user-images.githubusercontent.com/4209076/75731382-9f002400-5d43-11ea-939c-ae90299ea636.png)

Right. ✔
![image](https://user-images.githubusercontent.com/4209076/75731433-bdfeb600-5d43-11ea-8ed4-aa4c365bcb5d.png)

**Comment by cstrat** [comment]
> What browser are you on?
> 
> I'm on chrome 80.0.3987.87
> 
> <img alt="Screen Shot 2020-03-01 at 15 06 54" width="665" src="https://user-images.githubusercontent.com/13311268/75635869-84f10500-5bce-11ea-81a5-791ac3025fa3.png">
> 
> <img alt="Screen Shot 2020-03-01 at 15 07 06" width="754" src="https://user-images.githubusercontent.com/13311268/75635870-86223200-5bce-11ea-9ed6-20793b24614e.png">

I dont know how you got this to work.
I've even used browser test suites which test websites in VMs (http://browsershots.org/ and https://www.browserling.com/) and I get the same alignment issues.

**Comment by cstrat** [comment]
On my Macbook I don't have the issue. The 17px scrollbar class does not get applied.

Windows seems to be the common thread here... are you using Windows?

**Comment by Chrischuck** [comment]
I think we're all on macs, let me boot up my windows machine and see what happens after work. I'll update you tonight!

**Comment by Chrischuck** [comment]
@cstrat I apologize for the late reply, I came down with a cold the last few days...

Anyway, I was able to reproduce this instantly on a windows machine... so it seems like a pretty common windows issue. I'll dig into it more when I get some time

**Comment by cstrat** [comment]
All good @Chrischuck, no need to explain - hope you're better.

I spent a good amount of time trying to work it out but was left pulling my hair out. 😭

**Comment by cstrat** [comment]
Closed this one. I've opened a more thorough report in #1137
