### ISSUE TITLE
How to change the position of the toaster element?

### ISSUE THREAD

**Issue by MrScX** [segmentio/evergreen#764]
I'm trying out evergreen for a new project and it seems very fresh. Loving it so far!

But I can't seem to position the toaster element from its default center position. And there doesn't seem to be anything in the docs about positioning it either. I want to position it to the top right instead of dead center. I can do it by overriding the CSS but is there any evergreen way of doing it? Any props or options I'm missing here?

**Comment by mshwery** [comment]
Dupe: https://github.com/segmentio/evergreen/issues/759

Let's centralize the discussion. There is a PR open if you want to provide some feedback/review: https://github.com/segmentio/evergreen/pull/760
