### ISSUE TITLE
SelectMenu inside form triggers submit event

### ISSUE THREAD

**Issue by taviroquai** [segmentio/evergreen#767]
## In the case of a bug report 🐞

- Issue and steps to reproduce.

SelectMenu component inside form triggers form submit event when clicking the component for the first time.

```jsx
<form>
 <SelectMenu />
</form>
```

This triggers a form submit.

- Versions.
"react": "^16.13.1",
"evergreen-ui": "^4.24.0",

- Browser name and version.
Chrome 80.0

- Operating system.
Ubuntu 18.04

**Comment by Chrischuck** [comment]
@taviroquai 
I assume you're using the `SelectMenu` like the [docs](https://evergreen.segment.com/components/select-menu) say where you use a button for the `SelectMenu`.

According to [this](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit_event), from what you're experiencing, and what I've tested, in a form element whenever a button or an input with `type="submit"` is clicked, it will submit the form.

One workaround is the following: making the button an a tag (or anything other than button) for that matter. 
```
    <form>
        <SelectMenu
          title="Select name"
          options={
            ['Apple', 'Apricot', 'Banana', 'Cherry', 'Cucumber']
              .map(label => ({ label, value: label }))
          }
        >
          <Button is="a">{'Select name...'}</Button>
        </SelectMenu>
      </form>
```

**Comment by mshwery** [comment]
And if you set `<Button type="button">` does it still happen?

Html button `type` behavior applies:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

**Comment by Chrischuck** [comment]
@mshwery I tested it on my end and setting `type="button"` works as well.

**Comment by mshwery** [comment]
Perfect – this is standard html behavior. It's expected and working correctly!

**Comment by taviroquai** [comment]
Guys you are right, using type="button" solves the submit event problem.

Sometimes "we" rely so much on the library that we forget that it must follow the standards... my bad! :)

Thanks!
