### ISSUE TITLE
Publicly Hosted Storybook

### ISSUE THREAD

**Issue by colinking** [segmentio/evergreen#772]
Any thoughts on hosting Evergreen's storybook somewhere on `evergreen.segment.com`? Personally, it'd be helpful to compare a local branch against master to see if I've broken any existing behavior with changes.

Possibly a re-request of: https://github.com/segmentio/evergreen/issues/11

**Comment by jasonbarry** [comment]
@colinking if this repo builds storybook in its CircleCI pipeline, then you could integrate it with [FeaturePeek](https://featurepeek.com) to get a storybook build on every PR (shameless plug). It's completely free for open source projects like this one.

**Comment by akleiner2** [comment]
We had this set-up for v6, but I'm going to look into getting this set up for running against PRs into `master`. Closing out for now
