### ISSUE TITLE
New to Evergreen: Table questions

### ISSUE THREAD

**Issue by jibberishclient** [segmentio/evergreen#774]
Hello, I just wanted to start off by thanking you guys for the awesome work on this component lib. I just had a few questions about the Table component as follows:

A. Is it responsive? I'd basically like the table to consume 100% of the available space and if that means it has to truncate text then so be it (I'd actually prefer it to wrapping) so long as the menu button is preserved at the right hand side.

B. Is there support for some kind of pagination component at the bottom instead of virtualized scrolling? It would be nice to have a table footer with things like next page, back page, choose rows per page, showing items 1-5 of 20 for example.

C. Is there a global header(s) I can use in addition to the column headers? I'd like to leave my column headers in tact so I can toggle sorting but I want to have a table title and global table search filter instead of by column sitting at the top like so:

![image](https://user-images.githubusercontent.com/11995299/79129300-f944c980-7d72-11ea-9b4c-065ec68cc237.png)

**Comment by Chrischuck** [comment]
Hi @jibberishclient 
To answer your questions:

A) Yup! It's responsive and will adjust to the size of the container

B) Unfortunately, no pagination support :(

C) You _could_ just add another table header:
<img width="847" alt="Screen Shot 2020-04-16 at 17 47 18" src="https://user-images.githubusercontent.com/13311268/79520093-ab49f300-800a-11ea-8013-c11c3b58daa1.png">
<img width="439" alt="Screen Shot 2020-04-16 at 17 46 42" src="https://user-images.githubusercontent.com/13311268/79520107-b56bf180-800a-11ea-91b2-2497464d41cd.png">

But there's no official way of doing this.

**Comment by jibberishclient** [comment]
Thanks Chris I actually figured that out a little while back to add another header. I did have some additional questions though.

First off I notice some weird kind of offset between the last row and the table border, which is definitely kinda weird given that the styles don't show any indication of it.

![image](https://user-images.githubusercontent.com/11995299/79597403-36c98f80-80b0-11ea-9877-c957a21b39a1.png)

Secondly, I noticed that at smaller widths tables can be come misaligned. I'm assuming this is probably due to the fact that the search header seems to have some kind of a min width. But definitely worth noting. That being said, I know evergreen isn't really supposed to be responsive, but I was just wondering what layout do you guys use to ensure that this doesn't happen? I see a 1024px min width and some auto margins but I'm not sure on the specifics and I'm not sure when and why.

![image](https://user-images.githubusercontent.com/11995299/79597757-d424c380-80b0-11ea-9493-56dbbbb265e7.png)

**Comment by mshwery** [comment]
>but I was just wondering what layout do you guys use to ensure that this doesn't happen?

Late answer: columns in the header and in the rows generally should have the same width or flex props assigned. It intentionally behaves a bit different than native table elements (though we may reevaluate this as it's not the easiest component to work with).
