### ISSUE TITLE
Scrolling: Autogrow Textarea and Scrollbars

### ISSUE THREAD

**Issue by jibberishclient** [segmentio/evergreen#775]
I have 2 questions pertaining to scrolling:

A. Is there a 3rd party lib you recommend for auto growing a text area? Such that when I hit enter the scrollbar does not appear, rather the height of the textarea becomes larger.

B. Is there a 3rd party lib you recommend for better scrollbars that are consistent on different platforms and browsers? I'm looking for a really thin mobile style scrollbar that isn't intrusive or jarring on overflow.

**Comment by jibberishclient** [comment]
I found a 3rd partly lib but I think the text area should come with a prop to set the resize style for the underlying textarea element.

**Comment by mshwery** [comment]
Given that you can bring your own library to apply this sort of behavior I'm going to close out the issue. If there's significant demand or use-cases for us to bring it into Evergreen we'll consider it! cc @akleiner2 @colinlohner
