### ISSUE TITLE
Badge Superscript/Subscript

### ISSUE THREAD

**Issue by jibberishclient** [segmentio/evergreen#776]
The badge doesn't appear to handle badges correctly, when dealing with subscripts and superscripts? Can you guys look into this? I'd definite like to use superscripts and subscripts in my badges.

![image](https://user-images.githubusercontent.com/11995299/79135394-4168e980-7d7d-11ea-9dbc-759d7982e6af.png)

**Comment by Chrischuck** [comment]
Can do after work 😉

**Comment by jibberishclient** [comment]
Much appreciated. If I had to guess, looks like a use of absolute sizing/positioning. Didn't really look at the source though.

**Comment by mshwery** [comment]
I think it's somewhat expected that if you use more nuanced content that has JSX (rather than just a string literal) you may have to tweak the badge styles.

You can easily solve for this by adding `height='auto'` or `lineHeight='normal'` if you want.

**Comment by Ankit27Agg** [comment]
can anyone tell me that how do you run the code

**Comment by mshwery** [comment]
Closing since you can achieve this through Box css props on the `Badge` component itself.
