### ISSUE TITLE
FormField error icon

### ISSUE THREAD

**Issue by ghost** [segmentio/evergreen#780]
The error icon in `FormField` displays an error icon regardless of what is passed to `validationMessage` unless you specify null. Instead it should render if `validationMessage` isn't falsy. In other words, if an empty string for example is supplied, it should render nothing.

**Comment by Chrischuck** [comment]
I've come across this bug(or is this desired?) as well, happy to make a fix for it @mshwery @akleiner2

**Comment by jibberishclient** [comment]
On that same note it would be nice if you made FormField wrappers for the other form fields too not just text field. I'm using formik and the single component form field is a live saver, otherwise I'd need to destructure some of the props to the input and others to FormField that wraps it.

**Comment by jibberishclient** [comment]
On second thought, I think validationMesssge should be completely ignored unless isInvalid is true

**Comment by mshwery** [comment]
>validationMesssge should be completely ignored unless isInvalid is true

I agree! cc @akleiner2 @colinlohner

**Comment by colinlohner** [comment]
That makes sense to me

**Comment by jackcwu** [comment]
Me and @tcho0501 are on this

**Comment by akleiner2** [comment]
Closing out due to inactivity - please feel free to re-open / take a stab at this if there's availability!
