### ISSUE TITLE
CSS Baseline

### ISSUE THREAD

**Issue by jibberishclient** [segmentio/evergreen#784]
Out of the box, the body has some margin/padding and incorrect styles. Like MUI, I think evergreen should ship with a CSSBaseline component to override the default CSS and pave the way for Evegreen by removing all this padding, creating a good base layout, and setting default colors and fonts.

**Comment by mshwery** [comment]
Evergreen isn't opinionated about how or what css normalizers/resets you apply, and that lies beyond it's responsibility. Each app/site probably is using their own version of a reset, and if Evergreen shipped with one it could conflict in unintentional ways. Closing for now – thanks!
