### ISSUE TITLE
Table Issues

### ISSUE THREAD

**Issue by ghost** [segmentio/evergreen#787]
@Chrischuck I actually figured that out a little while back to add another header. I did have some additional questions though.

First off I notice some weird kind of offset between the last row and the table border, which is definitely kinda weird given that the styles don't show any indication of it.

![image](https://user-images.githubusercontent.com/11995299/79597403-36c98f80-80b0-11ea-9877-c957a21b39a1.png)

Secondly, I noticed that at smaller widths tables can be come misaligned. I'm assuming this is probably due to the fact that the search header seems to have some kind of a min width. But definitely worth noting. That being said, I know evergreen isn't really supposed to be responsive, but I was just wondering what layout do you guys use to ensure that this doesn't happen? I see a 1024px min width and some auto margins but I'm not sure on the specifics and I'm not sure when and why.

![image](https://user-images.githubusercontent.com/11995299/79597757-d424c380-80b0-11ea-9493-56dbbbb265e7.png)

_Originally posted by @jibberishclient in https://github.com/segmentio/evergreen/issues/774#issuecomment-615375858_

**Comment by mshwery** [comment]
The column alignment issue is because you aren't specifying widths on the flex table columns and header. 

It doesn't behave like a normal table would, so you do have to take a little bit more control to get similar behavior.

As for the border issue – can you link us to a reproduction of the problem (codesandbox.io or other)?

**Comment by jibberishclient** [comment]
Hey @mshwery this is actually a screenshot of the docs site. So I don't have an example to provide but one would assume it comes from the EnhancedTable example source.

**Comment by jibberishclient** [comment]
On that same note, I'm pretty sure the table even divides the flex space unless you specify otherwise as in the case of the overflow menu column with flex none and absolute width. One would assume that the search header might have some strange setup as well.

Again this is the docs site, I simply resized the container in chrome tools to show the effects a little better as you might see it in a Codesandbox or smaller screens. I know evergreen isn't supposed to be responsive, and that's totally fine given the fact that my application is a bunch of table data. But I'd really like to know what you're using for the page layout so I can optimally display the data without any issues.

**Comment by mshwery** [comment]
>I'm pretty sure the table even divides the flex space unless you specify otherwise as in the case of the overflow menu column with flex none and absolute width

The table will divide the flex space evenly, depending on how the content fills the flex containers. If it varies between the header and the rows, the columns will not stay aligned if you don't specify a width (unlike native table elements which maintain consistency in columns).

**Comment by jibberishclient** [comment]
So how exactly would I go about this? I specified flex="none" on the last overflow menu column as done in the example? Shouldn't the other columns divide the rest of the space evenly?

**Comment by cstrat** [comment]
The alignment issue is the same issue I posted here #748 - strangely it appears to primary impact Windows clients not Mac.

**Comment by jibberishclient** [comment]
Hmmmm that's very strange ... did you get an update on that?

**Comment by jibberishclient** [comment]
Honestly, I'm only really using evergreen for the table UI and overflow menu popovers, so this is a huge dealbreaker for me. I hope someone fixes it soon 🙏

**Comment by cstrat** [comment]
I think the issue isn't as straight forward as I hoped.
Check the thread, there are a couple reproductions of the issue which look similar to what you've said.

I haven't tried to fix it further myself yet - at the moment I am only using `<Table>` for a log feed which isn't bothering me too much. Plus 50% of my time I am on a mac where it looks fine.

**Comment by jibberishclient** [comment]
@cstrat @mshwery A couple things I noticed in the source:

First in src/table/src/TableHeaderCell.js line 13: 

    return <TableCell overflow="visible" borderBottom={null} {...this.props} />

You'll notice that overflow is visible, which will cause the headers to display beyond the bounds of the table, even if the width is too small to accommodate them. Instead they too should use the ellipsis style as seen in src/table/src/TextTableCell.js:

```
const ellipsis = {
  overflow: 'hidden',
  textOverflow: 'ellipsis',
  whiteSpace: 'nowrap'
}
```

Secondly is src/table/src/SearchTableHeaderCell.js on line 92:

          size={300}

It has an absolute size. This of course if left unchanged will offset the headers that follow as seen in the image earlier in the issue thread. This should probably be changed as well.

**Comment by jibberishclient** [comment]
Is there any update on this header issue as well as the extraneous border?

**Comment by mshwery** [comment]
We have no plans to prioritize this work just yet, and I believe there are simple workarounds for both (e.g. passing css props to the table) – let us know if you cannot use ui-box css props or `style`/classname to fix this issue (seems isolated to Windows?).

As always, PRs are welcome!

**Comment by akleiner2** [comment]
Going to close out due to inactivity! Always happy to accept incoming PRs for minor releases 👍
