### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by jibberishclient** [segmentio/evergreen#789]
I realize that evergreen isn't responsive nor it it supposed to be. But I was wondering what exact layout (margin, padding, width, min width, max width, alignment, etc.) is used in the docs site such that elements don't collapse and break. What do you generally recommend?

**Comment by mshwery** [comment]
Hey! I would recommend posting questions like this to the community in our Spectrum channel.

**Comment by jibberishclient** [comment]
Ok I've done that, but it appears to not be that active. Is there any general advice you can give?

On a separate note but still in regards to CSS, I'd like to call your attention to #784. I think Evergreen should ship with some default styles on the body namely to remove the default padding, margin, and any other base styles while adding base styles pertaining to Evergreen like fonts and such.

**Comment by mshwery** [comment]
Thread here for posterity:
https://spectrum.chat/evergreen/help-me/base-layout~8f664a3f-4a1e-4ca8-9d6d-3bf9ae5b89f6
