### ISSUE TITLE
TreeshakeableIcon PropTypes trigger React Warning

### ISSUE THREAD

**Issue by seanemmer** [segmentio/evergreen#794]
Evergreen version: 4.26.0
React version: 16.13.0

Seeing this warning in my browser console (Firefox) upon loading app with Evergreen:

`Warning: forwardRef render functions do not support propTypes or defaultProps. Did you accidentally pass a React component?`

Referencing Icon.js line 96

**Comment by mshwery** [comment]
This is resolved by https://github.com/segmentio/evergreen/pull/791
