### ISSUE TITLE
Unable to disable MenuItem

### ISSUE THREAD

**Issue by dustincjensen** [segmentio/evergreen#796]
## Issue

In the [documentation](https://evergreen.segment.com/components/menu) for `Menu` it mentions the following.

`Arrow keys within the menu will cycle through all of the menu items and skip disabled items.`

However, by default you cannot disable a `MenuItem`.
If you set the `is` property to make the `MenuItem` a `Button` then you can, but then you have to mess with padding and widths.

## Suggestion

- Update the documentation to have an example of the suggested approach to disable a menu item.

**Comment by colinlohner** [comment]
This has been fixed in v5.0.6
