### ISSUE TITLE
Production build is broken

### ISSUE THREAD

**Issue by gohyifan** [segmentio/evergreen#807]
Hi team evergreen, my production build is showing this error in the console but the development build works fine in localhost.

![error.png](https://i.imgur.com/mnaWFVI.png)

Steps to reproduce the bug:
1. Clone my repo here: https://github.com/gohyifan/openflow
2. Run `yarn install` and `yarn start`
3. See that it works fine in localhost.
4. Visit [production](https://openflow.herokuapp.com/) and see that it's broken.

Environment:
OS: macOS Catalina 10.15
Browser: Chrome
Evergreen version: 4.27.2
React boilerplate: create-react-app

**Comment by mshwery** [comment]
@gohyifan if you use v4.25.0 or earlier, does the same thing happen?

**Comment by mshwery** [comment]
I was able to pinpoint this to something between v4.25.0-v4.26.0-0 but it doesn't affect all production builds. For instance, we're using v4.27.2 in production and the optimized webpack build is fine.

**Comment by mshwery** [comment]
Resolved by https://github.com/segmentio/evergreen/pull/809

**Comment by mshwery** [comment]
I clone your repo and upgraded to `v4.27.3` and was able `yarn build && serve -s build`

**Comment by gohyifan** [comment]
`v4.27.3` worked, thanks @mshwery !
