### ISSUE TITLE
Classnames not generating correctly on first load

### ISSUE THREAD

**Issue by Chrischuck** [segmentio/evergreen#810]
We are using Next.js `v9.3.1`. Not sure if it's a mix of issues with next and evergreeen or just evergreen.
 This works fine in development

We are statically exporting the next app as well see [this](https://nextjs.org/docs/advanced-features/static-html-export). Next.js has a two step build/export process for static sites.

The issue we are facing is below:
<img width="1163" alt="Screen Shot 2020-04-28 at 00 20 43" src="https://user-images.githubusercontent.com/13311268/80459023-9a409200-88e6-11ea-9e0b-9b2ae9db480e.png">
After refreshing page:
<img width="1163" alt="Screen Shot 2020-04-28 at 00 21 35" src="https://user-images.githubusercontent.com/13311268/80459052-a4629080-88e6-11ea-8818-7d99f20ee4bb.png">

On first load, the components won't be rendered correctly (see the header). If you navigate to another page, the new page will render correctly (content below the header). If I were to refresh the page, all of the components on the page would not be rendered correctly. The only difference I can see between the two is the way the classnames are getting generated. 1 gets generated with the box emoji, the other gets `ub`

[link](https://5ea7cf432c5ec60006de455a--jovial-kalam-174fd9.netlify.app/) to site

**Comment by Chrischuck** [comment]
Downgraded to version `4.23.3` in order to get it to work. 

I'm pretty sure this is because of https://github.com/segmentio/evergreen/pull/763

I'll test on `4.24.0` tomorrow

**Comment by mshwery** [comment]
@Chrischuck what version of evergreen were you on originally?

Are you using extractStyles? You may need to manually set `setClassNamePrefix` before consuming evergreen (both server and client-side) - you could try setting it back to the default `ub-`

**Comment by Chrischuck** [comment]
@mshwery I was on latest originally. I just tested `v4.24.0` and it seems that's the jump that breaks.

I forgot to mention I did try `setClassNamePrefix` but that didn't help

**Comment by Chrischuck** [comment]
I stand corrected, I gave `setClassNamePrefix('ub-')` another try and it works fine now
