### ISSUE TITLE
Button component "onClick" doesn't work inside popover.

### ISSUE THREAD

**Issue by DimitriMichel** [segmentio/evergreen#850]
**Describe the bug**
When creating a popover using lets say the "Basic Usage" as seen in the docs. 
if you were to add onClick function it doesn't appear to work at all.

If you take this same function and try add it into onOpenComplete in the popover props it immediately closes the popover.

v4.27.4

**Comment by hugosoftdev** [comment]
Hey, i tested this component a lot and i'm almost sure that the component is working properly. Make sure that when you are passing your function, you are not invoking it.

Example:

const myFunc = () => {
       alert("it opened");
}

<Popover
            onOpenComplete={myFunc} //instead of myFunc()
            position={Position.BOTTOM_LEFT}
            content={({ close }) => <ClosablePopoverContent close={close} />}
          >
            <Button marginRight={20}>Inside Scrolling Container</Button>
</Popover>

Let me know if that was the issue!

**Comment by mshwery** [comment]
If you can provide a minimal working reproduction of the issue we can take a look. You can fork this starter codesandbox to create: https://codesandbox.io/s/nifty-star-u4ilq?file=/src/App.js
