### ISSUE TITLE
BLM banner on Evergreen docs page

### ISSUE THREAD

**Issue by Chrischuck** [segmentio/evergreen#851]
Anyone opposed to adding this? Similar things w/ github and react

<img width="1440" alt="Screen Shot 2020-06-03 at 16 48 15" src="https://user-images.githubusercontent.com/13311268/83699892-1e5af900-a5ba-11ea-8d7f-f96c1b3342a6.png">

<img width="1440" alt="Screen Shot 2020-06-03 at 16 42 18" src="https://user-images.githubusercontent.com/13311268/83699895-2024bc80-a5ba-11ea-86d9-4daec52123b4.png">

**Comment by mshwery** [comment]
Shared this with the team (back when the issue was created, and will again now) for consideration! Thanks
