### ISSUE TITLE
Utility types no longer exported

### ISSUE THREAD

**Issue by seanemmer** [segmentio/evergreen#852]
In previous versions of evergreen the utility types at the top of index.d.ts were exported.  I have been extending these types when composing Evergreen components and removing this export is preventing my app from compiling.  

PositionTypes
...
FontSizeSmall

**Comment by mshwery** [comment]
Yeah – this is a byproduct of how we were using a module declaration... happy to review a PR that adds them back as exports in the index.d.ts file!

Otherwise, we can try to get to it soon // cc @colinlohner

**Comment by mshwery** [comment]
These types will be re-exported in the next version of v4.
