### ISSUE TITLE
SelectMenu styles missing (See screenshot)

### ISSUE THREAD

**Issue by ksinghj** [segmentio/evergreen#853]
**Describe the bug**
SelectMenu components missing styles (font missing, no uniform order of elements).

**To Reproduce**
1. Start Evergreen locally
2. Click on 'select-menu' tab
3. See that styles are not the same as the other pages

**Expected behavior**
The styling of the page is styled in a similar fashion to the rest of the site.

**Evergreen Version**
e.g. v4.24.1

**Screenshots**
![Screenshot 2020-06-06 at 10 26 07](https://user-images.githubusercontent.com/44725786/83941058-24322380-a7e0-11ea-93dd-2f5d6e080604.png)

**Environment (please complete the following information):**
 - OS: MacOS
- Chrome
 - Version 10.15.5, 83.0.4103.61

**Additional context**
Looks like a style rule is missing/override, or the styles were never there.

**Comment by ksinghj** [comment]
Currently working on this

**Comment by Ankit27Agg** [comment]
i want to work on it.
