### ISSUE TITLE
Button's textAlign="center" doesn't work. 

### ISSUE THREAD

**Issue by a-y-u-s-h** [segmentio/evergreen#857]
**Describe the bug**

After changing button's width - the label doesn't align to center automatically. 

```jsx
<Button appearance="primary" type="submit" disabled={isSubmitting} height={56} width="100%" textAlign="center">
Submit
</Button>
```
creates a button with label not properly aligned, like in this screenshot: 

![2020-06-13_17-01-03_screenshot](https://user-images.githubusercontent.com/19586719/84567953-ddbd6580-ad99-11ea-860a-a5e9cb3a387f.png)

In order to fix that, I had to do this: 

```jsx
<Button appearance="primary" type="submit" disabled={isSubmitting} height={56} width="100%" textAlign="center">
 <Pane display="grid" width="100%">Submit</Pane>
</Button>
```

Which would create:

![2020-06-13_17-13-51_screenshot](https://user-images.githubusercontent.com/19586719/84567994-25dc8800-ad9a-11ea-86cd-d21d92827cb1.png)

**Expected behavior**
Button's label should remain in center when the width changes.

**Evergreen Version**
v4.24.4

**Screenshots**
Provided above.

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Browser Chrome (but this info isn't relevant)

**Comment by mshwery** [comment]
Buttons have flex display so you can do `justifyContent="center"`

**Comment by a-y-u-s-h** [comment]
Nice. This isn't mentioned in the docs though.

**Comment by mshwery** [comment]
@a-y-u-s-h ah, good call out! We should include that detail.
