### ISSUE TITLE
Device: A component that solves the problem of Responsiveness.

### ISSUE THREAD

**Issue by a-y-u-s-h** [segmentio/evergreen#859]
**Is your feature request related to a problem? Please describe.**
One of the main criticisms of Evergreen is that it doesn't provide a component based solution to tackle responsiveness. From what I know after reading docs and spectrum chats, It's left upto the user to deal with media queries or in whichever way the user would like to tackle the problem of device-size based (responsive) component rendering.

**Describe the solution you'd like**
I would love to have a component (called `Device`) that renders childrens based on screen size passed as props. While dealing with Evergreen since last month, I have figured out one way to implement such component (implentation is towards the end of this issue). Before that, let me demonstrate the usage of the component.

Once the component is implemented, following usage of the component in code will render the children only in devices that match the dimensions of a..

1) Desktop (renders nothing on Mobiles or Tablets) -
 
```jsx
<Device desktop>
 <p>Hello</p>
</Device>
```

2) Mobile (renders nothing on Desktop or Tablets) -
 
```jsx
<Device mobile>
 <p>Hello</p>
</Device>
```

3) Tablet (render nothing on Desktop and Mobile) -
 
```jsx
<Device tablet>
 <p>Hello</p>
</Device>
```

4) Mobile and Desktops (not Tablets) -
 
```jsx
<Device desktop mobile>
 <p>Hello</p>
</Device>
```

And likewise, these props can be added all three at a time or two at a time, and the component must render based on screen sizes. An extra `not` boolean prop should reverse the result by other props. Useful when you want to keep the markup clean. Consider this code:

```jsx
<Device desktop>
 <p>Hello from Desktop</p>
</Device>
<Device not desktop>
 <p>Hello from Tablets or Mobile phones!</p>
</Device>
```

Also, for a finer control of responsiveness, `desktop`, `mobile` and `tablet` props can be either `boolean` or `string`. So that the usage becomes much better, like say there's a component `X` that must be rendered only on Medium & Large Desktops and Small mobile phones, the developer can write the following code: 

```jsx
<Device desktop="M L" mobile="S">
 <p>This component will be rendered only on M, L size desktops and S sized mobile phones!</p>
</Device>
```

**Describe alternatives you've considered**
I used `react-responsive` library to create the component that behaves the exact way I've described above. The implementation looks like this (Code may look very cringy but it works fine, it's not refactored yet):

```jsx
import { useMediaQuery } from "react-responsive"

export const Device = ({ children, desktop, mobile, tablet, not }) => {
  /*
    ======================================
      This component renders children
      based on size of the screen. The usage
      is extremely simple but the component
      definition looks kind of ugly.
    ======================================
  */
  let condition = false
  const validate = (variable, name) => {
    /*
      ======================================
        This function basically takes in
        the variable and the name of the variable
        (should lie as a key in 'range' variable below).
        And then implemnts all the logic required to set
        the final condition.
      ======================================
    */
    const range = {
      mobile: {
        S: { maxWidth: 320 },
        M: { minWidth: 321, maxWidth: 375 },
        L: { minWidth: 376, maxWidth: 425 },
        XL: { minWidth: 426, maxWidth: 767 },
        generic: { maxWidth: 767 }
      },
      tablet: {
        generic: { minWidth: 768, maxWidth: 991 }
      },
      desktop: {
        S: { minWidth: 992, maxWidth: 1024 },
        M: { minWidth: 1024, maxWidth: 1360 },
        L: { minWidth: 1360, maxWidth: 2000 },
        XL: { minWidth: 2000 },
        generic: { minWidth: 992 }
      }
    }
    /*
      ======================================
        If that variable is a stirng, then
        each word in that string must be a valid
        size. And if that's true then we include the
        contribution of condition corresponding to that
        size in the final result. If not, we simply ignore it.
      ======================================
    */
    if (variable) {
      if (typeof variable === "string" || variable instanceof String) {
        variable.split(" ").forEach(i => {
          const size = range[name] ? (range[name][i] ? useMediaQuery(range[name][i]) : undefined) : undefined
          if (typeof size !== "undefined") condition = condition || size
        })
      } else if (typeof variable === "boolean") {
        if (range[name]) condition = condition || useMediaQuery(range[name].generic)
      }
    }
  }
  /*
    ======================================
      Finally, we run the checks and also
      if user doesn't provide any device,
      by default its assumed that the children
      should be rendered on all screens.
    ======================================
  */
  validate(mobile, "mobile")
  validate(tablet, "tablet")
  validate(desktop, "desktop")
  if (!desktop && !mobile && !tablet) condition = true
  condition = not ? !condition : condition
  return condition ? children : null
}

```

**Comment by Chrischuck** [comment]
Cool idea! But could possibly become cluttered if you have to wrap every component in a `Device` 🤔

**Comment by a-y-u-s-h** [comment]
I'm glad to say that the naswer is 'NO!' :), the use of this `Device` component is optional. I've tried this several times - makes things very clean (compared to the usual media query alternative - for which I'll need to have a CSS file). You'd use it only when you want to render something different for different screen sizes. Like let's say you need to have a layout that becomes a 2 column layout on a mobile and a 3 column layout on a computer - you'd do this:

```jsx

export const Layout = ({ children }) => (
<Device desktop>
  <Pane display="grid" gridTemplateColumns="1fr 1fr 1fr">
    {children}
  </Pane>
</Device>
<Device not desktop>
  <Pane display="grid" gridTemplateColumns="1fr 1fr">
    {children}
  </Pane>
</Device>
)
```

Like, to render on every screen size, you just simply don't use the `Device` component or you use it by passing it all three props `tablet` `mobile` `desktop`.

**Comment by a-y-u-s-h** [comment]
@Chrischuck Should I send a PR for this?
