### ISSUE TITLE
Portal Improvement

### ISSUE THREAD

**Issue by a-y-u-s-h** [segmentio/evergreen#865]
**Is your feature request related to a problem? Please describe.**
While creating Chrome Extensions, you usually want to inject some react components in the right place - in a DOM that's not created by you. So you do this by mounting your app somewhere in the body. But this makes it hard to create Modals and stuff. Portal component doesn't work in this case for some reason. I've tried using `Dialog` component and `Dialog` component with a separate `Portal` wrapped around it - both didn't work.

**Describe the solution you'd like**
I propose an improvement to Portal component. From source code - current implementation of Portal simply injects the children somewhere in a `div` at the root of the body. `Portal` should be able to inject something anywhere - by taking in an optional prop called `node` or `target` or `parent`, and this would be helpful if I want to inject a button next to a table or some media (like there are several Chrome Extensions just doing this, infact a lot of it is just embedding some custom component into the web page after reading the web page if it's a browser action extension)

**Describe alternatives you've considered**
Custom Portal component.

**Additional context**
Here's the implementation of portal in the v5 branch right now - 

```jsx

import { Component } from 'react'
import canUseDom from 'dom-helpers/util/inDOM'
import ReactDOM from 'react-dom'
import PropTypes from 'prop-types'

let portalContainer

export default class Portal extends Component {
  constructor() {
    super()

    // This fixes SSR
    if (!canUseDom) return

    if (!portalContainer) {
      portalContainer = document.createElement('div')
      portalContainer.setAttribute('evergreen-portal-container', '')
      document.body.appendChild(portalContainer)
    }

    this.el = document.createElement('div')
    portalContainer.appendChild(this.el)
  }

  componentWillUnmount() {
    portalContainer.removeChild(this.el)
  }

  render() {
    // This fixes SSR
    if (!canUseDom) return null
    return ReactDOM.createPortal(this.props.children, this.el)
  }
}

Portal.propTypes = {
  children: PropTypes.node.isRequired
}

```

This is what I propose: 

```jsx

import { Component } from 'react'
import canUseDom from 'dom-helpers/util/inDOM'
import ReactDOM from 'react-dom'
import PropTypes from 'prop-types'

let portalContainer

export default class Portal extends Component {
  constructor() {
    super()

    // This fixes SSR
    if (!canUseDom) return

    if (!portalContainer) {
      portalContainer = document.createElement('div')
      portalContainer.setAttribute('evergreen-portal-container', '')
     document.querySelector(this.props.parent || "body").appendChild(portalContainer)
    }

    this.el = document.createElement('div')
    portalContainer.appendChild(this.el)
  }

  componentWillUnmount() {
    portalContainer.removeChild(this.el)
  }

  render() {
    // This fixes SSR
    if (!canUseDom) return null
    return ReactDOM.createPortal(this.props.children, this.el)
  }
}

Portal.propTypes = {
  children: PropTypes.node.isRequired,
  parent: PropTypes.string
}

```

**Comment by mshwery** [comment]
@a-y-u-s-h this sounds like a nice additive change. Feel free to push up your suggestion in a PR if you have time! If not, we'll take a look after v5 lands.

**Comment by treygriffith** [comment]
I'd say this change could also apply to the Toaster, which has the same issue. @a-y-u-s-h are you planning to add this? If not, I may take a stab at it.

**Comment by a-y-u-s-h** [comment]
@treygriffith I was going to, but I haven't contributed before to Evergreen so no idea how to start and I'm busy as well these days with another project. But I proposed the solution as well, it's a minor change in current implementation. Feel free to push it.

**Comment by akleiner2** [comment]
Going to close this out due to inactivity - solution sounds good though, so please feel free to add this whenever folks are able to get around to it.
