### ISSUE TITLE
FilePicker

### ISSUE THREAD

**Issue by christopherlaangsell** [segmentio/evergreen#866]
Hi there, I've been using Evergreen UI with ClojureScript via hiccup. All of the components have been working great except for FilePicker. This might be a hiccup error, but everything else has worked fine so I am submitting this just in case.

The FilePicker works as described; however, it shows a "Choose File" box to the left of the text input. I have tried commenting out that section of code in the FilePicker source code but then the functionality breaks. Here is what it looks like and here is my code in ClojureScript:

<img width="480" alt="Screen Shot 2020-06-30 at 8 25 25 AM" src="https://user-images.githubusercontent.com/56093917/86138115-43546600-baab-11ea-88e4-b6bf0c3040d3.png">

<img width="562" alt="Screen Shot 2020-06-30 at 8 26 12 AM" src="https://user-images.githubusercontent.com/56093917/86138191-60893480-baab-11ea-83cd-fea5bb52c706.png">

I am using Chrome Version 83.0.4103.116 (Official Build) (64-bit) for Mac and Evergreen v4.28.0.

**Describe the bug**

**To Reproduce**
1. Use component/props '...'
3. See error

_Links to a codesandbox reproduction are extremely useful here._ You can fork this starter to create a minimal reproduction of the issue: https://codesandbox.io/s/nifty-star-u4ilq?file=/src/App.js

**Expected behavior**

**Evergreen Version**
e.g. v4.24.1

**Screenshots**

**Environment (please complete the following information):**

**Additional context**

**Comment by mshwery** [comment]
Could you provide the details for each section of the bug report. Ideally you would provide a minimal reproduction (like a link to a codesandbox) so we can see the issue you are describing.

**Comment by christopherlaangsell** [comment]
I apologize that I have just come around to resolve this issue, but it is only recently that I found the source of the error. There is no error with Evergreen using Node to resolve dependencies, but I was using Shadow CLJS to resolve dependencies (I was coding in  ClojureScript). Unlike Node, Shadow's policy of package resolution only looks within the top-level node_modules folder for the package. While this might simplify things, in practice, projects can rely on a variety of dependency versions, and these versions are stored in a nested fashion e.g. node_modules/packageA/node_modules. Node does not have an issue handling this but Shadow does.

In Evergreen's case, Evergreen relies on Glamor, which relies on an outdated version of Inline Style Prefixer. But Evergreen also relies on UI Box and other dependencies which require a new version of Inline Style Prefixer. This disjunction forced Shadow to choose one version of Inline Style Prefixer and stick with it. Unfortunately, that resulted in some elements, like FilePicker, not being properly rendered. 

So once again, I do not really believe this is an issue on Evergreen's end - although they may want to be more cognizant that their dependency requirements better align for both performance reasons and for those using other compilers. For this reason I will close the issue.

For more information about this specific case, please see this repo detailing the problem context: https://github.com/kyptin/shadow-cljs-example-breakage

And this pull request to Shadow presenting the benefits to a resolution process more aligned with Node's:
https://github.com/thheller/shadow-cljs/issues/892
