### ISSUE TITLE
v5 doesn't apply padding to `<IconButton>` correctly

### ISSUE THREAD

**Issue by cstrat** [segmentio/evergreen#900]
v5.0.0-5 doesn't apply padding to `<IconButton>` correctly.
Regular `<Button>` works fine, just seems to affect the IconButton component.
_Note, this is using external SVG icons from FontAwesome._

See repo here:
https://codesandbox.io/s/v5-padding-bug-dohc8?file=/src/App.js

![image](https://user-images.githubusercontent.com/4209076/88117741-4997b700-cbff-11ea-82ec-a36497577d20.png)

**Comment by cstrat** [comment]
Actually I just noticed in CodeSandbox that -5 isn't the latest. I have been using @next with npm to update (saw that posted somewhere).

There are releases up to -10 and also Alpha0 and Alpha1.
Which should I be using as the latest?

**Comment by mshwery** [comment]
Latest `5.0.0-10` has resolved this issue!

**Comment by mshwery** [comment]
@cstrat you can use `npm install evergreen-ui@next` to get the latest. Ignore the `alpha` ones.
