### ISSUE TITLE
v5 - SelectMenu: Cannot read property 'focus' of null

### ISSUE THREAD

**Issue by cstrat** [segmentio/evergreen#901]
In v5 there appears to be a new bug where the SelectMenu search/filter field doesn't get given focus, but in trying to do so evergreen bugs out.

Reproduction here: https://codesandbox.io/s/selectmenu-error-fr28r

There appears to be reference in the source to the hacky solution that was put in place here.

![image](https://user-images.githubusercontent.com/4209076/88172476-674b3780-cc64-11ea-9020-834bcf8ffbd3.png)

https://github.com/segmentio/evergreen/issues/90

**Comment by mshwery** [comment]
Thanks for reporting @cstrat ! We've noticed some related issues with Popovers/Overlays too – seems like some ref handling isn't working as expected.

**Comment by mshwery** [comment]
This has been fixed on latest `v5` branch and will be in the next release candidate.
