### ISSUE TITLE
v5 - RadioGroup not working (tested across all v5 releases)

### ISSUE THREAD

**Issue by cstrat** [segmentio/evergreen#911]
Seems to be an issue with events on RadioGroup in v5.
See the repo below. If you flick the dependency back to v4 it all works fine.

Repo:
https://codesandbox.io/s/radiogroup-syntheticevent-issue-itumx?file=/src/App.js

**Comment by cstrat** [comment]
You know what would be cool, if we could view the docs and toggle which version of Evergreen to use in the docs.

**Comment by mshwery** [comment]
> You know what would be cool, if we could view the docs and toggle which version of Evergreen to use in the docs.

Love that idea. Might be something we explore after pushing through the v5 release.

**Comment by mshwery** [comment]
This should be resolved in the next v5 release candidate.

**Comment by mshwery** [comment]
Works on latest v5! https://codesandbox.io/s/radiogroup-syntheticevent-issue-qn760?file=/src/App.js

**Comment by cstrat** [comment]
> > You know what would be cool, if we could view the docs and toggle which version of Evergreen to use in the docs.
> 
> Love that idea. Might be something we explore after pushing through the v5 release.

I am happy to spend some time later this week making a kitchen sink repo in code sandbox which could serve that purpose for now. 👍

> Works on latest v5! https://codesandbox.io/s/radiogroup-syntheticevent-issue-qn760?file=/src/App.js

Amazing, thanks!
