### ISSUE TITLE
v5 - Menu Icons & Button Icon padding

### ISSUE THREAD

**Issue by cstrat** [segmentio/evergreen#925]
Hi,

Hopefully I didn't just overlook a step in the migration guide (padding doesn't seem to be mentioned), but I was using the pre-release without issue prior to upgrading to 5.0.3.
Padding seems to have dropped off.

![image](https://user-images.githubusercontent.com/4209076/89609560-947e2380-d8bb-11ea-9395-8a70be5478b4.png)

Repo:
https://codesandbox.io/s/v5-padding-bug-dohc8?file=/src/App.js

**Comment by cstrat** [comment]
I think I noticed why this is happening.
Looks like the elements are passing in `marginLeft` to the `Icon` - but I am using `FontAwesome` icon's and because of that the marginLeft doesn't mean anything and is the cause for the errors in the console.

**Comment by colinlohner** [comment]
Hey @cstrat, yeah it does look like an incompatibility issue with FontAwesome. I took a second and worked up a quick fix you could implement to solve it. This isn't an Evergreen issue specifically as you are using a thirdparty icon library.

Hope this helps, happy to answer any questions or talk further.

https://codesandbox.io/s/v5-padding-bug-forked-cr2yv?file=/src/App.js

**Comment by colinlohner** [comment]
One other issue I noticed is that FontAwesome has its own size prop that doesn't map to what we use. In the codesandbox I strip that prop out, however you could map our sizes to the FontAwesome ones if you wanted.

**Comment by mshwery** [comment]
@colinlohner @cstrat we may want to consider passing all of these props to an evergreen/ui-box-controlled component so that the spacing concerns are kept intact regardless of the component being passed in.

**Comment by colinlohner** [comment]
@mshwery you raise a good point. Still wouldn't solve color and size, but would at least preserve spacing. I'll get a PR together for this

**Comment by colinlohner** [comment]
Okay this will be shipped as part of a release we are going to cut today

**Comment by colinlohner** [comment]
You may still have to do something similar to the codesandbox in order to handle colors or size. FontAwesome does respect font size so you may be okay without dealing with size

**Comment by colinlohner** [comment]
Released you can now use as you were and the positioning will be handled.

Available in v5.0.4
