### ISSUE TITLE
Pagination component suggestion  

### ISSUE THREAD

**Issue by salah-ahmed** [segmentio/evergreen#928]
Hi,

I was using zendesk Pagination component and I would love to include a similar one to evergreen components 

I think it can be implemented with Button & Pane components

PROPS

|  Prop | Type  | Default |  Description | 
|---|---|---|---|
| currentPage  | number  | Required  | The currently selected page  
| totalPages | number | Required | The total number of pages available
| onChange | (currentPage) => void  | ArgumentscurrentPage The currently selected page
| pageGap | number? | 2 | Position for the leading and trailing gap indicator, if needed based on current and total pages
| pagePadding | number? | 2 | The number of pages to pad the current page with when page gaps are displayed

Usage
```js
<Pagination currentPage={page} totalPages={numberOfPages} onChange={(currentPage) => setPage(currentPage) }/>
```

How it will look like
![Pagintion](https://user-images.githubusercontent.com/23643923/89716351-7cd29800-d9ac-11ea-826a-4f60d36d6d6a.PNG)

**Comment by colinlohner** [comment]
HI @salah-ahmed ! Thanks for the suggestion. We have talked about this internally as well, but it hasn't been prioritized. I'll bring it up again with the team, and get you more specifics

**Comment by salah-ahmed** [comment]
Awesome, if you decide to add it I will be thrilled to work on an implementation for it

**Comment by colinlohner** [comment]
Hey @salah-ahmed, I think it would be nice to add this component to Evergreen, however we do not currently have a specific need for it internally at the moment. That being said, we will put it on the roadmap. Just for transparency, it may be a little while until we are able to create the designs for it, and get it prioritized.
