### ISSUE TITLE
Bug: Sample Code on Evergreen Website has Syntax Error

### ISSUE THREAD

**Issue by jchengjr77** [segmentio/evergreen#937]
Hey,

I was just trying to learn about Evergreen UI, and was reading through documentation. When I got to the theming page, I saw that the sample code embedded in the page shows an error:

`SyntaxError: Unexpected token (1:8)
1 : return (const newTheme = {`

I found this at https://evergreen.segment.com/get-started/theming/

Not sure if it is a problem on my end or with the documentation itself. 

Thank you!

**Comment by akleiner2** [comment]
Closing this out as the new site has shipped.
