### ISSUE TITLE
Dialog: className props not added to Dialog component

### ISSUE THREAD

**Issue by Valentindi** [segmentio/evergreen#940]
Hey, thanks for this great work.

In the last days I was writing some test cases, I encountered the problem that class names added to the dialog component are not rendered.
Did you implement this on purpose? If not, it would make it much easier for me to develop.

Thanks

**Comment by akleiner2** [comment]
@Valentindi  The `<Dialog />` component is broken up into an overlay and the actual dialog container. Depending on which you're trying to add a `className` to, you probably want `<Dialog containerProps={{ className: 'your-css-class-here' }} ... />` or `<Dialog overlayProps={{ className: 'your-css-class-here' }} ... />`. Let me know if this works!

**Comment by akleiner2** [comment]
Hey @Valentindi going to close this out - but let me know if you still see issues with the proposed solution!
