### ISSUE TITLE
Tab's className has been replaced

### ISSUE THREAD

**Issue by leesiongchan** [segmentio/evergreen#946]
When I try to
```
<Tab className="hello">
```
I will lose the theme classes defined by the lib, do you think it makes sense to add the capability to allow the user to extend their own classes?

https://github.com/segmentio/evergreen/blob/master/src/tabs/src/Tab.js#L90

**Comment by akleiner2** [comment]
Hey @leesiongchan - you are correct. We do this elsewhere in Evergreen, (by composing a passed-in `className` with the `classnames` package). Happy to accept a PR to add this functionality!
