### ISSUE TITLE
tooltip with showDelay unexpected results

### ISSUE THREAD

**Issue by jasan-s** [segmentio/evergreen#996]
using the Tooltip component with showDelay in a listitem renders unexpected results:

Issue: if I set the showDelay value to 3000, and move mouse over 10 items in a list(all wrapped with tooltip) all of them show tooltip after the delayTime and do not disappear unless i hover mouse over the items again.

expected: with 3000ms showDelay set, if i hover over an item for more then 3000ms the tooltip is shown else it never renders .

**Comment by colinlohner** [comment]
This appears to be a valid issue, and we will look into it as soon as we are able! Thank you for bringing it to our attention.

**Comment by akleiner2** [comment]
This should be fixed up with #1011 , so going to cut a release some time today or tomorrow, and close this out 👍 . Thanks for reporting!

**Comment by akleiner2** [comment]
@jasan-s This should be fixed in `5.1.0`, do you mind updating and taking a look? Thanks!
